// src/scaffold/hook.ts -- the Akatsuki-Agent:/Akatsuki-Run: trailer-enforcing
// commit-msg hook.
//
// THIS HOOK NEVER EXISTED IN bankai-core. Its trailer pair is bankai-core's
// own naming convention renamed (Bankai-Agent:/Bankai-Run: -> Akatsuki-
// Agent:/Akatsuki-Run:, the migration's own global rename), but the HOOK
// ITSELF -- a commit-msg guard that enforces the trailer is present and
// well-formed on an automated commit -- is new: bankai-core's commits carry
// the trailer by convention, unchecked. Scaffold output is where it is
// specified to live (issue #4, artifact assumption 3), so it is authored
// fresh here rather than ported from anywhere.
//
// ENFORCEMENT IS CONDITIONAL ON THE ENVIRONMENT, NOT ON EVERY COMMIT. A human
// typing `git commit` at a keyboard is not an automated run and carries no
// obligation to add either trailer. The hook only requires them when an
// automated commit says so of ITSELF -- the caller-named environment variable
// being set is what marks a commit as automated -- so a human's ordinary
// workflow is never touched by this at all. Getting that backwards (requiring
// the trailer on every commit) would make every human commit fail a hook
// installed by a scaffold nobody read the fine print of.
//
// THE TRAILER NAMES ARE CALLER DATA. Which two trailer keys this hook
// enforces, and which environment variable marks an automated commit, are
// supplied by the caller (../scaffold/verb.ts's flags) -- this system serves
// more than one target, and a literal 'Akatsuki-Agent' baked into shipped
// code would be exactly the persona-naming violation §3 exists to catch, even
// though this specific pair is Akatsuki's own by design (the caller is free
// to pass exactly that pair; the point is that THIS module does not assume
// it).

import { chmodSync, writeFileSync } from "node:fs";

/**
 * Write a generated hook and make it executable, in that order.
 *
 * BOTH VERBS GO THROUGH THIS ONE FUNCTION, and the mode is why. `git` will not
 * run a `commit-msg` hook that is not executable -- it skips it, silently, on
 * every commit -- so a hook written 0644 is a hook that reports `created` and
 * enforces nothing. `nen scaffold new` shipped one for exactly as long as it had
 * its own two-line writer beside `nen scaffold init`'s three-line one; one
 * writer is one place the mode is set.
 *
 * A FAILED `chmod` IS NOT A FAILED INSTALL. Windows filesystems do not model
 * the POSIX executable bit and `git` only consults it on a POSIX checkout, so
 * the bit is set where it means something and its absence is not an error where
 * it does not. The write itself is NOT caught here: a `commit-msg` hook that
 * could not be written is a fact the caller has to hear about, and each verb
 * records it with the errno.
 */
export function writeHookFile(path: string, body: string): void {
  writeFileSync(path, body, "utf8");
  try {
    chmodSync(path, 0o755);
  } catch {
    // See above: the bit is advisory on the platforms where this throws.
  }
}

export interface HookSpec {
  /** The trailer key naming which agent/persona made an automated commit. */
  readonly agentTrailer: string;
  /** The trailer key naming which CI run produced an automated commit. */
  readonly runTrailer: string;
  /** The environment variable whose presence marks a commit as automated. */
  readonly markerEnvVar: string;
}

// A POSIX sh script -- portable to the Windows Git Bash lane this repository's
// own CI already runs on (.gitattributes' `* text=auto`, the CRLF discipline
// every parser here already follows), and to any Unix scaffold target.
export function renderCommitMsgHook(spec: HookSpec): string {
  return `#!/bin/sh
# commit-msg -- enforces the ${spec.agentTrailer}:/${spec.runTrailer}: trailer
# pair on an AUTOMATED commit only. Generated by 'nen scaffold init'.
#
# A commit is "automated" iff ${spec.markerEnvVar} is set in the environment
# the commit runs in. An ordinary human commit at a keyboard carries no such
# variable and is never touched by this hook.

set -eu

msg_file="\$1"

if [ -z "\${${spec.markerEnvVar}:-}" ]; then
  # Not an automated commit -- nothing to enforce.
  exit 0
fi

if ! grep -qE '^${spec.agentTrailer}: .+' "\$msg_file"; then
  echo "commit-msg: ${spec.markerEnvVar} is set (an automated commit) but the message carries no '${spec.agentTrailer}: <value>' trailer." >&2
  exit 1
fi

if ! grep -qE '^${spec.runTrailer}: .+' "\$msg_file"; then
  echo "commit-msg: ${spec.markerEnvVar} is set (an automated commit) but the message carries no '${spec.runTrailer}: <value>' trailer." >&2
  exit 1
fi

exit 0
`;
}
