// src/scaffold/init.ts -- the deterministic half of project scaffolding:
// directory layout, the commit-msg hook, and a canon-values template.
//
// SCOPE, STATED HONESTLY. bankai-scaffold's full role is an interactive,
// per-scenario project generator (seven scenario scripts, each laying out a
// stack-specific tree of source files, CI workflows and config). That
// generation is NOT ported here -- it is a large, scenario-specific body of
// work this pass did not reach, and pretending otherwise would be worse than
// naming the gap. What IS absorbed, and is the part the issue calls out by
// name, is the part every scaffolded project needs regardless of scenario:
// the directory skeleton, the trailer-enforcing commit-msg hook
// (../scaffold/hook.ts -- new, never existed in bankai-core), and a
// canon-values.yml template ready for 'nen canon mirror generate' to consume.
// A later pass absorbing the seven scenario generators extends this module
// rather than replacing it.

import { chmodSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { renderCommitMsgHook, type HookSpec } from "./hook.js";

export interface ScaffoldInitOptions {
  readonly root: string;
  /** Repo-relative directories to create, e.g. ["src", "tests", "docs"]. */
  readonly directories: readonly string[];
  readonly hook: HookSpec;
  /** Repo-relative path for the git hook. Default '.git/hooks/commit-msg'. */
  readonly hookPath?: string;
  /** Repo-relative path for the canon-values template. Omit to skip it. */
  readonly canonValuesPath?: string;
  readonly scenario?: string;
}

export interface ScaffoldInitResult {
  readonly createdDirectories: readonly string[];
  readonly hookWritten: string;
  readonly canonValuesWritten: string | null;
}

function ensureDir(path: string, created: string[]): void {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true });
    created.push(path);
  }
}

export function renderCanonValuesTemplate(scenario: string | undefined): string {
  const lines = [
    "# Generated by 'nen scaffold init'. Bind every {{TOKEN}} 'nen canon mirror generate'",
    "# needs for this repo's rule set. See handbooks/stacks/<scenario>/rules/placeholders.md",
    "# in the canon source for the token registry.",
  ];
  if (scenario !== undefined) lines.push(`scenario: ${scenario}`);
  lines.push("values:");
  lines.push("  # TOKEN_NAME: literal value");
  return `${lines.join("\n")}\n`;
}

export function scaffoldInit(options: ScaffoldInitOptions): ScaffoldInitResult {
  const createdDirectories: string[] = [];
  for (const dir of options.directories) {
    ensureDir(join(options.root, dir), createdDirectories);
  }

  const hookPath = join(options.root, options.hookPath ?? join(".git", "hooks", "commit-msg"));
  ensureDir(dirname(hookPath), createdDirectories);
  writeFileSync(hookPath, renderCommitMsgHook(options.hook), "utf8");
  try {
    chmodSync(hookPath, 0o755);
  } catch {
    // Windows filesystems that do not model the POSIX executable bit --
    // git itself only consults it on a POSIX checkout, so a failed chmod
    // here is not a failure of the hook install.
  }

  let canonValuesWritten: string | null = null;
  if (options.canonValuesPath !== undefined) {
    const path = join(options.root, options.canonValuesPath);
    ensureDir(dirname(path), createdDirectories);
    if (!existsSync(path)) {
      writeFileSync(path, renderCanonValuesTemplate(options.scenario), "utf8");
    }
    canonValuesWritten = path;
  }

  return { createdDirectories, hookWritten: hookPath, canonValuesWritten };
}
