// src/wc/mechanical.ts -- the conflict classes `nen wc catch-up` reports
// (zheref/nen#326): every conflicted path is a version MANIFEST, a
// CHANGELOG, a declared generated MIRROR, or OTHER, read off the
// repository's own `nen/contract.json` `mechanical` block.
//
// WHY THIS EXISTS. On a repository that releases in parallel, the same three
// conflict shapes come back on every catch-up -- both sides bumped the
// plugin manifests, both sides added the changelog's top section, both sides
// regenerated the mirrors -- and the verb handed them back as undifferentiated
// hand work every time. The verb was right to stop; what was missing was what
// it said when it did.
//
// IT RESOLVES NOTHING. This module classifies and composes the commands a
// caller would run; nothing here is spawned, by this module or by the verb.
// A manifest's next version is a release decision (zheref/hatsu#158), a
// changelog's two sections are both kept by whoever reads them, and a mirror
// is regenerated by the caller with the command its declaration states.
//
// MECHANICAL MEANS EVERY PATH, AND A DECLARATION THAT WAS READ. One `other`
// path, a missing block or an unreadable contract and the stop is the
// ordinary one -- exit 1, as before. Only a stop whose every conflicted path
// is in the declared set earns the distinct exit, because a caller branching
// on it is about to treat the whole stop as mechanical.
//
// PRECEDENCE: manifest, then changelog, then each mirror in declared order.
// A path two globs both match is the first one's -- stated, because globs
// cannot be proved disjoint when the file is loaded.

import { plainLine } from "../cli/plain.js";
import { loadContract, type MechanicalBlock } from "../schema/contract.js";
import { SchemaError } from "../schema/errors.js";
import { CONTRACT_FILE, resolveSchemaFile } from "../schema/source.js";
import { matchesAnyGlob } from "../shu/evidence/glob.js";
import { shellSingleQuote } from "../shu/render.js";

export type ConflictClass = "manifest" | "changelog" | "mirror" | "other";

export const CONFLICT_CLASSES: readonly ConflictClass[] = ["manifest", "changelog", "mirror", "other"];

/** `wc catch-up`'s exit when every conflicted path is in the declared mechanical set. */
export const EXIT_ALL_MECHANICAL = 3;

/**
 * Whether the declaration was read, and what it said.
 *
 *   * `not-read`   -- nothing conflicted, so the file was never opened;
 *   * `absent`     -- no `nen/contract.json`, or one with no `mechanical` block;
 *   * `declared`   -- the block was read and every path classified against it;
 *   * `unreadable` -- the file is there and nen could not read it (`error`).
 *
 * The last two are never collapsed into each other or into `absent`: "nothing
 * declared" and "nen could not tell" want different reactions.
 */
export type DeclarationState = "not-read" | "absent" | "declared" | "unreadable";

export interface MechanicalDeclaration {
  readonly state: DeclarationState;
  readonly block: MechanicalBlock | null;
  readonly error: string | null;
}

export const NOT_READ: MechanicalDeclaration = { state: "not-read", block: null, error: null };

/** Read `nen/contract.json`'s `mechanical` block from the working tree. Never throws on a bad file. */
export function loadMechanical(root: string): MechanicalDeclaration {
  if (!resolveSchemaFile(root, CONTRACT_FILE).canonical.present) return { state: "absent", block: null, error: null };
  try {
    const contract = loadContract(root);
    return contract.mechanical === null
      ? { state: "absent", block: null, error: null }
      : { state: "declared", block: contract.mechanical, error: null };
  } catch (error) {
    if (!(error instanceof SchemaError)) throw error;
    return { state: "unreadable", block: null, error: error.message };
  }
}

/** One class's share of a stop: the paths in it, and how a caller resolves them. */
export interface ResolveGroup {
  readonly class: Exclude<ConflictClass, "other">;
  /** For a mirror, the declared entry's own globs; empty for the other two. */
  readonly globs: readonly string[];
  readonly paths: readonly string[];
  /** What is the caller's to do, in a sentence. */
  readonly note: string;
  /** Each command, as an argv, in order. PRINTED, never run. */
  readonly steps: readonly (readonly string[])[];
}

export interface Classification {
  readonly classes: ReadonlyMap<string, ConflictClass>;
  readonly counts: Readonly<Record<ConflictClass, number>>;
  /** True only when the block was read and every one of at least one path is in it. */
  readonly mechanical: boolean;
  readonly resolve: readonly ResolveGroup[];
}

/** One conflicted path, as far as classification needs it: its name and whether the BASE's side still has it. */
export interface ClassifiedInput {
  readonly path: string;
  /** False when the base deleted the path (its stage is absent). */
  readonly baseSide: boolean;
}

function classOf(path: string, block: MechanicalBlock | null): { readonly kind: ConflictClass; readonly mirror: number | null } {
  if (block === null) return { kind: "other", mirror: null };
  if (matchesAnyGlob(path, block.manifests)) return { kind: "manifest", mirror: null };
  if (matchesAnyGlob(path, block.changelog)) return { kind: "changelog", mirror: null };
  const mirror = block.mirrors.findIndex((entry): boolean => matchesAnyGlob(path, entry.paths));
  return mirror === -1 ? { kind: "other", mirror: null } : { kind: "mirror", mirror };
}

/**
 * Every path's class, the counts, and the resolve groups. `strategy` decides
 * which `git checkout` flag names the BASE's side for a mirror: stage 3
 * (`--theirs`) on a merge, stage 2 (`--ours`) on a rebase -- the same
 * reversal ./catchup.ts's header states for the report's own labels.
 */
export function classifyConflicts(
  conflicted: readonly ClassifiedInput[],
  declaration: MechanicalDeclaration,
  strategy: "rebase" | "merge",
): Classification {
  const block = declaration.state === "declared" ? declaration.block : null;
  const classes = new Map<string, ConflictClass>();
  const counts: Record<ConflictClass, number> = { manifest: 0, changelog: 0, mirror: 0, other: 0 };
  const manifests: string[] = [];
  const changelogs: string[] = [];
  const mirrors = new Map<number, ClassifiedInput[]>();
  for (const conflict of conflicted) {
    const { kind, mirror } = classOf(conflict.path, block);
    classes.set(conflict.path, kind);
    counts[kind] += 1;
    if (kind === "manifest") manifests.push(conflict.path);
    if (kind === "changelog") changelogs.push(conflict.path);
    if (kind === "mirror" && mirror !== null) mirrors.set(mirror, [...(mirrors.get(mirror) ?? []), conflict]);
  }
  const resolve: ResolveGroup[] = [];
  if (manifests.length > 0) {
    resolve.push({
      class: "manifest",
      globs: [],
      paths: manifests,
      note: "both sides moved the version. Which version this branch ships is a release decision nen does not make: write it into each manifest, then stage them",
      steps: [["git", "add", "--", ...manifests]],
    });
  }
  if (changelogs.length > 0) {
    resolve.push({
      class: "changelog",
      globs: [],
      paths: changelogs,
      note: "both sides added entries. Keep both sides' entries and remove the markers -- nen drops neither and orders neither -- then stage it",
      steps: [["git", "add", "--", ...changelogs]],
    });
  }
  const baseFlag = strategy === "merge" ? "--theirs" : "--ours";
  for (const [index, entries] of [...mirrors.entries()].sort(([a], [b]): number => a - b)) {
    const entry = block?.mirrors[index];
    if (entry === undefined) continue;
    const kept = entries.filter((conflict): boolean => conflict.baseSide).map((conflict): string => conflict.path);
    const gone = entries.filter((conflict): boolean => !conflict.baseSide).map((conflict): string => conflict.path);
    const steps: (readonly string[])[] = [];
    if (kept.length > 0) steps.push(["git", "checkout", baseFlag, "--", ...kept]);
    if (gone.length > 0) steps.push(["git", "rm", "--quiet", "--", ...gone]);
    steps.push(entry.regenerate);
    steps.push(["git", "add", "-A", "--", ...entry.paths.map((glob): string => `:(glob)${glob}`)]);
    resolve.push({
      class: "mirror",
      globs: entry.paths,
      paths: entries.map((conflict): string => conflict.path),
      note: `generated, so neither side is kept: regenerate it AFTER every non-mirror conflict is resolved, because it is generated from those sources. The base's side (${baseFlag} on a ${strategy}) is checked out first only so a generator that refuses to overwrite a file it did not write can run; the regenerate rewrites it either way`,
      steps,
    });
  }
  const total = conflicted.length;
  return {
    classes,
    counts,
    mechanical: block !== null && total > 0 && counts.other === 0,
    resolve,
  };
}

/** An argv as ONE line a POSIX shell reads back as the same argv. */
export function renderCommand(argv: readonly string[]): string {
  return argv.map((token): string => (/^[A-Za-z0-9_./=@%+,-]+$/.test(token) ? token : shellSingleQuote(token))).join(" ");
}

/** The text rendering's classification block -- every path under its class, every step as a command line. */
export function renderClassification(
  classification: Classification,
  declaration: MechanicalDeclaration,
  others: readonly string[],
): readonly string[] {
  const { counts } = classification;
  const total = counts.manifest + counts.changelog + counts.mirror + counts.other;
  const lines: string[] = [];
  const tally = CONFLICT_CLASSES.map((kind): string => `${counts[kind]} ${kind}`).join(", ");
  if (declaration.state === "absent") {
    lines.push(`classes: ${tally} -- ${CONTRACT_FILE} declares no 'mechanical' block, so every path is 'other'`);
  } else if (declaration.state === "unreadable") {
    lines.push(`classes: ${tally} -- ${CONTRACT_FILE} could not be read (${declaration.error ?? "unknown error"}), so every path is reported as 'other'`);
  } else {
    lines.push(`classes: ${tally} (by ${CONTRACT_FILE}'s 'mechanical' block)`);
  }
  lines.push(
    classification.mechanical
      ? `all ${total} conflicted path(s) are mechanical -- exit ${EXIT_ALL_MECHANICAL}; nen resolved none. Resolve them in this order, then re-run the same command:`
      : `${counts.other} path(s) are not mechanical -- exit 1; resolve them by hand, then re-run the same command`,
  );
  for (const group of classification.resolve) {
    const label = group.class === "mirror" ? `mirror ${group.globs.join(", ")}` : group.class;
    lines.push(`  ${plainLine(label)} (${group.paths.length}): ${group.note}`);
    for (const step of group.steps) lines.push(`    $ ${plainLine(renderCommand(step))}`);
  }
  if (others.length > 0) {
    lines.push(`  other (${others.length}): a judgement nen does not make -- ${others.map((path): string => plainLine(path)).join(", ")}`);
  }
  return lines;
}
