// src/surface/command.ts -- `nen surface mirror generate|check`: one skills
// directory, rendered into the layout and frontmatter another agent surface
// documents for itself.
//
// WHY IT IS A FAMILY AND NOT A FLAG ON `canon mirror`. The two mirrors answer
// the same QUESTION ("is the committed copy still an image of its source?") and
// share none of its INPUTS: canon substitutes `{{TOKEN}}` bindings from a values
// file and pins a ref; this one filters frontmatter keys per a surface's own
// documentation and rewrites invocation spellings. Folding them together would
// have produced a verb with two disjoint halves of required flags and a
// `--kind` to say which -- the shape ../cli/registry.ts's header exists to keep
// out of this binary.
//
// NEITHER VERB DECIDES ANYTHING. `generate` writes the mirror the table
// describes; `check` says how the committed one differs. Neither opens a pull
// request, neither installs anything into a surface's real skills directory, and
// neither judges whether a skill is any good for the surface it is being
// mirrored into.

import { resolve } from "node:path";
import {
  emit,
  requireSubcommand,
  VerbUsageError,
  type Command,
  type CommandContext,
} from "../cli/command.js";
import { isContained } from "../repo/contain.js";
import {
  checkSurfaceMirror,
  generateSurfaceMirror,
  mirrorReportOk,
  readSourceAgents,
  readSourceSkills,
  SurfaceMirrorError,
  writeSurfaceMirror,
  type GeneratedFile,
  type SourceAgent,
} from "./mirror.js";
import { findSurface, SURFACES, surfaceNames, type SurfaceRow } from "./rules.js";

export const GENERATE_CONTRACT = "nen.surface.mirror.generate/v0.1";
export const CHECK_CONTRACT = "nen.surface.mirror.check/v0.1";

const SURFACE_LIST = SURFACES.map((row): string => `    ${row.surface.padEnd(8)} ${row.summary}`).join("\n");

const USAGE = `nen surface -- mirror a skills directory into another agent surface's own layout.

usage:
  nen surface mirror generate --source <dir> --surface <name> --out <dir>
                              [--agents <dir>] [--invocation-prefix <prefix>]
                              [--dry-run] [--json]
  nen surface mirror check    --source <dir> --surface <name> --out <dir>
                              [--agents <dir>] [--invocation-prefix <prefix>]
                              [--json]

For every '<name>/SKILL.md' under --source, writes '<out>/<name>/SKILL.md': the
body verbatim, the frontmatter reduced to the keys the surface documents, and --
where the surface documents an explicit invocation spelling -- every
'<prefix><name>' mention rewritten into it. Every generated file carries a
one-line 'GENERATED by nen surface mirror' marker as its first MARKDOWN line
(after the frontmatter fence, because the surface needs that fence first).

surfaces (src/surface/rules.ts -- one row each, with the page every fact was
read from):
${SURFACE_LIST}

  --source <dir>              REQUIRED. The directory whose SUBDIRECTORIES are
                              the skills. One with no <name>/SKILL.md in it is
                              refused rather than mirrored as empty.
  --surface <name>            REQUIRED. A row in the table above; anything else
                              is refused, naming the ones that exist.
  --out <dir>                 REQUIRED. Where the mirror goes. A path INSIDE
                              --source is refused: the mirror would become part
                              of the source it is generated from.
  --agents <dir>              A directory of '*.md' persona files. Where the
                              surface documents per-persona files they are
                              written one apiece; where it documents none, every
                              persona becomes a section of the one prose
                              document the row names.
  --invocation-prefix <p>     The SOURCE's own invocation namespace (e.g.
                              'myplugin:'). Caller data, never a literal in this
                              binary. Without it nothing is rewritten.
  --dry-run                   generate only. Reports exactly what it would write
                              and writes nothing.

'check' regenerates in memory and diffs the committed mirror, writing nothing at
all. A file is MISSING (generated, not in --out), EXTRA (in --out's mirror
universe, with no source), STALE (marked, but for a different surface),
HAND_EDITED (marked for this surface, bytes differ from a fresh generation) or
OK. Only '<name>/SKILL.md' and the row's own persona files are in that universe;
anything else --out holds is neither checked nor deleted.

Exit codes: 0 a completed generate, or a check with no drift; 1 a check with any
drift; 2 a missing or unknown flag, an --out inside --source, a --source with no
SKILL.md, a skill missing a key the surface requires, or a destination that
exists and carries no marker (this verb never overwrites a hand-written file).`;

const SUBCOMMAND_FLAGS: Readonly<Record<string, { values: readonly string[]; booleans: readonly string[] }>> = {
  generate: { values: ["source", "agents", "surface", "out", "invocation-prefix"], booleans: ["dry-run"] },
  check: { values: ["source", "agents", "surface", "out", "invocation-prefix"], booleans: [] },
};

const FAMILY_VALUES = [
  ...new Set(Object.values(SUBCOMMAND_FLAGS).flatMap((spec): readonly string[] => spec.values)),
].sort();
const FAMILY_BOOLEANS = [
  ...new Set(Object.values(SUBCOMMAND_FLAGS).flatMap((spec): readonly string[] => spec.booleans)),
].sort();

/** Refused rather than ignored -- ../report/command.ts's argument, verbatim. */
function refuseForeignFlags(subcommand: string, context: CommandContext): void {
  const spec = SUBCOMMAND_FLAGS[subcommand];
  /* c8 ignore next -- the subcommand was already checked against the same keys */
  if (spec === undefined) return;
  const known = new Set([...FAMILY_VALUES, ...FAMILY_BOOLEANS]);
  const mine = new Set([...spec.values, ...spec.booleans]);
  const foreign = [...Object.keys(context.args.values), ...context.args.booleans].filter(
    (flag): boolean => known.has(flag) && !mine.has(flag),
  );
  if (foreign.length === 0) return;
  throw new VerbUsageError(
    `--${[...new Set(foreign)].sort().join(", --")} ${foreign.length === 1 ? "is" : "are"} not read by 'surface mirror ${subcommand}'. A flag accepted and ignored is worse than one refused: the ignored thing is the instruction you gave.`,
  );
}

function required(context: CommandContext, flag: string, why: string): string {
  const value = context.args.values[flag];
  if (value === undefined || value.trim() === "") throw new VerbUsageError(`--${flag} is required. ${why}`);
  return value;
}

interface Inputs {
  readonly row: SurfaceRow;
  readonly sourceDir: string;
  readonly outDir: string;
  readonly agentsDir: string | null;
  readonly generated: readonly GeneratedFile[];
}

function readInputs(context: CommandContext): Inputs {
  const sourceDir = required(
    context,
    "source",
    "It names the directory whose subdirectories are the skills to mirror.",
  );
  const outDir = required(context, "out", "It names the directory the mirror is written into.");
  const surfaceName = required(
    context,
    "surface",
    `It selects a row of the surface table. Known: ${surfaceNames().join(", ")}.`,
  );
  const row = findSurface(surfaceName);
  if (row === undefined) {
    throw new VerbUsageError(
      `--surface '${surfaceName}' is not in the table. Known: ${surfaceNames().join(", ")}. A surface nen has not read the documentation for cannot be guessed at: adding one is a row in src/surface/rules.ts carrying the page every field was read from.`,
    );
  }

  // BEFORE ANYTHING IS READ. A caller who pointed --out at a path inside
  // --source must hear about THAT, not about the eleventh skill's frontmatter
  // -- and on the second run the mirror would be inside the set being mirrored,
  // so the generator would start generating from its own output.
  const sourceAbs = resolve(sourceDir);
  const outAbs = resolve(outDir);
  if (isContained(sourceAbs, outAbs)) {
    throw new VerbUsageError(
      `--out '${outDir}' resolves inside --source '${sourceDir}' (${outAbs}). The mirror would become part of the source it is generated from, and the next run would mirror its own output. Point --out at a directory outside the source tree.`,
    );
  }

  const agentsFlag = context.args.values["agents"];
  if (agentsFlag !== undefined && agentsFlag.trim() === "") {
    throw new VerbUsageError(
      "--agents was given an empty value. Omit it entirely to mirror the skills and no personas.",
    );
  }
  const agents: readonly SourceAgent[] = agentsFlag === undefined ? [] : readSourceAgents(agentsFlag);

  return {
    row,
    sourceDir,
    outDir,
    agentsDir: agentsFlag ?? null,
    generated: generateSurfaceMirror({
      row,
      skills: readSourceSkills(sourceDir),
      agents,
      invocationPrefix: context.args.values["invocation-prefix"] ?? null,
    }),
  };
}

const listOr = (items: readonly string[]): string => (items.length === 0 ? "(none)" : items.join(", "));

function runGenerate(context: CommandContext): number {
  const inputs = readInputs(context);
  const dryRun = context.args.booleans.has("dry-run");
  const result = writeSurfaceMirror(inputs.outDir, inputs.generated, inputs.row, dryRun);
  context.io.err(`nen: note: ${inputs.row.surface}: ${inputs.row.caveat}.`);
  emit(
    context.io,
    context.json,
    {
      contract: GENERATE_CONTRACT,
      surface: inputs.row.surface,
      skillsPath: inputs.row.skillsPath,
      out: inputs.outDir,
      dryRun,
      written: result.written,
      unchanged: result.unchanged,
      deleted: result.deleted,
    },
    [
      `surface: ${inputs.row.surface} (${inputs.row.skillsPath})`,
      `out: ${inputs.outDir}${dryRun ? " (--dry-run: nothing written)" : ""}`,
      `written: ${listOr(result.written)}`,
      `unchanged: ${listOr(result.unchanged)}`,
      `deleted (orphaned): ${listOr(result.deleted)}`,
    ],
  );
  return 0;
}

function runCheck(context: CommandContext): number {
  const inputs = readInputs(context);
  const report = checkSurfaceMirror(inputs.outDir, inputs.generated, inputs.row);
  emit(context.io, context.json, { contract: CHECK_CONTRACT, ...report }, [
    `surface: ${report.surface}`,
    `ok: ${report.ok.length}`,
    `missing: ${listOr(report.missing)}`,
    `extra: ${listOr(report.extra)}`,
    `stale: ${listOr(report.stale)}`,
    `hand-edited: ${listOr(report.handEdited)}`,
  ]);
  return mirrorReportOk(report) ? 0 : 1;
}

export const surfaceCommand: Command = {
  name: "surface",
  summary: "Mirror a skills directory into another agent surface's layout, and check it for drift.",
  usage: USAGE,
  flags: { values: FAMILY_VALUES, booleans: FAMILY_BOOLEANS },
  run(context: CommandContext): number {
    requireSubcommand("surface", context.args, ["mirror"]);
    const sub = context.args.positionals[2];
    if (sub !== "generate" && sub !== "check") {
      throw new VerbUsageError(
        `unknown 'surface mirror' subcommand '${sub ?? "(none)"}'. Try 'generate' or 'check'.`,
      );
    }
    refuseForeignFlags(sub, context);
    try {
      return sub === "generate" ? runGenerate(context) : runCheck(context);
    } catch (error) {
      // A refusal the mirror raised is a refusal the CALLER made -- a source
      // with no skills, a required key the surface documents and the file has
      // not got, a destination somebody wrote by hand. It exits 2 like every
      // other "you asked for something that cannot be done", carrying its own
      // message whole (../cli/command.ts's parseCallerToken makes the same
      // trade for the same reason).
      if (error instanceof SurfaceMirrorError) throw new VerbUsageError(error.message);
      throw error;
    }
  },
};
