// src/surface/command.ts -- `nen surface mirror generate|check`: one skills
// directory, rendered into the layout and frontmatter another agent surface
// documents for itself.
//
// WHY IT IS A FAMILY AND NOT A FLAG ON `canon mirror`. The two mirrors answer
// the same QUESTION ("is the committed copy still an image of its source?") and
// share none of its INPUTS: canon substitutes `{{TOKEN}}` bindings from a values
// file and pins a ref; this one filters frontmatter keys per a surface's own
// documentation and rewrites invocation spellings. Folding them together would
// have produced a verb with two disjoint halves of required flags and a
// `--kind` to say which -- the shape ../cli/registry.ts's header exists to keep
// out of this binary.
//
// NEITHER VERB DECIDES ANYTHING. `generate` writes the mirror the table
// describes; `check` says how the committed one differs. Neither opens a pull
// request, neither installs anything into a surface's real skills directory, and
// neither judges whether a skill is any good for the surface it is being
// mirrored into. `check --installed` reads a copy somebody else installed and
// says whether it is still the source's image; it copies nothing back.

import { resolve } from "node:path";
import {
  emit,
  requireSubcommand,
  VerbUsageError,
  type Command,
  type CommandContext,
} from "../cli/command.js";
import { isContained } from "../repo/contain.js";
import {
  checkSurfaceMirror,
  generateSurfaceMirrorReport,
  mirrorReportOk,
  readSourceAgentsReport,
  readSourceSkills,
  SurfaceMirrorError,
  writeSurfaceMirror,
  type GenerateReport,
} from "./mirror.js";
import {
  isVersion,
  readHooksManifest,
  readModelMaps,
  readPermissions,
  readPluginManifest,
  readRules,
  SurfacePackError,
} from "./packs.js";
import { findSurface, SURFACES, surfaceNames, type SurfaceRow } from "./rules.js";
import { CAPABILITIES, capabilityNames, findCapabilities, renderCapabilities } from "./capabilities.js";

export const GENERATE_CONTRACT = "nen.surface.mirror.generate/v0.1";
export const CHECK_CONTRACT = "nen.surface.mirror.check/v0.1";
export const CHECK_INSTALLED_CONTRACT = "nen.surface.mirror.check-installed/v0.1";

/**
 * The surface whose aliases the SOURCE personas carry in `model:` when the
 * caller does not say. A canonical skills tree is read directly by one
 * surface, so its personas name that surface's models; the one this binary's
 * first consumer writes for is this one. Caller data all the same -- the flag
 * overrides it, and the value is only ever a key of the caller's own
 * `models` matrix.
 */
export const DEFAULT_SOURCE_SURFACE = "claude-code";

const SURFACE_LIST = SURFACES.map((row): string => `    ${row.surface.padEnd(12)} ${row.summary}`).join("\n");

const USAGE = `nen surface -- mirror a skills directory into another agent surface's own layout,
               and say what each surface can do.

usage:
  nen surface capabilities --surface <name> [--json]
  nen surface capabilities [--json]                 (every surface)
  nen surface mirror generate --source <dir> --surface <name> --out <dir>
                              [--agents <dir>] [--invocation-prefix <prefix>]
                              [--hooks <hooks.json>] [--hooks-root <expr>]
                              [--manifest <plugin.json>] [--models <workflow.json>]
                              [--source-surface <name>]
                              [--rules <file.md>] [--permissions <permissions.json>]
                              [--stamp <version>] [--dry-run] [--json]
  nen surface mirror check    --source <dir> --surface <name> --out <dir>
                              [the same inputs] [--stamp <version>] [--json]
  nen surface mirror check    --source <dir> --surface <name> --installed <dir>
                              [the same inputs] [--stamp <version>] [--json]

capabilities: the primitives a RUNNING SESSION on a surface has -- which
tool asks a human a multiple-choice question, which raises a subagent, which
hook events exist and the JSON key a PreToolUse hook answers with, whether a
subagent can be isolated in a worktree, whether a page can be published,
whether the surface notifies on its own, where a permission allowlist lives
and in what shape, the per-agent model key, the rules file and its limit, and
the description budget -- as data with a citation per row (zheref/nen #216,
#227), so a skill branches on a fact rather than on prose that was true when
it was written. Surfaces: ${capabilityNames().join(", ")}. An unknown one
exits 2 naming those.

mirror: for every '<name>/SKILL.md' under --source, writes '<out>/<name>/SKILL.md': the
body verbatim, the frontmatter reduced to the keys the surface documents, and --
where the surface documents an explicit invocation spelling -- every
'<prefix><name>' mention rewritten into it. Every generated file carries a
one-line 'GENERATED by nen surface mirror' marker as its first MARKDOWN line
(after the frontmatter fence, because the surface needs that fence first); a
TOML file carries it as a '# ' first line and a JSON file as a top-level
'$generated' key.

surfaces (src/surface/rules.ts -- one row each, with the page every fact was
read from):
${SURFACE_LIST}

  --source <dir>              REQUIRED. The directory whose SUBDIRECTORIES are
                              the skills. One with no <name>/SKILL.md in it is
                              refused rather than mirrored as empty.
  --surface <name>            REQUIRED. A row in the table above; anything else
                              is refused, naming the ones that exist.
  --out <dir>                 REQUIRED (unless --installed). Where the mirror
                              goes. A path INSIDE --source is refused: the
                              mirror would become part of the source it is
                              generated from.
  --agents <dir>              A directory of '*.md' persona files. Where the
                              surface documents per-persona files they are
                              written one apiece; where it documents none, every
                              persona becomes a section of the one prose
                              document the row names. A '_'-prefixed file is a
                              shared include, not a persona: skipped and named.
  --invocation-prefix <p>     The SOURCE's own invocation namespace (e.g.
                              'myplugin:'). Caller data, never a literal in this
                              binary. Without it nothing is rewritten.
  --hooks <hooks.json>        A Claude-Code-shaped hook manifest (Stop,
                              PreToolUse, SessionStart groups, each with
                              commands). Emitted at the row's hook file with the
                              events renamed to the surface's own; a surface
                              with no hooks reports 'hooks: not supported'.
  --hooks-root <expr>         What '\${CLAUDE_PLUGIN_ROOT}' in a --hooks command
                              becomes, double-quoted inside the command when
                              it has whitespace or expands; a command still
                              carrying a '$' (or a quoted root) is wrapped as
                              sh -c 'exec <command>' -- so a surface with no
                              shell expands it. Refused on the verbatim row,
                              and for a root or command carrying '"', a
                              backtick, '$(', a backslash or a newline. The
                              scripts a command names
                              as <root>/hooks/<file> are copied beside the
                              manifest to <out>/hooks/<file> (mode 755, marker
                              on line 2) on every non-verbatim row.
  --manifest <plugin.json>    A Claude plugin manifest; a row that documents a
                              plugin manifest of its own (antigravity:
                              plugin.json with name, version, description)
                              gets one with those keys; the others report
                              'manifest: not supported'.
  --models <workflow.json>    A nen/workflow.json whose 'models.<surface>' maps
                              tiers to aliases. A persona's 'model:' is read as
                              a tier, else as an alias of --source-surface's
                              row (read back to its one tier), and rewritten to
                              the target alias; 'inherit' is carried where the
                              surface documents it and dropped (named)
                              elsewhere; anything else is refused by pointer.
                              Codex also gets config.toml.fragment
                              (default_subagent_model = the 'fast' alias) and
                              one agents/<name>.toml per persona.
  --source-surface <name>     The surface the SOURCE personas were written for
                              (default claude-code): their 'model:' values are
                              that surface's aliases, read back through
                              'models.<name>'.
  --rules <file.md>           A rules document, emitted at the row's rules
                              directory as '<stem><ext>' with the surface's own
                              frontmatter; over the surface's documented
                              character limit it is REFUSED, never truncated.
  --permissions <file.json>   A permissions source ({ allow: [{exe, args}],
                              deny: [...], surfaces: { <name>: { allow, deny
                              } } }), emitted as the surface's own pack --
                              Bash(exe args) for claude-code, Shell(exe:args)
                              for cursor, a config.toml with writable_roots =
                              [] for codex (the installer fills it; the report
                              says writableRootsPlaceholder). A surfaces.<name>
                              block is transcribed verbatim after the shared
                              rows for that surface only. A surface with no
                              allowlist file reports 'permissions: not
                              supported'; a '(' or ')' in a row is refused.
  --stamp <version>           MAJOR.MINOR.PATCH of the source, written into the
                              marker. 'check --stamp' then reports a file
                              carrying no stamp or another one as STALE.
  --installed <dir>           check only, in place of --out: an installed copy
                              (a plugin cache directory, a consumer's .codex/,
                              .cursor/, .agents/) compared against a fresh
                              in-memory generation under the check-installed
                              contract.
  --dry-run                   generate only. Reports exactly what it would write
                              and writes nothing.

'check' regenerates in memory and diffs the committed mirror, writing nothing at
all. A file is MISSING (generated, not in --out), EXTRA (in --out's mirror
universe, with no source), STALE (marked, but for a different surface -- or,
with --stamp, for no stamp or a different one), HAND_EDITED (marked for this
surface, bytes differ from a fresh generation -- or a hook script's mode is
not the 755 it was written with) or OK. Only '<name>/SKILL.md',
the row's own persona files and the row's hook, rules, permission and fragment
files are in that universe; anything else --out holds is neither checked nor
deleted.

Exit codes: 0 a completed generate, or a check with no drift; 1 a check with any
drift; 2 a missing or unknown flag, an --out inside --source, a --source with no
SKILL.md, a skill missing a key the surface requires, a rules file over the
surface's limit, a tier --models does not declare, or a destination that exists
and carries no marker (this verb never overwrites a hand-written file).`;

const INPUT_VALUES = ["source", "agents", "surface", "source-surface", "invocation-prefix", "hooks", "hooks-root", "manifest", "models", "rules", "permissions", "stamp"];

const SUBCOMMAND_FLAGS: Readonly<Record<string, { values: readonly string[]; booleans: readonly string[] }>> = {
  generate: { values: [...INPUT_VALUES, "out"], booleans: ["dry-run"] },
  check: { values: [...INPUT_VALUES, "out", "installed"], booleans: [] },
};

const FAMILY_VALUES = [
  ...new Set(Object.values(SUBCOMMAND_FLAGS).flatMap((spec): readonly string[] => spec.values)),
].sort();
const FAMILY_BOOLEANS = [
  ...new Set(Object.values(SUBCOMMAND_FLAGS).flatMap((spec): readonly string[] => spec.booleans)),
].sort();

/** Refused rather than ignored -- ../report/command.ts's argument, verbatim. */
function refuseForeignFlags(subcommand: string, context: CommandContext): void {
  const spec = SUBCOMMAND_FLAGS[subcommand];
  /* c8 ignore next -- the subcommand was already checked against the same keys */
  if (spec === undefined) return;
  const known = new Set([...FAMILY_VALUES, ...FAMILY_BOOLEANS]);
  const mine = new Set([...spec.values, ...spec.booleans]);
  const foreign = [...Object.keys(context.args.values), ...context.args.booleans].filter(
    (flag): boolean => known.has(flag) && !mine.has(flag),
  );
  if (foreign.length === 0) return;
  throw new VerbUsageError(
    `--${[...new Set(foreign)].sort().join(", --")} ${foreign.length === 1 ? "is" : "are"} not read by 'surface mirror ${subcommand}'. A flag accepted and ignored is worse than one refused: the ignored thing is the instruction you gave.`,
  );
}

function required(context: CommandContext, flag: string, why: string): string {
  const value = context.args.values[flag];
  if (value === undefined || value.trim() === "") throw new VerbUsageError(`--${flag} is required. ${why}`);
  return value;
}

/** An optional path flag: absent, or present and non-empty. An empty value is refused, never read as absent. */
function optionalPath(context: CommandContext, flag: string): string | null {
  const value = context.args.values[flag];
  if (value === undefined) return null;
  if (value.trim() === "") {
    throw new VerbUsageError(`--${flag} was given an empty value. Omit it entirely, or name the file.`);
  }
  return value;
}

interface Inputs {
  readonly row: SurfaceRow;
  readonly sourceDir: string;
  /** `--out`, or `--installed` when that was given instead. */
  readonly outDir: string;
  readonly installed: boolean;
  readonly agentsDir: string | null;
  readonly stamp: string | null;
  readonly skippedAgents: readonly string[];
  readonly report: GenerateReport;
}

function readInputs(context: CommandContext, allowInstalled: boolean): Inputs {
  const sourceDir = required(
    context,
    "source",
    "It names the directory whose subdirectories are the skills to mirror.",
  );
  const installedFlag = allowInstalled ? optionalPath(context, "installed") : null;
  const outFlag = context.args.values["out"];
  if (installedFlag !== null && outFlag !== undefined) {
    throw new VerbUsageError(
      "--installed replaces --out: the installed copy IS the directory being checked. Give one or the other.",
    );
  }
  const outDir =
    installedFlag ?? required(context, "out", "It names the directory the mirror is written into.");
  const surfaceName = required(
    context,
    "surface",
    `It selects a row of the surface table. Known: ${surfaceNames().join(", ")}.`,
  );
  const row = findSurface(surfaceName);
  if (row === undefined) {
    throw new VerbUsageError(
      `--surface '${surfaceName}' is not in the table. Known: ${surfaceNames().join(", ")}. A surface nen has not read the documentation for cannot be guessed at: adding one is a row in src/surface/rules.ts carrying the page every field was read from.`,
    );
  }

  // BEFORE ANYTHING IS READ. A caller who pointed --out at a path inside
  // --source must hear about THAT, not about the eleventh skill's frontmatter
  // -- and on the second run the mirror would be inside the set being mirrored,
  // so the generator would start generating from its own output.
  const sourceAbs = resolve(sourceDir);
  const outAbs = resolve(outDir);
  if (installedFlag === null && isContained(sourceAbs, outAbs)) {
    throw new VerbUsageError(
      `--out '${outDir}' resolves inside --source '${sourceDir}' (${outAbs}). The mirror would become part of the source it is generated from, and the next run would mirror its own output. Point --out at a directory outside the source tree.`,
    );
  }

  const stamp = context.args.values["stamp"] ?? null;
  if (stamp !== null && !isVersion(stamp)) {
    throw new VerbUsageError(
      `--stamp '${stamp}' is not a MAJOR.MINOR.PATCH version. The stamp is compared as a version by 'check --stamp', so it has to be one.`,
    );
  }

  const agentsFlag = context.args.values["agents"];
  if (agentsFlag !== undefined && agentsFlag.trim() === "") {
    throw new VerbUsageError(
      "--agents was given an empty value. Omit it entirely to mirror the skills and no personas.",
    );
  }
  const agents = agentsFlag === undefined ? { agents: [], skipped: [] } : readSourceAgentsReport(agentsFlag);
  const hooksPath = optionalPath(context, "hooks");
  const modelsPath = optionalPath(context, "models");
  const sourceSurface = context.args.values["source-surface"] ?? DEFAULT_SOURCE_SURFACE;
  if (sourceSurface.trim() === "") {
    throw new VerbUsageError("--source-surface was given an empty value. Omit it for the default, or name the surface the source personas were written for.");
  }
  const rulesPath = optionalPath(context, "rules");
  const permissionsPath = optionalPath(context, "permissions");
  const manifestPath = optionalPath(context, "manifest");
  const hooksRoot = context.args.values["hooks-root"] ?? null;
  if (hooksRoot !== null) {
    if (hooksRoot.trim() === "") {
      throw new VerbUsageError("--hooks-root was given an empty value. Omit it to carry the commands verbatim.");
    }
    if (hooksPath === null) {
      throw new VerbUsageError("--hooks-root rebases the commands of a --hooks manifest, and no --hooks was given.");
    }
    if (row.verbatim) {
      throw new VerbUsageError(
        `--hooks-root is refused on '${row.surface}': its manifest is carried byte for byte, and a rebased command would be a change to the file this row promises not to change.`,
      );
    }
  }

  return {
    row,
    sourceDir,
    outDir,
    installed: installedFlag !== null,
    agentsDir: agentsFlag ?? null,
    stamp,
    skippedAgents: agents.skipped,
    report: generateSurfaceMirrorReport({
      row,
      skills: readSourceSkills(sourceDir),
      agents: agents.agents,
      invocationPrefix: context.args.values["invocation-prefix"] ?? null,
      stamp,
      hooks: hooksPath === null ? null : readHooksManifest(hooksPath),
      hooksRoot,
      manifest: manifestPath === null ? null : readPluginManifest(manifestPath),
      models: modelsPath === null ? null : readModelMaps(modelsPath, row.surface, sourceSurface),
      rules: rulesPath === null ? null : readRules(rulesPath),
      permissions: permissionsPath === null ? null : readPermissions(permissionsPath),
    }),
  };
}

const listOr = (items: readonly string[]): string => (items.length === 0 ? "(none)" : items.join(", "));

function runGenerate(context: CommandContext): number {
  const inputs = readInputs(context, false);
  const dryRun = context.args.booleans.has("dry-run");
  const report = inputs.report;
  const result = writeSurfaceMirror(inputs.outDir, report.files, inputs.row, dryRun);
  context.io.err(`nen: note: ${inputs.row.surface}: ${inputs.row.caveat}.`);
  const rulesLine =
    typeof report.rules === "string"
      ? report.rules
      : `${report.rules.path} (${report.rules.chars} chars${report.rules.limit === null ? "" : ` of ${report.rules.limit}`})`;
  emit(
    context.io,
    context.json,
    {
      contract: GENERATE_CONTRACT,
      surface: inputs.row.surface,
      skillsPath: inputs.row.skillsPath,
      out: inputs.outDir,
      dryRun,
      written: result.written,
      unchanged: result.unchanged,
      deleted: result.deleted,
      stamp: inputs.stamp,
      skippedAgents: inputs.skippedAgents,
      truncated: report.truncated,
      droppedInherit: report.droppedInherit,
      undocumentedAliases: report.undocumentedAliases,
      hooks: report.hooks,
      rules: report.rules,
      permissions: report.permissions,
      manifest: report.manifest,
      notes: report.notes,
      permissionSurfaceRows: report.permissionSurfaceRows,
      writableRootsPlaceholder: report.writableRootsPlaceholder,
    },
    [
      `surface: ${inputs.row.surface} (${inputs.row.skillsPath})`,
      `out: ${inputs.outDir}${dryRun ? " (--dry-run: nothing written)" : ""}`,
      ...(inputs.stamp === null ? [] : [`stamp: ${inputs.stamp}`]),
      `written: ${listOr(result.written)}`,
      `unchanged: ${listOr(result.unchanged)}`,
      `deleted (orphaned): ${listOr(result.deleted)}`,
      ...(inputs.skippedAgents.length === 0
        ? []
        : [`skipped (shared includes, not personas): ${inputs.skippedAgents.join(", ")}`]),
      ...(report.truncated.length === 0
        ? []
        : [`truncated (description over the ${inputs.row.descriptionBudget ?? 0}-char budget; summary: added): ${report.truncated.join(", ")}`]),
      ...(report.droppedInherit.length === 0
        ? []
        : [`model: inherit dropped (the surface documents no inherit): ${report.droppedInherit.join(", ")}`]),
      ...(report.undocumentedAliases.length === 0
        ? []
        : [`model alias outside the surface's documented set (${(inputs.row.modelAliases ?? []).join("|")}): ${report.undocumentedAliases.join(", ")}`]),
      `hooks: ${report.hooks}`,
      `rules: ${rulesLine}`,
      `permissions: ${report.permissions}${report.permissionSurfaceRows > 0 ? ` (+${report.permissionSurfaceRows} surface rows)` : ""}`,
      `manifest: ${report.manifest}`,
      ...report.notes.map((note): string => `note: ${note}`),
    ],
  );
  return 0;
}

function runCheck(context: CommandContext): number {
  const inputs = readInputs(context, true);
  const report = checkSurfaceMirror(inputs.outDir, inputs.report.files, inputs.row, inputs.stamp);
  const contract = inputs.installed ? CHECK_INSTALLED_CONTRACT : CHECK_CONTRACT;
  emit(
    context.io,
    context.json,
    inputs.installed
      ? { contract, ...report, installed: inputs.outDir, stamp: inputs.stamp }
      : { contract, ...report, stamp: inputs.stamp },
    [
      `surface: ${report.surface}`,
      ...(inputs.installed ? [`installed: ${inputs.outDir}`] : []),
      ...(inputs.stamp === null ? [] : [`stamp: ${inputs.stamp}`]),
      `ok: ${report.ok.length}`,
      `missing: ${listOr(report.missing)}`,
      `extra: ${listOr(report.extra)}`,
      `stale: ${listOr(report.stale)}`,
      `hand-edited: ${listOr(report.handEdited)}`,
    ],
  );
  return mirrorReportOk(report) ? 0 : 1;
}

export const surfaceCommand: Command = {
  name: "surface",
  subcommands: ["mirror", "capabilities"],
  summary: "Mirror a skills directory into another agent surface's layout, and check it for drift.",
  usage: USAGE,
  flags: { values: FAMILY_VALUES, booleans: FAMILY_BOOLEANS },
  run(context: CommandContext): number {
    const family = requireSubcommand("surface", context.args, ["mirror", "capabilities"]);
    if (family === "capabilities") return runCapabilities(context);
    const sub = context.args.positionals[2];
    if (sub !== "generate" && sub !== "check") {
      throw new VerbUsageError(
        `unknown 'surface mirror' subcommand '${sub ?? "(none)"}'. Try 'generate' or 'check'.`,
      );
    }
    refuseForeignFlags(sub, context);
    try {
      return sub === "generate" ? runGenerate(context) : runCheck(context);
    } catch (error) {
      // A refusal the mirror raised is a refusal the CALLER made -- a source
      // with no skills, a required key the surface documents and the file has
      // not got, a destination somebody wrote by hand. It exits 2 like every
      // other "you asked for something that cannot be done", carrying its own
      // message whole (../cli/command.ts's parseCallerToken makes the same
      // trade for the same reason).
      if (error instanceof SurfaceMirrorError || error instanceof SurfacePackError) {
        throw new VerbUsageError(error.message);
      }
      throw error;
    }
  },
};

function runCapabilities(context: CommandContext): number {
  const name = context.args.values["surface"] ?? null;
  if (name === null) {
    const lines = CAPABILITIES.flatMap((row): string[] => [...renderCapabilities(row), ""]);
    emit(context.io, context.json, { contract: "nen.surface.capabilities/v0.1", surfaces: CAPABILITIES }, lines);
    return 0;
  }
  const row = findCapabilities(name);
  if (row === undefined) {
    throw new VerbUsageError(`unknown surface '${name}'. This build knows: ${capabilityNames().join(", ")}.`);
  }
  emit(context.io, context.json, { contract: "nen.surface.capabilities/v0.1", ...row }, renderCapabilities(row));
  return 0;
}
