// src/surface/mirror.ts -- generate a per-surface skills mirror from one source
// directory, and diff a committed mirror against a fresh generation.
//
// IT IS ../canon/mirror.ts's SHAPE, DELIBERATELY, down to the four drift
// classes. That module mirrors canon rule files into a product repository and
// this one mirrors skill files into another agent surface's layout, and the
// operational question is identical both times: is the committed copy still an
// exact image of its source? So the answers are the same four words -- MISSING
// (the source has it, the mirror does not), EXTRA (the mirror has it, the source
// does not), STALE (the mirror was generated, but for something other than what
// this run asked for), HAND_EDITED (the mirror carries the marker and its bytes
// are not a fresh generation's) -- and `check` regenerates in memory and writes
// nothing, which is what makes it the half CI can run.
//
// WHAT PLAYS THE ROLE OF canon's `--ref`. Two facts the generated marker
// carries, and drift in either means "generated, but not for this": the
// SURFACE, always, and the STAMP when `--stamp <version>` was given (zheref/
// nen#227). A mirror generated for one surface and checked against another is
// exactly canon's stale case; so is a mirror stamped from an older source than
// the one `check --stamp` names -- it was really generated, it is really out of
// date, and calling it hand-edited would send its maintainer looking for an
// edit nobody made. Without `--stamp` the stamp is ignored both ways: a file
// is compared with its own stamp masked, so a stamped mirror checked by a
// caller who did not ask about stamps is not drift.
//
// WHERE THE MARKER SITS, AND WHY IT IS NOT LINE 1. Every surface here loads a
// SKILL.md by reading YAML frontmatter delimited by `---` AT THE START OF THE
// FILE. An HTML comment above that fence means the file has no frontmatter at
// all, so a generator that put its own marker on line 1 would emit a file the
// surface silently refuses to load -- a "do not edit" banner bought at the price
// of the document. So the marker is the first line of the MARKDOWN: line 1 of a
// file with no frontmatter (the appendix document), and the first line after the
// closing fence otherwise. It is one deterministic position either way --
// ./frontmatter.ts's `splitDocument(text).body`'s first line -- which is what
// `check` reads it back out of, and it is anchored there for the same reason
// ../canon/mirror.ts anchors its own at the first line: a marker-shaped line
// further down (a quoted example, a nested fence) must never be mistaken for the
// real one. A TOML file carries it as its `# ` first line and a JSON file as a
// top-level `"$generated"` key (./packs.ts says why), and `readMarker` reads
// all three.
//
// IT NEVER OVERWRITES A FILE IT DID NOT WRITE. `writeSurfaceMirror` refuses --
// before writing anything at all -- any destination that exists and does NOT
// carry the marker. The case that makes this non-optional is the appendix one:
// `AGENTS.md` is a file people write by hand, at the root of their project, and
// a generator that clobbered it because `--out` was pointed one directory too
// high would destroy work with no diff to recover it from. A file that DOES
// carry the marker is overwritten freely, hand edits included -- that is the
// self-healing the mirror exists for. The same guard is why `config.toml` is
// never a destination: the model default lands in a marked FRAGMENT beside it.

import { chmodSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, rmSync, rmdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { hasValue, inlineValue, renderFrontmatter, splitDocument, type FrontmatterEntry } from "./frontmatter.js";
import {
  compareVersions,
  isVersion,
  readHookScripts,
  renderHooks,
  renderHookScript,
  renderPermissions,
  renderPluginManifest,
  renderRules,
  rewriteModel,
  tomlMultiline,
  tomlString,
  type HooksManifest,
  type ModelMaps,
  type PermissionsSource,
  type PluginManifest,
  type RulesSource,
} from "./packs.js";
import { invocationFor, skillPath, type SurfaceRow } from "./rules.js";

/** A refusal this module raises; the command layer turns it into exit 2. */
export class SurfaceMirrorError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SurfaceMirrorError";
  }
}

export const MARKER_PREFIX = "<!-- GENERATED by nen surface mirror (surface: ";
const TEXT_PREFIX = "GENERATED by nen surface mirror (surface: ";
const TEXT_SUFFIX = ") -- do not edit; edit the source and regenerate";

/**
 * The marker's text, without any comment syntax: `GENERATED by nen surface
 * mirror (surface: codex[, stamp: 0.43.0]) -- do not edit; ...`.
 *
 * ASCII ONLY, and `--` rather than an em dash: this line is written into
 * somebody else's repository, read back by this same verb on a Windows checkout,
 * and compared byte for byte. A character whose encoding can vary is a drift
 * class nobody asked for.
 */
export function markerText(surface: string, stamp: string | null = null): string {
  return `${TEXT_PREFIX}${surface}${stamp === null ? "" : `, stamp: ${stamp}`}${TEXT_SUFFIX}`;
}

/** The marker as a markdown line. */
export function markerFor(surface: string, stamp: string | null = null): string {
  return `<!-- ${markerText(surface, stamp)} -->`;
}

export function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const TEXT_RE = new RegExp(
  `^${escapeRegExp(TEXT_PREFIX)}(?<surface>[^,)]*)(?:, stamp: (?<stamp>[^)]*))?${escapeRegExp(TEXT_SUFFIX)}$`,
);
const STAMP_RE = new RegExp(`(${escapeRegExp(TEXT_PREFIX)}[^,)]*), stamp: [^)]*\\)`, "g");

export interface Marker {
  readonly surface: string;
  /** The version the mirror was generated from, or null for the unstamped form. */
  readonly stamp: string | null;
}

function parseMarkerText(text: string): Marker | null {
  const groups = TEXT_RE.exec(text.replace(/\r$/, ""))?.groups;
  if (groups === undefined) return null;
  return { surface: groups["surface"] ?? "", stamp: groups["stamp"] ?? null };
}

/**
 * The marker a committed file carries, or null when it carries none (a
 * hand-written file, or one whose banner was deleted). Markdown: the first
 * markdown line as an HTML comment. TOML: a `# ` first line. JSON: the
 * top-level `$generated` key.
 */
export function readMarker(text: string): Marker | null {
  const first = splitDocument(text).body.split("\n")[0] ?? "";
  const comment = /^<!-- (.*) -->\r?$/.exec(first);
  if (comment?.[1] !== undefined) return parseMarkerText(comment[1]);
  if (first.startsWith("# ")) return parseMarkerText(first.slice(2));
  // A script: the shebang owns line 1, so the marker is the `# ` line under it.
  if (first.startsWith("#!")) {
    const second = text.split("\n")[1] ?? "";
    if (second.startsWith("# ")) return parseMarkerText(second.slice(2));
  }
  if (text.trimStart().startsWith("{")) {
    try {
      const parsed = JSON.parse(text) as unknown;
      if (typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)) {
        const value = (parsed as Record<string, unknown>)["$generated"];
        if (typeof value === "string") return parseMarkerText(value);
      }
    } catch {
      return null;
    }
  }
  return null;
}

/** `text` with every marker's `, stamp: <v>` removed, so two generations differing only in stamp compare equal. */
export function withoutStamp(text: string): string {
  return text.replace(STAMP_RE, "$1)");
}

// ---------------------------------------------------------------------------
// Reading the source
// ---------------------------------------------------------------------------

export interface SourceSkill {
  /** The directory name, which is also the skill's name for invocation purposes. */
  readonly name: string;
  /** `<name>/SKILL.md`, for a message that names what was read. */
  readonly relative: string;
  readonly text: string;
}

export interface SourceAgent {
  /** The filename without its extension. */
  readonly stem: string;
  /** Frontmatter `name` where the file states one, else the stem. */
  readonly name: string;
  readonly relative: string;
  readonly text: string;
}

function directoryEntries(dir: string, what: string, flag: string): readonly string[] {
  try {
    return readdirSync(dir).sort();
  } catch (error) {
    throw new SurfaceMirrorError(
      `--${flag} '${dir}' could not be read as ${what}: ${(error as NodeJS.ErrnoException).code ?? String(error)}.`,
    );
  }
}

/**
 * Every `<name>/SKILL.md` under `sourceDir`, sorted by name.
 *
 * A source with none is a REFUSAL rather than an empty mirror. An empty
 * generation is indistinguishable from a correct one that mirrors nothing, and
 * `writeSurfaceMirror` would then delete every file in `--out` as an orphan --
 * so the one plausible typo (`--source` pointed at the parent of the skills
 * directory) would quietly empty the mirror instead of saying so.
 */
export function readSourceSkills(sourceDir: string): readonly SourceSkill[] {
  const skills: SourceSkill[] = [];
  for (const entry of directoryEntries(sourceDir, "a skills directory", "source")) {
    const file = join(sourceDir, entry, "SKILL.md");
    if (!existsSync(file) || !statSync(file).isFile()) continue;
    skills.push({ name: entry, relative: `${entry}/SKILL.md`, text: readFileSync(file, "utf8") });
  }
  if (skills.length === 0) {
    throw new SurfaceMirrorError(
      `--source '${sourceDir}' holds no <name>/SKILL.md. A mirror generated from nothing is indistinguishable from a correct empty one, and writing it would delete the whole mirror as orphaned -- point --source at the directory whose SUBDIRECTORIES are the skills.`,
    );
  }
  return skills;
}

export interface SourceAgents {
  readonly agents: readonly SourceAgent[];
  /**
   * `_`-prefixed `*.md` files: shared INCLUDES a persona pulls in by path
   * ("read `agents/_review-preamble.md` first"), never personas (zheref/nen
   * #223 -- mirrored as personas they became subagents nobody defined).
   * Carried as INCLUDES (Nobunaga S11): a mirrored persona that cites a file
   * the mirror does not hold is a persona pointing at nothing.
   */
  readonly includes: readonly SourceAgent[];
  /** Anything else under `--agents` that was set aside: a `*.md` that is not a regular file. */
  readonly skipped: readonly string[];
}

/** Every `*.md` directly under `agentsDir`, sorted, `_`-prefixed files as includes. An empty directory is allowed. */
export function readSourceAgentsReport(agentsDir: string): SourceAgents {
  const agents: SourceAgent[] = [];
  const includes: SourceAgent[] = [];
  const skipped: string[] = [];
  for (const entry of directoryEntries(agentsDir, "an agents directory", "agents")) {
    if (!entry.endsWith(".md")) continue;
    const file = join(agentsDir, entry);
    if (!statSync(file).isFile()) {
      skipped.push(entry);
      continue;
    }
    const text = readFileSync(file, "utf8");
    const stem = entry.slice(0, -".md".length);
    const named = splitDocument(text).entries.find((candidate): boolean => candidate.key === "name");
    const inline = named === undefined ? "" : inlineValue(named);
    (entry.startsWith("_") ? includes : agents).push({ stem, name: inline === "" ? stem : inline, relative: entry, text });
  }
  return { agents, includes, skipped };
}

export function readSourceAgents(agentsDir: string): readonly SourceAgent[] {
  return readSourceAgentsReport(agentsDir).agents;
}

// ---------------------------------------------------------------------------
// Generating
// ---------------------------------------------------------------------------

export interface GeneratedFile {
  /** Path relative to `--out`, always `/`-separated. */
  readonly path: string;
  readonly content: string;
  /** A file mode to set on write (a hook script's 0o755), or absent for the default. */
  readonly mode?: number;
  /**
   * True for a hook script whose interpreter does not read `#` comments, so
   * it carries no marker (N12): the manifest that names it does. Such a file
   * is compared by bytes in `check`, is outside the orphan universe, and is
   * not clobber-guarded -- the manifest beside it is, and the path is one
   * the manifest names as a script the plugin ships.
   */
  readonly markerless?: true;
}

export interface GenerateOptions {
  readonly row: SurfaceRow;
  readonly skills: readonly SourceSkill[];
  readonly agents: readonly SourceAgent[];
  /** The `_`-prefixed shared includes beside the personas (`readSourceAgentsReport().includes`), carried as includes. */
  readonly includes?: readonly SourceAgent[];
  /**
   * The source's own invocation prefix (`--invocation-prefix`), or null. Caller
   * data: a source repository's namespace is its own name for itself, never a
   * literal this binary carries (§3).
   */
  readonly invocationPrefix: string | null;
  /** `--stamp`, or null for the unstamped marker. */
  readonly stamp?: string | null;
  /** `--hooks`, read; null when not given. */
  readonly hooks?: HooksManifest | null;
  /** `--hooks-root`: what `${CLAUDE_PLUGIN_ROOT}` becomes in every command; null carries commands verbatim. */
  readonly hooksRoot?: string | null;
  /** `--manifest`, read; null when not given. */
  readonly manifest?: PluginManifest | null;
  /** `--rules`, read; null when not given. */
  readonly rules?: RulesSource | null;
  /** `--permissions`, read; null when not given. */
  readonly permissions?: PermissionsSource | null;
  /** `models.<surface>` and `models.<source-surface>` of `--models`, read; null when not given. */
  readonly models?: ModelMaps | null;
}

export interface GenerateReport {
  readonly files: readonly GeneratedFile[];
  /** Skills whose description exceeded the row's budget and gained a `summary:` key. */
  readonly truncated: readonly string[];
  /** Personas whose `model: inherit` was dropped because the surface documents no inherit. */
  readonly droppedInherit: readonly string[];
  /** Personas whose mapped alias is outside the surface's documented set, as `<persona>: <alias>`. */
  readonly undocumentedAliases: readonly string[];
  /** Personas written `model: inherit` on a `modelInheritOnly` row, as `<persona>: <tier> -> inherit`. */
  readonly modelMapped: readonly string[];
  /** `written`, `not supported` (the row has no manifest), or `none` (no --hooks). */
  readonly hooks: "written" | "not supported" | "none";
  readonly rules: { readonly path: string; readonly chars: number; readonly limit: number | null } | "not supported" | "none";
  readonly permissions: "written" | "not supported" | "none";
  /** Rows transcribed verbatim from the source's `surfaces.<surface>` block, after the shared ones. */
  readonly permissionSurfaceRows: number;
  /** True when the permission pack carries a `writable_roots = []` an installer has to fill (codex). */
  readonly writableRootsPlaceholder: boolean;
  /**
   * The sandbox's network line: absent (null) where the pack states no
   * sandbox; otherwise `network_access` as declared, or null when the source
   * declares none and the pack carries no such line (the surface's default).
   */
  readonly permissionSandbox: { readonly networkAccess: boolean | null } | null;
  readonly manifest: "written" | "not supported" | "none";
  /** Everything else worth a line: unmapped hook events, an appendix past the read limit, a long rules file. */
  readonly notes: readonly string[];
  /** The shared includes carried beside the personas, by source filename (`_shared.md`). */
  readonly includes: readonly string[];
}

/**
 * `<prefix><name>` rewritten to the surface's own spelling, everywhere it
 * appears -- INCLUDING names that are not in the mirrored set, because a skill
 * that points at a sibling points at it by the same prefix and a half-rewritten
 * document is worse than an unrewritten one.
 *
 * A `{name}` the surface has no spelling for is left exactly as written: this
 * verb never invents an invocation syntax for a surface whose documentation
 * states none.
 */
export function rewriteInvocations(text: string, row: SurfaceRow, prefix: string | null): string {
  if (prefix === null || prefix === "" || row.invocation === null) return text;
  const pattern = new RegExp(`(?<![A-Za-z0-9_-])${escapeRegExp(prefix)}([A-Za-z0-9][A-Za-z0-9_-]*)`, "g");
  return text.replace(pattern, (_whole, name: string): string => invocationFor(row, name) ?? _whole);
}

/** The whole `description:` value -- its own line plus every continuation -- as one space-joined string. */
export function descriptionText(entries: readonly FrontmatterEntry[]): string {
  const entry = entries.find((candidate): boolean => candidate.key === "description");
  if (entry === undefined) return "";
  return [inlineValue(entry), ...entry.lines.slice(1).map((line): string => line.trim())]
    .filter((part): boolean => part !== "")
    .join(" ")
    .replace(/\r/g, "");
}

/**
 * The first sentence of `text`, trimmed to `budget` characters. A sentence
 * ends at the first `.`, `!` or `?` followed by whitespace or the end; a
 * sentence longer than the budget is cut at the budget's last whitespace, or
 * hard at the budget when it has none.
 */
export function firstSentence(text: string, budget: number): string {
  const match = /^(.*?[.!?])(?:\s|$)/.exec(text);
  const sentence = (match?.[1] ?? text).trim();
  if (sentence.length <= budget) return sentence;
  const cut = sentence.slice(0, budget);
  const space = cut.lastIndexOf(" ");
  return (space > 0 ? cut.slice(0, space) : cut).trim();
}

function skillFile(options: GenerateOptions, skill: SourceSkill, truncated: string[]): GeneratedFile {
  const row = options.row;
  const document = splitDocument(skill.text);
  if (!document.hasFrontmatter) {
    throw new SurfaceMirrorError(
      `'${skill.relative}' has no '---' frontmatter block. Every surface in the table identifies a skill by its frontmatter, so a file without one cannot be adapted -- only copied, which is not what this verb promises.`,
    );
  }
  for (const key of row.skillRequired) {
    if (!hasValue(document.entries, key)) {
      throw new SurfaceMirrorError(
        `'${skill.relative}' has no '${key}' in its frontmatter, and '${row.surface}' documents it as required (${row.source}). Add it to the source rather than to the mirror.`,
      );
    }
  }
  const path = skillPath(row, skill.name);
  if (row.verbatim) return { path, content: skill.text };

  let entries: readonly FrontmatterEntry[] = document.entries;
  if (row.descriptionBudget !== null) {
    const description = descriptionText(entries);
    if (description.length > row.descriptionBudget && !entries.some((entry): boolean => entry.key === "summary")) {
      const summary: FrontmatterEntry = {
        key: "summary",
        lines: [`summary: ${firstSentence(description, row.descriptionBudget)}`],
      };
      const at = entries.findIndex((entry): boolean => entry.key === "description");
      entries = [...entries.slice(0, at + 1), summary, ...entries.slice(at + 1)];
      truncated.push(skill.name);
    }
  }
  const front = renderFrontmatter(entries, new Set(row.skillKeys));
  const content = `${front}${markerFor(row.surface, options.stamp ?? null)}\n${document.body}`;
  return { path, content: rewriteInvocations(content, row, options.invocationPrefix) };
}

interface AgentOutput {
  readonly files: readonly GeneratedFile[];
  readonly droppedInherit: readonly string[];
  readonly undocumentedAliases: readonly string[];
  readonly modelMapped: readonly string[];
  readonly notes: readonly string[];
}

function agentFiles(options: GenerateOptions): AgentOutput {
  const row = options.row;
  const rule = row.agents;
  const stamp = options.stamp ?? null;
  const models = options.models ?? null;
  const droppedInherit: string[] = [];
  const undocumentedAliases: string[] = [];
  const modelMapped: string[] = [];
  const notes: string[] = [];
  const includes = options.includes ?? [];
  if (options.agents.length === 0 && includes.length === 0) return { files: [], droppedInherit, undocumentedAliases, modelMapped, notes };

  /** `model:` through --models, for a persona whose entries the surface reads as frontmatter. */
  const mapped = (agent: SourceAgent, entries: readonly FrontmatterEntry[]): readonly FrontmatterEntry[] => {
    if (models === null || !row.agentModelMap) return entries;
    const result = rewriteModel(row, models, entries, agent.relative);
    if (result.droppedInherit) droppedInherit.push(agent.stem);
    if (result.undocumentedAlias !== null) undocumentedAliases.push(`${agent.stem}: ${result.undocumentedAlias}`);
    if (result.mappedToInherit !== null) modelMapped.push(`${agent.stem}: ${result.mappedToInherit} -> inherit`);
    return result.entries;
  };

  if (rule.kind === "files") {
    const files = options.agents.map((agent): GeneratedFile => {
      const path = `${rule.dir}/${agent.stem}${rule.extension}`;
      if (row.verbatim) return { path, content: agent.text };
      const document = splitDocument(agent.text);
      for (const key of rule.required) {
        if (!hasValue(document.entries, key)) {
          throw new SurfaceMirrorError(
            `'${agent.relative}' has no '${key}' in its frontmatter, and '${row.surface}' documents it as required for a persona (${row.agentSource}). Add it to the source rather than to the mirror.`,
          );
        }
      }
      const front = renderFrontmatter(mapped(agent, document.entries), new Set(rule.keys));
      // A `files` surface reads a persona AS frontmatter-bearing markdown, so a
      // mirror with an EMPTY block cannot be one (zheref/nen#149, review).
      // Emitting it anyway would write a persona file with no frontmatter at
      // all -- nothing for the surface to route on, and the marker sitting on
      // line 1 of a document whose shape that surface's own page describes
      // differently. That the row REQUIRES no key is a statement about which
      // keys must be filled in; it is not a statement that the block itself is
      // optional. Both ways of arriving at an empty block are refused -- no
      // fence in the source, or a fence holding only keys this surface does not
      // read -- because the file that would be written is the same file.
      if (front === "") {
        const because = document.hasFrontmatter
          ? `its frontmatter holds none of the keys this surface reads (${rule.keys.join(", ")})`
          : "it has no '---' frontmatter block at all";
        throw new SurfaceMirrorError(
          `'${agent.relative}' would mirror to a persona file with no frontmatter, because ${because}. '${row.surface}' reads a persona as frontmatter-bearing markdown (${row.agentSource}), so there would be nothing for it to route on. Fix the source rather than the mirror.`,
        );
      }
      const content = `${front}${markerFor(row.surface, stamp)}\n${document.body}`;
      return { path, content: rewriteInvocations(content, row, options.invocationPrefix) };
    });
    // The includes, beside the personas (S11): frontmatter reduced the same
    // way, marker after it, body verbatim -- and NO required-key check, no
    // empty-frontmatter refusal and no model rewriting, because an include
    // is not a persona: nothing routes on it, and a persona reads it by path.
    for (const include of includes) {
      const path = `${rule.dir}/${include.stem}${rule.extension}`;
      if (row.verbatim) {
        files.push({ path, content: include.text });
        continue;
      }
      const document = splitDocument(include.text);
      const front = renderFrontmatter(document.entries, new Set(rule.keys));
      const content = `${front}${markerFor(row.surface, stamp)}\n${document.body}`;
      files.push({ path, content: rewriteInvocations(content, row, options.invocationPrefix) });
    }
    return { files, droppedInherit, undocumentedAliases, modelMapped, notes };
  }

  // The appendix: ONE document, a heading per persona, the persona's prose
  // underneath. Its frontmatter is dropped whole rather than filtered -- the
  // file this lands in has no frontmatter concept at all, and a stray `---`
  // fence in the middle of a prose document renders as a horizontal rule.
  const hashes = "#".repeat(rule.headingLevel);
  const section = (agent: SourceAgent, heading: string): string => {
    const body = splitDocument(agent.text).body.replace(/^\n+/, "").replace(/\s+$/, "");
    return `${hashes} ${heading}\n\n${body}\n`;
  };
  // The includes follow the personas as `## _<stem>` sections (S11): a
  // persona's "read _review-preamble first" then lands on a heading in the
  // same document rather than on a file the surface never received.
  const sections = [
    ...options.agents.map((agent): string => section(agent, agent.name)),
    ...includes.map((include): string => section(include, include.stem)),
  ];
  const appendix = rewriteInvocations(
    `${markerFor(row.surface, stamp)}\n\n${sections.join("\n")}`,
    row,
    options.invocationPrefix,
  );
  const files: GeneratedFile[] = [{ path: rule.file, content: appendix }];
  if (rule.warnBytes !== null) {
    const bytes = Buffer.byteLength(appendix, "utf8");
    if (bytes > rule.warnBytes) {
      notes.push(
        `${rule.file} is ${bytes} bytes, past the ${rule.warnBytes}-byte read limit the surface documents (${row.agentSource}); a persona past the cut-off is one the surface never meets`,
      );
    }
  }

  // The machine-readable persona files beside the appendix, only when a
  // model map was given: `model` is the one field the prose cannot carry,
  // and it is the reason the files exist.
  if (row.agentToml !== null && models !== null) {
    for (const agent of options.agents) {
      const document = splitDocument(agent.text);
      const result = rewriteModel(row, models, document.entries, agent.relative);
      if (result.droppedInherit) droppedInherit.push(agent.stem);
      if (result.undocumentedAlias !== null) undocumentedAliases.push(`${agent.stem}: ${result.undocumentedAlias}`);
      const description = descriptionText(document.entries);
      if (description === "") {
        throw new SurfaceMirrorError(
          `'${agent.relative}' has no 'description' in its frontmatter, and '${row.surface}' documents it as required for ${row.agentToml.documentedPath} (${row.agentToml.source}). Add it to the source rather than to the mirror.`,
        );
      }
      const body = rewriteInvocations(document.body.replace(/^\n+/, "").replace(/\s+$/, ""), row, options.invocationPrefix);
      const lines = [
        `# ${markerText(row.surface, stamp)}`,
        `name = ${tomlString(agent.name)}`,
        `description = ${tomlString(rewriteInvocations(description, row, options.invocationPrefix))}`,
        ...(result.alias === null || result.alias === "inherit" ? [] : [`model = ${tomlString(result.alias)}`]),
        `developer_instructions = ${tomlMultiline(body)}`,
        "",
      ];
      files.push({ path: `${row.agentToml.dir}/${agent.stem}.toml`, content: lines.join("\n") });
    }
  }
  return { files, droppedInherit, undocumentedAliases, modelMapped, notes };
}

/** Every file this run would write, sorted by path, with what the report needs to say about them. */
export function generateSurfaceMirrorReport(options: GenerateOptions): GenerateReport {
  const row = options.row;
  const stamp = options.stamp ?? null;
  const truncated: string[] = [];
  const notes: string[] = [];
  const files: GeneratedFile[] = options.skills.map((skill): GeneratedFile => skillFile(options, skill, truncated));
  const agents = agentFiles(options);
  files.push(...agents.files);
  notes.push(...agents.notes);

  let hooks: GenerateReport["hooks"] = "none";
  if (options.hooks !== undefined && options.hooks !== null) {
    if (row.hooks === null) hooks = "not supported";
    else {
      hooks = "written";
      const marker = markerText(row.surface, stamp);
      files.push({ path: row.hooks.file, content: renderHooks(row.hooks, options.hooks, marker, options.hooksRoot ?? null) });
      // The scripts travel with the manifest: a mirror installed as a plugin
      // root has to resolve `<root>/hooks/<file>` to a file it ships.
      if (row.hooks.scriptsDir !== null) {
        for (const script of readHookScripts(options.hooks)) {
          const rendered = renderHookScript(script, marker);
          const path = `${row.hooks.scriptsDir}/${script.name}`;
          files.push({ path, content: rendered.content, mode: 0o755, ...(rendered.markerless ? { markerless: true } : {}) });
          if (rendered.markerless) {
            notes.push(`${path} carries no marker: its interpreter does not read # comments, and the manifest beside it carries the marker`);
          }
        }
      }
      if (options.hooks.unmapped.length > 0) {
        notes.push(
          `--hooks carries ${options.hooks.unmapped.join(", ")}, which no row maps; only Stop, PreToolUse and SessionStart are carried`,
        );
      }
    }
  }

  let rules: GenerateReport["rules"] = "none";
  if (options.rules !== undefined && options.rules !== null) {
    if (row.rules === null) rules = "not supported";
    else {
      const rendered = renderRules(row.rules, options.rules, markerText(row.surface, stamp));
      files.push({ path: rendered.path, content: rendered.content });
      rules = { path: rendered.path, chars: rendered.chars, limit: row.rules.limit };
      if (row.rules.lineGuidance !== null && rendered.lines > row.rules.lineGuidance) {
        notes.push(
          `${rendered.path} is ${rendered.lines} lines; the surface advises under ${row.rules.lineGuidance} (${row.rules.source})`,
        );
      }
    }
  }

  let permissions: GenerateReport["permissions"] = "none";
  let permissionSurfaceRows = 0;
  let writableRootsPlaceholder = false;
  let permissionSandbox: GenerateReport["permissionSandbox"] = null;
  if (options.permissions !== undefined && options.permissions !== null) {
    if (row.permissions === null) permissions = "not supported";
    else {
      permissions = "written";
      const rendered = renderPermissions(row.permissions, options.permissions, markerText(row.surface, stamp), row.surface);
      files.push({ path: row.permissions.file, content: rendered.content });
      permissionSurfaceRows = rendered.surfaceRows;
      writableRootsPlaceholder = rendered.writableRootsPlaceholder;
      permissionSandbox = rendered.sandbox;
      if (writableRootsPlaceholder) {
        notes.push(`${row.permissions.file} carries writable_roots = [] for the installer to fill (writableRootsPlaceholder)`);
      }
    }
  }

  let manifest: GenerateReport["manifest"] = "none";
  if (options.manifest !== undefined && options.manifest !== null) {
    if (row.pluginManifest === null) manifest = "not supported";
    else {
      manifest = "written";
      files.push({
        path: row.pluginManifest.file,
        content: renderPluginManifest(row.pluginManifest, options.manifest, markerText(row.surface, stamp)),
      });
    }
  }

  if (options.models !== undefined && options.models !== null && row.subagentModelFragment !== null) {
    const fragment = row.subagentModelFragment;
    const alias = options.models.target[fragment.tier];
    if (alias === undefined) {
      throw new SurfaceMirrorError(
        `--models declares no 'models.${row.surface}.${fragment.tier}', which ${fragment.file} names as the default subagent model (${fragment.source}). Add the tier or omit --models.`,
      );
    }
    files.push({
      path: fragment.file,
      content: `# ${markerText(row.surface, stamp)}\n# Merge into ${fragment.documentedPath}; this fragment is never the live file.\n[agents]\ndefault_subagent_model = ${tomlString(alias)}\n`,
    });
  }

  return {
    files: files.sort((left, right): number => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0)),
    truncated: truncated.sort(),
    droppedInherit: [...new Set(agents.droppedInherit)].sort(),
    undocumentedAliases: [...new Set(agents.undocumentedAliases)].sort(),
    modelMapped: [...new Set(agents.modelMapped)].sort(),
    hooks,
    rules,
    permissions,
    permissionSurfaceRows,
    writableRootsPlaceholder,
    permissionSandbox,
    manifest,
    notes,
    includes: (options.includes ?? []).map((include): string => include.relative),
  };
}

/** Every file this run would write, sorted by path. */
export function generateSurfaceMirror(options: GenerateOptions): readonly GeneratedFile[] {
  return generateSurfaceMirrorReport(options).files;
}

// ---------------------------------------------------------------------------
// The mirror's own filename universe
// ---------------------------------------------------------------------------

/**
 * The files under `outDir` this verb considers ITS OWN -- the only ones it will
 * ever delete, and the only ones a check calls EXTRA.
 *
 * TWO CONDITIONS, AND THE SECOND IS THE MARKER (zheref/nen#149, review). A file
 * is ours only if it sits at one of the row's own locations AND carries a
 * generated marker. The first cut had only the location test, which made
 * `writeSurfaceMirror` inconsistent with itself: it REFUSED to overwrite an
 * unmarked `<name>/SKILL.md` and then happily DELETED one whose source had gone
 * -- the same file, the same hand, destroyed instead of protected because it
 * was orphaned rather than shadowed. "This verb never touches a file it did not
 * write" has to hold for the delete path too, or it is not a property.
 *
 * The gate is deliberately "carries A marker", not "carries THIS surface's": a
 * file generated for another surface and now sourceless is still this
 * generator's output, and is the case `check` reports as EXTRA and `generate`
 * removes. And `check` and `generate` read the SAME list, so what one calls
 * extra is exactly what the other deletes -- an `extra` a regenerate could not
 * clear would be drift nobody can fix.
 *
 * The row's OTHER locations are in the universe on the same terms: its hook
 * manifest, its rules directory's files, its permission pack, its model
 * fragment, its persona TOML files. A VERBATIM row writes no marker, so for it
 * the location test is the whole test: a plugin's own tree has no hand-written
 * files to tell apart from generated ones, because none of them is generated.
 *
 * Anything else a repository keeps in the mirror directory (a README, a
 * reference file beside a SKILL.md, an unrelated subdirectory, a SKILL.md
 * somebody wrote by hand) is outside the universe and is never touched, which
 * is ../canon/mirror.ts's rule and the reason its own docstring gives for
 * having one.
 */
export function universeFiles(outDir: string, row: SurfaceRow): readonly string[] {
  const ours = (relative: string): boolean => {
    const path = join(outDir, ...relative.split("/"));
    if (!existsSync(path) || !statSync(path).isFile()) return false;
    return row.verbatim || readMarker(readFileSync(path, "utf8")) !== null;
  };
  const isDir = (path: string): boolean => existsSync(path) && statSync(path).isDirectory();
  // A `_`-prefixed file is a shared include on the source side (zheref/nen
  // #223) and is CARRIED as one (S11), so it is inside the universe on every
  // row like any persona file: generated, checked, and deleted as an orphan
  // when its source goes.
  const filesIn = (dir: string, extension: string): readonly string[] => {
    const absolute = join(outDir, ...dir.split("/"));
    if (!isDir(absolute)) return [];
    return readdirSync(absolute)
      .sort()
      .filter((entry): boolean => entry.endsWith(extension))
      .map((entry): string => `${dir}/${entry}`);
  };

  if (!existsSync(outDir)) return [];
  const found: string[] = [];
  const skillsRoot = row.skillsDir === "" ? outDir : join(outDir, ...row.skillsDir.split("/"));
  if (isDir(skillsRoot)) {
    for (const entry of readdirSync(skillsRoot).sort()) {
      if (!isDir(join(skillsRoot, entry))) continue;
      const relative = skillPath(row, entry);
      if (ours(relative)) found.push(relative);
    }
  }
  const candidates: string[] = [];
  const rule = row.agents;
  if (rule.kind === "files") candidates.push(...filesIn(rule.dir, rule.extension));
  else candidates.push(rule.file);
  if (row.agentToml !== null) candidates.push(...filesIn(row.agentToml.dir, ".toml"));
  if (row.hooks !== null) {
    candidates.push(row.hooks.file);
    if (row.hooks.scriptsDir !== null) candidates.push(...filesIn(row.hooks.scriptsDir, ""));
  }
  if (row.pluginManifest !== null) candidates.push(row.pluginManifest.file);
  if (row.rules !== null) candidates.push(...filesIn(row.rules.dir, row.rules.extension));
  if (row.permissions !== null) candidates.push(row.permissions.file);
  if (row.subagentModelFragment !== null) candidates.push(row.subagentModelFragment.file);
  for (const candidate of candidates) if (ours(candidate)) found.push(candidate);
  return [...new Set(found)].sort();
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

/** True when `path` is a symbolic link (dangling or not); false when nothing is there. */
function isSymlink(path: string): boolean {
  try {
    return lstatSync(path).isSymbolicLink();
  } catch {
    return false;
  }
}

/** The permission bits of `path`. */
function modeOf(path: string): number {
  return statSync(path).mode & 0o777;
}

export interface WriteResult {
  readonly written: readonly string[];
  readonly unchanged: readonly string[];
  readonly deleted: readonly string[];
}

/**
 * Write the generation into `outDir`, touching only what changed and deleting
 * the orphans -- or, with `dryRun`, compute exactly the same three lists and
 * write nothing.
 *
 * THE CLOBBER GUARD RUNS FIRST, over every destination, before the first byte is
 * written. A guard applied file by file would leave the mirror half-written when
 * the third file turned out to be somebody's own, and "it refused, but only
 * after overwriting two of your files" is not a refusal.
 */
export function writeSurfaceMirror(
  outDir: string,
  generated: readonly GeneratedFile[],
  row: SurfaceRow,
  dryRun = false,
): WriteResult {
  if (row.verbatim) {
    throw new SurfaceMirrorError(
      `'${row.surface}' is the verbatim row: its generation is the source itself, and it writes no marker to tell a destination it owns from one it does not. There is nothing to generate; use 'check' (or 'check --installed') to compare a copy against the source.`,
    );
  }
  const guarded: string[] = [];
  const linked: string[] = [];
  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (!existsSync(path) && !isSymlink(path)) continue;
    // A destination that is a symlink is refused before anything is written
    // (Feitan S4): writeFileSync follows it, and the file it would overwrite
    // is wherever the link points -- not a file this verb generated.
    if (isSymlink(path)) {
      linked.push(file.path);
      continue;
    }
    if (file.markerless === true) continue;
    if (readMarker(readFileSync(path, "utf8")) === null) guarded.push(file.path);
  }
  if (linked.length > 0) {
    throw new SurfaceMirrorError(
      `refusing to write through ${linked.length === 1 ? "a symbolic link" : "symbolic links"} in '${outDir}': ${linked.join(", ")}. A write there lands wherever the link points, which is not a file this verb generated. Replace the link with a file, or move it aside.`,
    );
  }
  if (guarded.length > 0) {
    throw new SurfaceMirrorError(
      `refusing to overwrite ${guarded.length === 1 ? "a file" : "files"} in '${outDir}' that ${guarded.length === 1 ? "was" : "were"} not generated by this verb: ${guarded.join(", ")}. ${guarded.length === 1 ? "It carries" : "They carry"} no '${MARKER_PREFIX}...' line, so ${guarded.length === 1 ? "it was" : "they were"} written by hand. Point --out at a directory this mirror owns, or move the file aside first.`,
    );
  }

  const written: string[] = [];
  const unchanged: string[] = [];
  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (existsSync(path) && readFileSync(path, "utf8") === file.content) {
      // Unchanged BYTES; the mode is still applied when the file declares one
      // (Nobunaga N6), because a script somebody chmod'ed to 0644 is a hook
      // the surface cannot run, and `check` calls that hand-edited.
      if (file.mode !== undefined && modeOf(path) !== file.mode) {
        if (!dryRun) chmodSync(path, file.mode);
        written.push(file.path);
        continue;
      }
      unchanged.push(file.path);
      continue;
    }
    written.push(file.path);
    if (dryRun) continue;
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, file.content, "utf8");
    if (file.mode !== undefined) chmodSync(path, file.mode);
  }

  const keep = new Set(generated.map((file): string => file.path));
  const deleted = universeFiles(outDir, row).filter((path): boolean => !keep.has(path));
  if (!dryRun) {
    for (const path of deleted) {
      const absolute = join(outDir, ...path.split("/"));
      rmSync(absolute);
      // The skill DIRECTORY goes too, but only when removing the file emptied
      // it: a `<name>/` still holding a reference file or a script is a
      // directory whose other contents are none of this verb's business.
      const parent = join(absolute, "..");
      try {
        if (readdirSync(parent).length === 0) rmdirSync(parent);
      } catch {
        /* c8 ignore next -- the parent is gone, or is outDir itself; either way there is nothing to tidy */
      }
    }
  }

  return { written: written.sort(), unchanged: unchanged.sort(), deleted: deleted.sort() };
}

// ---------------------------------------------------------------------------
// Checking
// ---------------------------------------------------------------------------

export interface MirrorReport {
  readonly surface: string;
  readonly ok: readonly string[];
  readonly missing: readonly string[];
  readonly extra: readonly string[];
  readonly stale: readonly string[];
  readonly handEdited: readonly string[];
}

/**
 * The committed mirror against a fresh generation. With `stamp`, a file whose
 * marker carries no stamp or a different one is STALE (older is the case that
 * matters; newer is not this source's either); without it, stamps are masked
 * on both sides and never a drift class.
 */
export function checkSurfaceMirror(
  outDir: string,
  generated: readonly GeneratedFile[],
  row: SurfaceRow,
  stamp: string | null = null,
): MirrorReport {
  const ok: string[] = [];
  const missing: string[] = [];
  const stale: string[] = [];
  const handEdited: string[] = [];

  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (!existsSync(path) || !statSync(path).isFile()) {
      missing.push(file.path);
      continue;
    }
    const existing = readFileSync(path, "utf8");
    if (row.verbatim || file.markerless === true) {
      (existing === file.content ? ok : handEdited).push(file.path);
      continue;
    }
    const marker = readMarker(existing);
    if (marker === null) handEdited.push(file.path);
    else if (marker.surface !== row.surface) stale.push(file.path);
    // A stamp that is not a version is STALE, not an error (N14): the file was
    // generated by something whose stamp this build cannot read, which is the
    // same fact as "not this source's" -- and a check that exited 2 over it
    // could never report the file it was asked about.
    else if (stamp !== null && (marker.stamp === null || !isVersion(marker.stamp) || compareVersions(marker.stamp, stamp) !== 0)) stale.push(file.path);
    else if (withoutStamp(existing) !== withoutStamp(file.content)) handEdited.push(file.path);
    // The same bytes under a different mode is a hand edit too (N6): a hook
    // script at 0644 is one the surface cannot run.
    else if (file.mode !== undefined && modeOf(path) !== file.mode) handEdited.push(file.path);
    else ok.push(file.path);
  }

  const keep = new Set(generated.map((file): string => file.path));
  const extra = universeFiles(outDir, row).filter((path): boolean => !keep.has(path));

  return {
    surface: row.surface,
    ok: ok.sort(),
    missing: missing.sort(),
    extra: extra.sort(),
    stale: stale.sort(),
    handEdited: handEdited.sort(),
  };
}

export function mirrorReportOk(report: MirrorReport): boolean {
  return (
    report.missing.length === 0 &&
    report.extra.length === 0 &&
    report.stale.length === 0 &&
    report.handEdited.length === 0
  );
}
