// src/surface/mirror.ts -- generate a per-surface skills mirror from one source
// directory, and diff a committed mirror against a fresh generation.
//
// IT IS ../canon/mirror.ts's SHAPE, DELIBERATELY, down to the four drift
// classes. That module mirrors canon rule files into a product repository and
// this one mirrors skill files into another agent surface's layout, and the
// operational question is identical both times: is the committed copy still an
// exact image of its source? So the answers are the same four words -- MISSING
// (the source has it, the mirror does not), EXTRA (the mirror has it, the source
// does not), STALE (the mirror was generated, but for something other than what
// this run asked for), HAND_EDITED (the mirror carries the marker and its bytes
// are not a fresh generation's) -- and `check` regenerates in memory and writes
// nothing, which is what makes it the half CI can run.
//
// WHAT PLAYS THE ROLE OF canon's `--ref`. There is no pinned upstream version
// here, so the fact the generated marker carries -- the fact whose drift means
// "generated, but not for this" -- is the SURFACE. A mirror generated for one
// surface and checked against another is exactly canon's stale case: it was
// really generated, it is really out of date, and calling it hand-edited would
// send its maintainer looking for an edit nobody made.
//
// WHERE THE MARKER SITS, AND WHY IT IS NOT LINE 1. Every surface here loads a
// SKILL.md by reading YAML frontmatter delimited by `---` AT THE START OF THE
// FILE. An HTML comment above that fence means the file has no frontmatter at
// all, so a generator that put its own marker on line 1 would emit a file the
// surface silently refuses to load -- a "do not edit" banner bought at the price
// of the document. So the marker is the first line of the MARKDOWN: line 1 of a
// file with no frontmatter (the appendix document), and the first line after the
// closing fence otherwise. It is one deterministic position either way --
// ./frontmatter.ts's `splitDocument(text).body`'s first line -- which is what
// `check` reads it back out of, and it is anchored there for the same reason
// ../canon/mirror.ts anchors its own at the first line: a marker-shaped line
// further down (a quoted example, a nested fence) must never be mistaken for the
// real one.
//
// IT NEVER OVERWRITES A FILE IT DID NOT WRITE. `writeSurfaceMirror` refuses --
// before writing anything at all -- any destination that exists and does NOT
// carry the marker. The case that makes this non-optional is the appendix one:
// `AGENTS.md` is a file people write by hand, at the root of their project, and
// a generator that clobbered it because `--out` was pointed one directory too
// high would destroy work with no diff to recover it from. A file that DOES
// carry the marker is overwritten freely, hand edits included -- that is the
// self-healing the mirror exists for.

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, rmdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { hasValue, renderFrontmatter, splitDocument } from "./frontmatter.js";
import { invocationFor, type SurfaceRow } from "./rules.js";

/** A refusal this module raises; the command layer turns it into exit 2. */
export class SurfaceMirrorError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "SurfaceMirrorError";
  }
}

export const MARKER_PREFIX = "<!-- GENERATED by nen surface mirror (surface: ";
const MARKER_SUFFIX = ") -- do not edit; edit the source and regenerate -->";

/**
 * The marker line for a surface.
 *
 * ASCII ONLY, and `--` rather than an em dash: this line is written into
 * somebody else's repository, read back by this same verb on a Windows checkout,
 * and compared byte for byte. A character whose encoding can vary is a drift
 * class nobody asked for.
 */
export function markerFor(surface: string): string {
  return `${MARKER_PREFIX}${surface}${MARKER_SUFFIX}`;
}

const MARKER_RE = new RegExp(
  `^${escapeRegExp(MARKER_PREFIX)}(?<surface>[^)]*)${escapeRegExp(MARKER_SUFFIX)}\\r?$`,
);

export function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * The surface a committed file says it was generated for, or null when its first
 * markdown line is not a marker at all (a hand-written file, or one whose banner
 * was deleted).
 */
export function readMarker(text: string): string | null {
  const first = splitDocument(text).body.split("\n")[0] ?? "";
  return MARKER_RE.exec(first)?.groups?.["surface"] ?? null;
}

// ---------------------------------------------------------------------------
// Reading the source
// ---------------------------------------------------------------------------

export interface SourceSkill {
  /** The directory name, which is also the skill's name for invocation purposes. */
  readonly name: string;
  /** `<name>/SKILL.md`, for a message that names what was read. */
  readonly relative: string;
  readonly text: string;
}

export interface SourceAgent {
  /** The filename without its extension. */
  readonly stem: string;
  /** Frontmatter `name` where the file states one, else the stem. */
  readonly name: string;
  readonly relative: string;
  readonly text: string;
}

function directoryEntries(dir: string, what: string, flag: string): readonly string[] {
  try {
    return readdirSync(dir).sort();
  } catch (error) {
    throw new SurfaceMirrorError(
      `--${flag} '${dir}' could not be read as ${what}: ${(error as NodeJS.ErrnoException).code ?? String(error)}.`,
    );
  }
}

/**
 * Every `<name>/SKILL.md` under `sourceDir`, sorted by name.
 *
 * A source with none is a REFUSAL rather than an empty mirror. An empty
 * generation is indistinguishable from a correct one that mirrors nothing, and
 * `writeSurfaceMirror` would then delete every file in `--out` as an orphan --
 * so the one plausible typo (`--source` pointed at the parent of the skills
 * directory) would quietly empty the mirror instead of saying so.
 */
export function readSourceSkills(sourceDir: string): readonly SourceSkill[] {
  const skills: SourceSkill[] = [];
  for (const entry of directoryEntries(sourceDir, "a skills directory", "source")) {
    const file = join(sourceDir, entry, "SKILL.md");
    if (!existsSync(file) || !statSync(file).isFile()) continue;
    skills.push({ name: entry, relative: `${entry}/SKILL.md`, text: readFileSync(file, "utf8") });
  }
  if (skills.length === 0) {
    throw new SurfaceMirrorError(
      `--source '${sourceDir}' holds no <name>/SKILL.md. A mirror generated from nothing is indistinguishable from a correct empty one, and writing it would delete the whole mirror as orphaned -- point --source at the directory whose SUBDIRECTORIES are the skills.`,
    );
  }
  return skills;
}

/** Every `*.md` directly under `agentsDir`, sorted. An empty directory is allowed. */
export function readSourceAgents(agentsDir: string): readonly SourceAgent[] {
  const agents: SourceAgent[] = [];
  for (const entry of directoryEntries(agentsDir, "an agents directory", "agents")) {
    if (!entry.endsWith(".md")) continue;
    const file = join(agentsDir, entry);
    if (!statSync(file).isFile()) continue;
    const text = readFileSync(file, "utf8");
    const stem = entry.slice(0, -".md".length);
    const named = splitDocument(text).entries.find((candidate): boolean => candidate.key === "name");
    const inline = named === undefined ? "" : (named.lines[0] ?? "").slice("name:".length).trim();
    agents.push({ stem, name: inline === "" ? stem : inline, relative: entry, text });
  }
  return agents;
}

// ---------------------------------------------------------------------------
// Generating
// ---------------------------------------------------------------------------

export interface GeneratedFile {
  /** Path relative to `--out`, always `/`-separated. */
  readonly path: string;
  readonly content: string;
}

export interface GenerateOptions {
  readonly row: SurfaceRow;
  readonly skills: readonly SourceSkill[];
  readonly agents: readonly SourceAgent[];
  /**
   * The source's own invocation prefix (`--invocation-prefix`), or null. Caller
   * data: a source repository's namespace is its own name for itself, never a
   * literal this binary carries (§3).
   */
  readonly invocationPrefix: string | null;
}

/**
 * `<prefix><name>` rewritten to the surface's own spelling, everywhere it
 * appears -- INCLUDING names that are not in the mirrored set, because a skill
 * that points at a sibling points at it by the same prefix and a half-rewritten
 * document is worse than an unrewritten one.
 *
 * A `{name}` the surface has no spelling for is left exactly as written: this
 * verb never invents an invocation syntax for a surface whose documentation
 * states none.
 */
export function rewriteInvocations(text: string, row: SurfaceRow, prefix: string | null): string {
  if (prefix === null || prefix === "" || row.invocation === null) return text;
  const pattern = new RegExp(`(?<![A-Za-z0-9_-])${escapeRegExp(prefix)}([A-Za-z0-9][A-Za-z0-9_-]*)`, "g");
  return text.replace(pattern, (_whole, name: string): string => invocationFor(row, name) ?? _whole);
}

function skillFile(options: GenerateOptions, skill: SourceSkill): GeneratedFile {
  const document = splitDocument(skill.text);
  if (!document.hasFrontmatter) {
    throw new SurfaceMirrorError(
      `'${skill.relative}' has no '---' frontmatter block. Every surface in the table identifies a skill by its frontmatter, so a file without one cannot be adapted -- only copied, which is not what this verb promises.`,
    );
  }
  for (const key of options.row.skillRequired) {
    if (!hasValue(document.entries, key)) {
      throw new SurfaceMirrorError(
        `'${skill.relative}' has no '${key}' in its frontmatter, and '${options.row.surface}' documents it as required (${options.row.source}). Add it to the source rather than to the mirror.`,
      );
    }
  }
  const front = renderFrontmatter(document.entries, new Set(options.row.skillKeys));
  const content = `${front}${markerFor(options.row.surface)}\n${document.body}`;
  return {
    path: `${skill.name}/SKILL.md`,
    content: rewriteInvocations(content, options.row, options.invocationPrefix),
  };
}

function agentFiles(options: GenerateOptions): readonly GeneratedFile[] {
  const rule = options.row.agents;
  if (options.agents.length === 0) return [];
  if (rule.kind === "files") {
    return options.agents.map((agent): GeneratedFile => {
      const document = splitDocument(agent.text);
      const front = renderFrontmatter(document.entries, new Set(rule.keys));
      const content = `${front}${markerFor(options.row.surface)}\n${document.body}`;
      return {
        path: `${rule.dir}/${agent.stem}${rule.extension}`,
        content: rewriteInvocations(content, options.row, options.invocationPrefix),
      };
    });
  }

  // The appendix: ONE document, a heading per persona, the persona's prose
  // underneath. Its frontmatter is dropped whole rather than filtered -- the
  // file this lands in has no frontmatter concept at all, and a stray `---`
  // fence in the middle of a prose document renders as a horizontal rule.
  const hashes = "#".repeat(rule.headingLevel);
  const sections = options.agents.map((agent): string => {
    const body = splitDocument(agent.text).body.replace(/^\n+/, "").replace(/\s+$/, "");
    return `${hashes} ${agent.name}\n\n${body}\n`;
  });
  const content = `${markerFor(options.row.surface)}\n\n${sections.join("\n")}`;
  return [{ path: rule.file, content: rewriteInvocations(content, options.row, options.invocationPrefix) }];
}

/** Every file this run would write, sorted by path. */
export function generateSurfaceMirror(options: GenerateOptions): readonly GeneratedFile[] {
  const files = [...options.skills.map((skill): GeneratedFile => skillFile(options, skill)), ...agentFiles(options)];
  return files.sort((left, right): number => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0));
}

// ---------------------------------------------------------------------------
// The mirror's own filename universe
// ---------------------------------------------------------------------------

/**
 * The files under `outDir` this verb considers ITS OWN -- the only ones it will
 * ever delete, and the only ones a check calls EXTRA.
 *
 * Anything else a repository keeps in the mirror directory (a README, a
 * reference file beside a SKILL.md, an unrelated subdirectory) is outside the
 * universe and is never touched, which is ../canon/mirror.ts's rule and the
 * reason its own docstring gives for having one.
 */
export function universeFiles(outDir: string, row: SurfaceRow): readonly string[] {
  if (!existsSync(outDir)) return [];
  const found: string[] = [];
  for (const entry of readdirSync(outDir).sort()) {
    const path = join(outDir, entry);
    if (!statSync(path).isDirectory()) continue;
    const skill = join(path, "SKILL.md");
    if (existsSync(skill) && statSync(skill).isFile()) found.push(`${entry}/SKILL.md`);
  }
  const rule = row.agents;
  if (rule.kind === "files") {
    const dir = join(outDir, rule.dir);
    if (existsSync(dir) && statSync(dir).isDirectory()) {
      for (const entry of readdirSync(dir).sort()) {
        if (entry.endsWith(rule.extension) && statSync(join(dir, entry)).isFile()) found.push(`${rule.dir}/${entry}`);
      }
    }
  } else {
    const file = join(outDir, rule.file);
    if (existsSync(file) && statSync(file).isFile()) found.push(rule.file);
  }
  return found.sort();
}

// ---------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------

export interface WriteResult {
  readonly written: readonly string[];
  readonly unchanged: readonly string[];
  readonly deleted: readonly string[];
}

/**
 * Write the generation into `outDir`, touching only what changed and deleting
 * the orphans -- or, with `dryRun`, compute exactly the same three lists and
 * write nothing.
 *
 * THE CLOBBER GUARD RUNS FIRST, over every destination, before the first byte is
 * written. A guard applied file by file would leave the mirror half-written when
 * the third file turned out to be somebody's own, and "it refused, but only
 * after overwriting two of your files" is not a refusal.
 */
export function writeSurfaceMirror(
  outDir: string,
  generated: readonly GeneratedFile[],
  row: SurfaceRow,
  dryRun = false,
): WriteResult {
  const guarded: string[] = [];
  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (!existsSync(path)) continue;
    if (readMarker(readFileSync(path, "utf8")) === null) guarded.push(file.path);
  }
  if (guarded.length > 0) {
    throw new SurfaceMirrorError(
      `refusing to overwrite ${guarded.length === 1 ? "a file" : "files"} in '${outDir}' that ${guarded.length === 1 ? "was" : "were"} not generated by this verb: ${guarded.join(", ")}. ${guarded.length === 1 ? "It carries" : "They carry"} no '${MARKER_PREFIX}...' line, so ${guarded.length === 1 ? "it was" : "they were"} written by hand. Point --out at a directory this mirror owns, or move the file aside first.`,
    );
  }

  const written: string[] = [];
  const unchanged: string[] = [];
  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (existsSync(path) && readFileSync(path, "utf8") === file.content) {
      unchanged.push(file.path);
      continue;
    }
    written.push(file.path);
    if (dryRun) continue;
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, file.content, "utf8");
  }

  const keep = new Set(generated.map((file): string => file.path));
  const deleted = universeFiles(outDir, row).filter((path): boolean => !keep.has(path));
  if (!dryRun) {
    for (const path of deleted) {
      const absolute = join(outDir, ...path.split("/"));
      rmSync(absolute);
      // The skill DIRECTORY goes too, but only when removing the file emptied
      // it: a `<name>/` still holding a reference file or a script is a
      // directory whose other contents are none of this verb's business.
      const parent = join(absolute, "..");
      try {
        if (readdirSync(parent).length === 0) rmdirSync(parent);
      } catch {
        /* c8 ignore next -- the parent is gone, or is outDir itself; either way there is nothing to tidy */
      }
    }
  }

  return { written: written.sort(), unchanged: unchanged.sort(), deleted: deleted.sort() };
}

// ---------------------------------------------------------------------------
// Checking
// ---------------------------------------------------------------------------

export interface MirrorReport {
  readonly surface: string;
  readonly ok: readonly string[];
  readonly missing: readonly string[];
  readonly extra: readonly string[];
  readonly stale: readonly string[];
  readonly handEdited: readonly string[];
}

export function checkSurfaceMirror(
  outDir: string,
  generated: readonly GeneratedFile[],
  row: SurfaceRow,
): MirrorReport {
  const ok: string[] = [];
  const missing: string[] = [];
  const stale: string[] = [];
  const handEdited: string[] = [];

  for (const file of generated) {
    const path = join(outDir, ...file.path.split("/"));
    if (!existsSync(path) || !statSync(path).isFile()) {
      missing.push(file.path);
      continue;
    }
    const existing = readFileSync(path, "utf8");
    const marker = readMarker(existing);
    if (marker === null) handEdited.push(file.path);
    else if (marker !== row.surface) stale.push(file.path);
    else if (existing !== file.content) handEdited.push(file.path);
    else ok.push(file.path);
  }

  const keep = new Set(generated.map((file): string => file.path));
  const extra = universeFiles(outDir, row).filter((path): boolean => !keep.has(path));

  return {
    surface: row.surface,
    ok: ok.sort(),
    missing: missing.sort(),
    extra: extra.sort(),
    stale: stale.sort(),
    handEdited: handEdited.sort(),
  };
}

export function mirrorReportOk(report: MirrorReport): boolean {
  return (
    report.missing.length === 0 &&
    report.extra.length === 0 &&
    report.stale.length === 0 &&
    report.handEdited.length === 0
  );
}
