// src/surface/packs.test.ts -- the readers and renderers for the files a
// mirror carries beside its skills (zheref/nen#227), over the fixtures under
// ./fixtures/packs and the rows in ./rules.ts.

import { describe, expect, it } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { splitDocument } from "./frontmatter.js";
import {
  compareVersions,
  isVersion,
  readHooksManifest,
  readModelMaps,
  resolveTier,
  readPermissions,
  readRules,
  renderHooks,
  renderPermissions,
  renderRules,
  rewriteModel,
  SurfacePackError,
  tomlMultiline,
  tomlString,
} from "./packs.js";
import { findSurface, type SurfaceRow } from "./rules.js";

const PACKS = join(process.cwd(), "src", "surface", "fixtures", "packs");
const MARKER = "GENERATED by nen surface mirror (surface: test) -- do not edit; edit the source and regenerate";

function row(name: string): SurfaceRow {
  const found = findSurface(name);
  if (found === undefined) throw new Error(`no row for ${name}`);
  return found;
}
function must<T>(value: T | null): T {
  if (value === null) throw new Error("expected a value");
  return value;
}
const tempFile = (name: string, content: string): string => {
  const dir = mkdtempSync(join(tmpdir(), "nen-packs-"));
  const path = join(dir, name);
  writeFileSync(path, content);
  return path;
};

describe("versions", () => {
  it("accepts MAJOR.MINOR.PATCH with an optional tail, and nothing shorter", () => {
    expect(isVersion("0.43.0")).toBe(true);
    expect(isVersion("1.2.3-rc.1")).toBe(true);
    expect(isVersion("0.43")).toBe(false);
    expect(isVersion("v0.43.0")).toBe(false);
  });

  it("compares numerically, component by component, ignoring the tail", () => {
    expect(compareVersions("0.43.0", "0.43.0")).toBe(0);
    expect(compareVersions("0.9.0", "0.10.0")).toBe(-1);
    expect(compareVersions("1.0.0", "0.99.99")).toBe(1);
    expect(compareVersions("0.43.0-rc.1", "0.43.0")).toBe(0);
    expect(() => compareVersions("x", "0.1.0")).toThrow(SurfacePackError);
  });
});

describe("hooks", () => {
  const manifest = readHooksManifest(join(PACKS, "hooks.json"));

  it("reads the three mapped events and names the ones no row maps", () => {
    expect(manifest.events.Stop).toHaveLength(1);
    expect(manifest.events.PreToolUse[0]?.matcher).toBe("Bash");
    expect(manifest.events.SessionStart[0]?.hooks[0]?.timeout).toBeNull();
    expect(manifest.unmapped).toEqual(["PostToolUse"]);
  });

  it("reads the same three events without the `hooks` wrapper", () => {
    const flat = readHooksManifest(tempFile("hooks.json", '{"Stop":[{"hooks":[{"type":"command","command":"x"}]}]}'));
    expect(flat.events.Stop[0]?.hooks[0]?.command).toBe("x");
  });

  it("refuses a malformed manifest by pointer", () => {
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":[{"hooks":[]}]}}'))).toThrow(/hooks\.Stop\[0\]\.hooks/);
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":[{"hooks":[{"command":""}]}]}}'))).toThrow(/command/);
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":"no"}}'))).toThrow(/not an array/);
    expect(() => readHooksManifest(tempFile("h.json", "not json"))).toThrow(/not JSON/);
    expect(() => readHooksManifest(join(PACKS, "nowhere.json"))).toThrow(/ENOENT/);
  });

  it("renders the grouped shape with the row's own event names and matcher", () => {
    const text = renderHooks(must(row("antigravity").hooks), manifest, MARKER);
    const doc = JSON.parse(text) as { $generated: string; hooks: Record<string, unknown[]> };
    expect(doc.$generated).toBe(MARKER);
    expect(Object.keys(doc.hooks)).toEqual(["Stop", "PreToolUse", "PreInvocation"]);
    expect(doc.hooks["PreToolUse"]?.[0]).toEqual({
      matcher: "run_command",
      hooks: [{ type: "command", command: "${PLUGIN_ROOT}/hooks/guard.sh", timeout: 10 }],
    });
    // A command with no timeout carries none, rather than an invented default.
    expect(doc.hooks["PreInvocation"]?.[0]).toEqual({ hooks: [{ type: "command", command: "sh -c 'echo warm'" }] });
  });

  it("renders cursor's flat version-1 shape: one command per entry, no matcher, no timeout", () => {
    const doc = JSON.parse(renderHooks(must(row("cursor").hooks), manifest, MARKER)) as {
      version: number;
      hooks: Record<string, { command: string }[]>;
    };
    expect(doc.version).toBe(1);
    expect(Object.keys(doc.hooks)).toEqual(["stop", "beforeShellExecution", "sessionStart"]);
    expect(doc.hooks["beforeShellExecution"]).toEqual([{ command: "${PLUGIN_ROOT}/hooks/guard.sh" }]);
  });

  it("renders the verbatim row's manifest byte for byte", () => {
    expect(renderHooks(must(row("claude-code").hooks), manifest, MARKER)).toBe(manifest.text);
  });
});

describe("permissions", () => {
  const source = readPermissions(join(PACKS, "permissions.json"));

  it("reads allow and deny, and refuses a malformed row by pointer", () => {
    expect(source.allow).toHaveLength(3);
    expect(source.deny[1]).toEqual({ exe: "sudo", args: "*" });
    expect(() => readPermissions(tempFile("p.json", '{"allow":[{"exe":""}]}'))).toThrow(/allow\[0\]\.exe/);
    expect(() => readPermissions(tempFile("p.json", '{"deny":{}}'))).toThrow(/deny is not an array/);
    expect(readPermissions(tempFile("p.json", "{}"))).toEqual({ allow: [], deny: [] });
  });

  it("renders Claude Code's settings shape as Bash(exe args) patterns", () => {
    const doc = JSON.parse(renderPermissions(must(row("claude-code").permissions), source, MARKER)) as {
      $generated: string;
      permissions: { allow: string[]; deny: string[] };
    };
    expect(doc.$generated).toBe(MARKER);
    expect(doc.permissions.allow).toEqual(["Bash(nen *)", "Bash(git fetch *)", "Bash(git write-tree)"]);
    expect(doc.permissions.deny).toEqual(["Bash(git push --force *)", "Bash(sudo *)"]);
  });

  it("renders Cursor's cli.json shape as Shell(...) patterns plus the workspace read/write grants", () => {
    const doc = JSON.parse(renderPermissions(must(row("cursor").permissions), source, MARKER)) as {
      permissions: { allow: string[]; deny: string[] };
    };
    expect(doc.permissions.allow.slice(-2)).toEqual(["Read(./**)", "Write(./**)"]);
    expect(doc.permissions.allow[0]).toBe("Shell(nen *)");
    expect(doc.permissions.deny).toEqual(["Shell(git push --force *)", "Shell(sudo *)"]);
  });

  it("renders Codex's config.toml with the marker on line 1 and the sandbox stated", () => {
    const text = renderPermissions(must(row("codex").permissions), source, MARKER);
    expect(text.split("\n")[0]).toBe(`# ${MARKER}`);
    expect(text).toContain('sandbox_mode = "workspace-write"');
    expect(text).toContain("[sandbox_workspace_write]");
  });
});

describe("rules", () => {
  const source = readRules(join(PACKS, "rules.md"));

  it("names the file after the source's stem, in the row's directory and extension", () => {
    const rendered = renderRules(must(row("antigravity").rules), source, MARKER);
    expect(rendered.path).toBe("rules/rules.md");
    expect(rendered.content.startsWith(`<!-- ${MARKER} -->\n# House rules`)).toBe(true);
    expect(rendered.chars).toBe(rendered.content.length);
  });

  it("prepends cursor's own frontmatter with the stem as the description", () => {
    const rendered = renderRules(must(row("cursor").rules), source, MARKER);
    expect(rendered.path).toBe("rules/rules.mdc");
    const doc = splitDocument(rendered.content);
    expect(doc.entries.map((entry): string => entry.lines.join("\n"))).toEqual(["description: rules", "alwaysApply: true"]);
    expect(doc.body.split("\n")[0]).toBe(`<!-- ${MARKER} -->`);
  });

  it("REFUSES a rendering over the documented limit, naming both numbers, and never truncates", () => {
    const long = { stem: "long", text: "x".repeat(12_000) };
    expect(() => renderRules(must(row("antigravity").rules), long, MARKER)).toThrow(/over the 12000-character limit/);
    // The same text is fine where the row documents no limit.
    expect(renderRules(must(row("cursor").rules), long, MARKER).chars).toBeGreaterThan(12_000);
  });

  it("refuses a --rules that cannot be read", () => {
    expect(() => readRules(join(PACKS, "nowhere.md"))).toThrow(/ENOENT/);
  });
});

describe("models", () => {
  const workflow = join(PACKS, "workflow.json");
  const maps = (surface: string, sourceSurface = "claude-code"): ReturnType<typeof readModelMaps> =>
    readModelMaps(workflow, surface, sourceSurface);

  it("reads models.<surface> and models.<source-surface>, and refuses a target the file does not declare", () => {
    expect(maps("codex").target["fast"]).toBe("gpt-5-mini");
    expect(maps("codex").source?.["deep"]).toBe("opus");
    expect(maps("codex", "nowhere").source).toBeNull();
    expect(maps("codex").known).toContain("antigravity");
    expect(() => maps("gemini-cli")).toThrow(/no 'models\.gemini-cli'.*claude-code, twins, codex, cursor, antigravity/);
    expect(() => readModelMaps(tempFile("w.json", '{"models":{"codex":{"fast":1}}}'), "codex", "x")).toThrow(/models\.codex\.fast/);
    expect(() => readModelMaps(tempFile("w.json", "[]"), "codex", "x")).toThrow(/not an object/);
  });

  it("resolves a tier name as itself, and a source alias to its one tier", () => {
    expect(resolveTier(maps("cursor"), "deep", "x.md")).toBe("deep");
    expect(resolveTier(maps("cursor"), "opus", "x.md")).toBe("deep");
    expect(resolveTier(maps("cursor"), "haiku", "x.md")).toBe("economy");
  });

  it("refuses an alias under two tiers, an unknown value, and a missing source row -- each by pointer", () => {
    expect(() => resolveTier(maps("cursor", "twins"), "big", "x.md")).toThrow(/'models\.twins' lists under 2 tiers \(frontier, deep\)/);
    expect(() => resolveTier(maps("cursor"), "gigantic", "x.md")).toThrow(/neither a tier of 'models\.cursor'.*nor an alias under 'models\.claude-code'/);
    expect(() => resolveTier(maps("cursor", "nowhere"), "opus", "x.md")).toThrow(/declares no 'models\.nowhere'.*--source-surface/);
  });

  const entries = (text: string): ReturnType<typeof splitDocument>["entries"] => splitDocument(text).entries;

  it("rewrites a tier or a source alias to the target alias and leaves every other line alone", () => {
    const result = rewriteModel(row("cursor"), maps("cursor"), entries("---\nname: x\nmodel: deep\n---\n"), "x.md");
    expect(result.alias).toBe("claude-4-opus");
    expect(result.entries.map((entry): string => entry.lines.join("\n"))).toEqual(["name: x", "model: claude-4-opus"]);
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel: sonnet\n---\n"), "x.md").alias).toBe("gpt-4.1");
  });

  it("carries inherit where the row documents it and drops it, saying so, elsewhere", () => {
    const kept = rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel: inherit\n---\n"), "x.md");
    expect(kept.alias).toBe("inherit");
    expect(kept.droppedInherit).toBe(false);
    const dropped = rewriteModel({ ...row("cursor"), inheritModel: false }, maps("cursor"), entries("---\nmodel: inherit\n---\n"), "x.md");
    expect(dropped.alias).toBeNull();
    expect(dropped.droppedInherit).toBe(true);
    expect(dropped.entries).toEqual([]);
  });

  it("refuses an unresolvable value by pointer, and names an alias outside the documented set", () => {
    expect(() => rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: gigantic\n---\n"), "x.md")).toThrow(
      /'x\.md' says 'model: gigantic'/,
    );
    const economy = rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: haiku\n---\n"), "x.md");
    expect(economy.alias).toBe("flash_lite");
    expect(economy.undocumentedAlias).toBe("flash_lite");
    expect(rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: opus\n---\n"), "x.md")).toMatchObject({ alias: "pro", undocumentedAlias: null });
  });

  it("leaves a persona with no model, or an empty one, untouched", () => {
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nname: x\n---\n"), "x.md").alias).toBeNull();
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel:\n---\n"), "x.md").alias).toBeNull();
  });
});

describe("toml strings", () => {
  it("escapes what a basic string cannot carry raw", () => {
    expect(tomlString('say "hi"\\ there\n\tend')).toBe('"say \\"hi\\"\\\\ there\\n\\tend"');
    expect(tomlString(`bell${String.fromCharCode(7)}`)).toBe('"bell\\u0007"');
  });

  it("carries a body line for line in a multi-line string, breaking a triple quote", () => {
    expect(tomlMultiline('one\ntwo """ three\\')).toBe('"""\none\ntwo ""\\" three\\\\\n"""');
    expect(tomlMultiline("ends with newline\n")).toBe('"""\nends with newline\n"""');
  });
});
