// src/surface/packs.test.ts -- the readers and renderers for the files a
// mirror carries beside its skills (zheref/nen#227), over the fixtures under
// ./fixtures/packs and the rows in ./rules.ts.

import { describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { splitDocument } from "./frontmatter.js";
import {
  compareVersions,
  isVersion,
  readHookScripts,
  readHooksManifest,
  readModelMaps,
  readPluginManifest,
  rebaseCommand,
  renderHookScript,
  resolveTier,
  readPermissions,
  readRules,
  renderHooks,
  renderPermissions,
  renderPluginManifest,
  renderRules,
  rewriteModel,
  SurfacePackError,
  tomlMultiline,
  tomlString,
  WRITABLE_ROOTS_NOTE,
  type PermissionsSource,
} from "./packs.js";
import { findSurface, type SurfaceRow } from "./rules.js";

const PACKS = join(process.cwd(), "src", "surface", "fixtures", "packs");
const MARKER = "GENERATED by nen surface mirror (surface: test) -- do not edit; edit the source and regenerate";

function row(name: string): SurfaceRow {
  const found = findSurface(name);
  if (found === undefined) throw new Error(`no row for ${name}`);
  return found;
}
function must<T>(value: T | null): T {
  if (value === null) throw new Error("expected a value");
  return value;
}
const tempFile = (name: string, content: string): string => {
  const dir = mkdtempSync(join(tmpdir(), "nen-packs-"));
  const path = join(dir, name);
  writeFileSync(path, content);
  return path;
};

describe("versions", () => {
  it("accepts MAJOR.MINOR.PATCH with an optional tail, and nothing shorter", () => {
    expect(isVersion("0.43.0")).toBe(true);
    expect(isVersion("1.2.3-rc.1")).toBe(true);
    expect(isVersion("0.43")).toBe(false);
    expect(isVersion("v0.43.0")).toBe(false);
  });

  it("compares numerically, component by component, ignoring the tail", () => {
    expect(compareVersions("0.43.0", "0.43.0")).toBe(0);
    expect(compareVersions("0.9.0", "0.10.0")).toBe(-1);
    expect(compareVersions("1.0.0", "0.99.99")).toBe(1);
    expect(compareVersions("0.43.0-rc.1", "0.43.0")).toBe(0);
    expect(() => compareVersions("x", "0.1.0")).toThrow(SurfacePackError);
  });
});

describe("hooks", () => {
  const manifest = readHooksManifest(join(PACKS, "hooks.json"));

  it("reads the three mapped events and names the ones no row maps", () => {
    expect(manifest.events.Stop).toHaveLength(1);
    expect(manifest.events.PreToolUse[0]?.matcher).toBe("Bash");
    expect(manifest.events.SessionStart[0]?.hooks[0]?.timeout).toBeNull();
    expect(manifest.unmapped).toEqual(["PostToolUse"]);
  });

  it("reads the same three events without the `hooks` wrapper", () => {
    const flat = readHooksManifest(tempFile("hooks.json", '{"Stop":[{"hooks":[{"type":"command","command":"x"}]}]}'));
    expect(flat.events.Stop[0]?.hooks[0]?.command).toBe("x");
  });

  it("refuses a malformed manifest by pointer", () => {
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":[{"hooks":[]}]}}'))).toThrow(/hooks\.Stop\[0\]\.hooks/);
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":[{"hooks":[{"command":""}]}]}}'))).toThrow(/command/);
    expect(() => readHooksManifest(tempFile("h.json", '{"hooks":{"Stop":"no"}}'))).toThrow(/not an array/);
    expect(() => readHooksManifest(tempFile("h.json", "not json"))).toThrow(/not JSON/);
    expect(() => readHooksManifest(join(PACKS, "nowhere.json"))).toThrow(/ENOENT/);
  });

  it("renders the grouped shape with the row's own event names and matcher", () => {
    const text = renderHooks(must(row("antigravity").hooks), manifest, MARKER);
    const doc = JSON.parse(text) as { $generated: string; hooks: Record<string, unknown[]> };
    expect(doc.$generated).toBe(MARKER);
    expect(Object.keys(doc.hooks)).toEqual(["Stop", "PreToolUse", "PreInvocation"]);
    expect(doc.hooks["PreToolUse"]?.[0]).toEqual({
      matcher: "run_command",
      hooks: [{ type: "command", command: "${CLAUDE_PLUGIN_ROOT}/hooks/guard.hook", timeout: 10 }],
    });
    // A command with no timeout carries none, rather than an invented default.
    expect(doc.hooks["PreInvocation"]?.[0]).toEqual({ hooks: [{ type: "command", command: "sh -c 'echo warm'" }] });
  });

  it("renders cursor's flat version-1 shape: one command per entry, no matcher, no timeout", () => {
    const doc = JSON.parse(renderHooks(must(row("cursor").hooks), manifest, MARKER)) as {
      version: number;
      hooks: Record<string, { command: string }[]>;
    };
    expect(doc.version).toBe(1);
    expect(Object.keys(doc.hooks)).toEqual(["stop", "beforeShellExecution", "sessionStart"]);
    expect(doc.hooks["beforeShellExecution"]).toEqual([{ command: "${CLAUDE_PLUGIN_ROOT}/hooks/guard.hook" }]);
  });

  it("reads the scripts a command names from beside the manifest, and marks them under the shebang", () => {
    const scripts = readHookScripts(manifest);
    expect(scripts.map((script): string => script.name)).toEqual(["bell.hook", "guard.hook"]);
    expect(renderHookScript(scripts[0] ?? { name: "", text: "" }, MARKER)).toBe(`#!/bin/sh\n# ${MARKER}\n# rings the bell\necho bell\n`);
    expect(renderHookScript({ name: "x", text: "echo x\n" }, MARKER)).toBe(`# ${MARKER}\necho x\n`);
    expect(() => readHookScripts({ ...manifest, dir: join(PACKS, "nowhere") })).toThrow(/is not a file/);
  });

  it("refuses a script that is a symbolic link, by name, rather than following it out of the manifest's directory (S4)", () => {
    const dir = mkdtempSync(join(tmpdir(), "nen-packs-link-"));
    writeFileSync(join(dir, "guard.hook"), "#!/bin/sh\nexit 0\n");
    symlinkSync(join(PACKS, "bell.hook"), join(dir, "bell.hook"));
    expect(() => readHookScripts({ ...manifest, dir })).toThrow(/'.*bell\.hook' is a symbolic link/);
    // A dangling link is a link too, not "not a file".
    const dangling = mkdtempSync(join(tmpdir(), "nen-packs-link-"));
    writeFileSync(join(dangling, "guard.hook"), "x\n");
    symlinkSync(join(dangling, "gone"), join(dangling, "bell.hook"));
    expect(() => readHookScripts({ ...manifest, dir: dangling })).toThrow(/is a symbolic link/);
  });

  it("rebases the root variable, quoting the root INSIDE the command and wrapping only what still expands", () => {
    expect(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "/opt/p")).toBe("/opt/p/hooks/x.sh");
    // The root is one double-quoted word; the command's own arguments stay separate words (N2).
    expect(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "${ROOT:-$HOME/p}")).toBe(`sh -c 'exec "\${ROOT:-$HOME/p}"/hooks/x.sh' --`);
    expect(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh --mode $MODE", "${ROOT:-$HOME/p}")).toBe(`sh -c 'exec "\${ROOT:-$HOME/p}"/hooks/x.sh --mode $MODE' --`);
    expect(rebaseCommand("echo $HOME", "/opt/p")).toBe(`sh -c 'exec echo $HOME' --`);
    // A root with a space is quoted and wrapped even with no `$` anywhere.
    expect(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "/opt/my plugin")).toBe(`sh -c 'exec "/opt/my plugin"/hooks/x.sh' --`);
    // A single quote is no longer a refusal: the payload carries it as '\''.
    expect(rebaseCommand("echo 'a' $B", "/opt/p")).toBe(`sh -c 'exec echo '\\''a'\\'' $B' --`);
    const rebased = JSON.parse(renderHooks(must(row("cursor").hooks), manifest, MARKER, "/opt/p")) as { hooks: Record<string, { command: string }[]> };
    expect(rebased.hooks["stop"]).toEqual([{ command: "/opt/p/hooks/bell.hook" }]);
  });

  it("refuses, naming the character, a root or command the wrapper cannot hold (S3)", () => {
    expect(() => rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", '/opt/"p')).toThrow(/root expression.*carries a double quote/);
    expect(() => rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "$(id)")).toThrow(/carries a command substitution/);
    expect(() => rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "`id`")).toThrow(/carries a backtick/);
    expect(() => rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh", "/opt/p\\x")).toThrow(/carries a backslash/);
    expect(() => rebaseCommand("echo \"$X\"", "/opt/p")).toThrow(/the command.*carries a double quote/);
    expect(() => rebaseCommand("echo $X\necho y", "/opt/p")).toThrow(/carries a newline/);
    // With no `$` and a plain root nothing is wrapped, so nothing is refused: the command is carried as it was.
    expect(rebaseCommand('echo "plain"', "/opt/p")).toBe('echo "plain"');
  });

  it("emits a string that RUNS under sh -c: a real script in a temp dir, with its arguments intact", () => {
    const dir = mkdtempSync(join(tmpdir(), "nen packs root-"));
    mkdirSync(join(dir, "hooks"));
    const script = join(dir, "hooks", "x.sh");
    writeFileSync(script, '#!/bin/sh\nprintf "%s|" "$@"\n');
    chmodSync(script, 0o755);
    const run = (command: string, env: Record<string, string> = {}): string => {
      const result = spawnSync("sh", ["-c", command], { encoding: "utf8", env: { ...process.env, ...env } });
      return `${result.status}:${result.stdout}`;
    };
    // The root has a space: quoted inside the command, the whole thing wrapped.
    expect(run(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh --mode fast", dir))).toBe("0:--mode|fast|");
    // The root is an expression the surface's shell has to expand.
    expect(run(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh one $TWO", "${DEMO_ROOT:-/nowhere}"), { DEMO_ROOT: dir, TWO: "two" })).toBe("0:one|two|");
    // The single-quote rule survives the shell: a quoted argument arrives whole.
    expect(run(rebaseCommand("${CLAUDE_PLUGIN_ROOT}/hooks/x.sh 'a b' $C", "${DEMO_ROOT}"), { DEMO_ROOT: dir, C: "c" })).toBe("0:a b|c|");
  });

  it("renders the verbatim row's manifest byte for byte", () => {
    expect(renderHooks(must(row("claude-code").hooks), manifest, MARKER)).toBe(manifest.text);
  });
});

describe("plugin manifest", () => {
  it("copies the row's keys under the marker, skipping an absent optional one and refusing an absent required one", () => {
    const rule = must(row("antigravity").pluginManifest);
    const source = readPluginManifest(join(PACKS, "plugin.json"));
    expect(JSON.parse(renderPluginManifest(rule, source, MARKER))).toEqual({ $generated: MARKER, name: "demo", version: "0.1.0", description: "A demo plugin." });
    expect(JSON.parse(renderPluginManifest(rule, { name: "n", description: "d" }, MARKER))).toEqual({ $generated: MARKER, name: "n", description: "d" });
    expect(() => renderPluginManifest(rule, { name: "n" }, MARKER)).toThrow(/no 'description'.*plugin\.json/);
    expect(() => readPluginManifest(tempFile("p.json", "[]"))).toThrow(/not an object/);
  });
});

describe("permissions", () => {
  const source = readPermissions(join(PACKS, "permissions.json"));
  const render = (surface: string, src = source): ReturnType<typeof renderPermissions> =>
    renderPermissions(must(row(surface).permissions), src, MARKER, surface);

  it("reads allow and deny, and refuses a malformed row by pointer", () => {
    expect(source.allow).toHaveLength(3);
    expect(source.deny[1]).toEqual({ exe: "sudo", args: "*" });
    expect(source.surfaces).toEqual({});
    expect(() => readPermissions(tempFile("p.json", '{"allow":[{"exe":""}]}'))).toThrow(/allow\[0\]\.exe/);
    expect(() => readPermissions(tempFile("p.json", '{"deny":{}}'))).toThrow(/deny is not an array/);
    expect(readPermissions(tempFile("p.json", "{}"))).toEqual({ allow: [], deny: [], surfaces: {} });
  });

  it("refuses a parenthesis in an exe or args by pointer: it would close the surface's Tool(...) early (S8)", () => {
    expect(() => readPermissions(tempFile("p.json", '{"allow":[{"exe":"git","args":"log) Bash(rm -rf"}]}'))).toThrow(/allow\[0\]\.args carries a parenthesis/);
    expect(() => readPermissions(tempFile("p.json", '{"deny":[{"exe":"a(","args":""}]}'))).toThrow(/deny\[0\]\.exe carries a parenthesis/);
  });

  it("reads a per-surface block of verbatim rows, and refuses a malformed one by pointer (S5)", () => {
    const src = readPermissions(tempFile("p.json", '{"allow":[{"exe":"nen","args":"*"}],"surfaces":{"cursor":{"allow":["Read(./**)","Write(./**)"],"deny":["Shell(rm:-rf *)"]},"$comment":"x"}}'));
    expect(src.surfaces).toEqual({ cursor: { allow: ["Read(./**)", "Write(./**)"], deny: ["Shell(rm:-rf *)"] } });
    expect(() => readPermissions(tempFile("p.json", '{"surfaces":[]}'))).toThrow(/surfaces is not an object/);
    expect(() => readPermissions(tempFile("p.json", '{"surfaces":{"cursor":{"allow":[""]}}}'))).toThrow(/surfaces\.cursor\.allow\[0\] is not a non-empty string/);
    expect(() => readPermissions(tempFile("p.json", '{"surfaces":{"cursor":{"deny":"x"}}}'))).toThrow(/surfaces\.cursor\.deny is not an array/);
  });

  it("renders Claude Code's settings shape as Bash(exe args) patterns", () => {
    const rendered = render("claude-code");
    const doc = JSON.parse(rendered.content) as { $generated: string; permissions: { allow: string[]; deny: string[] } };
    expect(doc.$generated).toBe(MARKER);
    expect(doc.permissions.allow).toEqual(["Bash(nen *)", "Bash(git fetch *)", "Bash(git write-tree)"]);
    expect(doc.permissions.deny).toEqual(["Bash(git push --force *)", "Bash(sudo *)"]);
    expect(rendered.surfaceRows).toBe(0);
    expect(rendered.writableRootsPlaceholder).toBe(false);
  });

  it("renders Cursor's cli.json in its documented Shell(exe:args) grammar, with nothing the source did not declare (S9, S5)", () => {
    const rendered = render("cursor");
    const doc = JSON.parse(rendered.content) as { permissions: { allow: string[]; deny: string[] } };
    expect(doc.permissions.allow).toEqual(["Shell(nen:*)", "Shell(git:fetch *)", "Shell(git:write-tree)"]);
    expect(doc.permissions.deny).toEqual(["Shell(git:push --force *)", "Shell(sudo:*)"]);
    expect(rendered.surfaceRows).toBe(0);
  });

  it("appends a surface's own rows verbatim after the shared ones, for that surface only", () => {
    const src: PermissionsSource = {
      ...source,
      surfaces: { cursor: { allow: ["Read(./**)", "Write(./**)"], deny: ["Shell(rm:-rf *)"] }, "claude-code": { allow: ["WebFetch"], deny: [] } },
    };
    const cursor = render("cursor", src);
    const doc = JSON.parse(cursor.content) as { permissions: { allow: string[]; deny: string[] } };
    expect(doc.permissions.allow.slice(-2)).toEqual(["Read(./**)", "Write(./**)"]);
    expect(doc.permissions.allow).not.toContain("WebFetch");
    expect(doc.permissions.deny.at(-1)).toBe("Shell(rm:-rf *)");
    expect(cursor.surfaceRows).toBe(3);
    const claude = JSON.parse(render("claude-code", src).content) as { permissions: { allow: string[] } };
    expect(claude.permissions.allow.at(-1)).toBe("WebFetch");
    expect(claude.permissions.allow).not.toContain("Read(./**)");
    // Codex has no rows to append to: a block for it is refused rather than dropped.
    expect(() => render("codex", { ...source, surfaces: { codex: { allow: ["x"], deny: [] } } })).toThrow(/surfaces\.codex carries 1 row/);
  });

  it("renders Codex's config.toml with the marker on line 1, the sandbox stated, and writable_roots EMPTY for the installer (S10)", () => {
    const rendered = render("codex");
    const text = rendered.content;
    expect(text.split("\n")[0]).toBe(`# ${MARKER}`);
    expect(text).toContain('sandbox_mode = "workspace-write"');
    expect(text).toContain(`[sandbox_workspace_write]\n${WRITABLE_ROOTS_NOTE}\nwritable_roots = []\nnetwork_access = true\n`);
    expect(text).not.toContain("<the working tree>");
    expect(rendered.writableRootsPlaceholder).toBe(true);
  });
});

describe("rules", () => {
  const source = readRules(join(PACKS, "rules.md"));

  it("names the file after the source's stem, in the row's directory and extension", () => {
    const rendered = renderRules(must(row("antigravity").rules), source, MARKER);
    expect(rendered.path).toBe("rules/rules.md");
    expect(rendered.content.startsWith(`<!-- ${MARKER} -->\n# House rules`)).toBe(true);
    expect(rendered.chars).toBe(rendered.content.length);
  });

  it("prepends cursor's own frontmatter with the stem as the description", () => {
    const rendered = renderRules(must(row("cursor").rules), source, MARKER);
    expect(rendered.path).toBe("rules/rules.mdc");
    const doc = splitDocument(rendered.content);
    expect(doc.entries.map((entry): string => entry.lines.join("\n"))).toEqual(["description: rules", "alwaysApply: true"]);
    expect(doc.body.split("\n")[0]).toBe(`<!-- ${MARKER} -->`);
  });

  it("REFUSES a rendering over the documented limit, naming both numbers, and never truncates", () => {
    const long = { stem: "long", text: "x".repeat(12_000) };
    expect(() => renderRules(must(row("antigravity").rules), long, MARKER)).toThrow(/over the 12000-character limit/);
    // The same text is fine where the row documents no limit.
    expect(renderRules(must(row("cursor").rules), long, MARKER).chars).toBeGreaterThan(12_000);
  });

  it("refuses a --rules that cannot be read", () => {
    expect(() => readRules(join(PACKS, "nowhere.md"))).toThrow(/ENOENT/);
  });
});

describe("models", () => {
  const workflow = join(PACKS, "workflow.json");
  const maps = (surface: string, sourceSurface = "claude-code"): ReturnType<typeof readModelMaps> =>
    readModelMaps(workflow, surface, sourceSurface);

  it("reads models.<surface> and models.<source-surface>, and refuses a target the file does not declare", () => {
    expect(maps("codex").target["fast"]).toBe("gpt-5-mini");
    expect(maps("codex").source?.["deep"]).toBe("opus");
    expect(maps("codex", "nowhere").source).toBeNull();
    expect(maps("codex").known).toContain("antigravity");
    expect(() => maps("gemini-cli")).toThrow(/no 'models\.gemini-cli'.*claude-code, twins, codex, cursor, antigravity/);
    expect(() => readModelMaps(tempFile("w.json", '{"models":{"codex":{"fast":1}}}'), "codex", "x")).toThrow(/models\.codex\.fast/);
    expect(() => readModelMaps(tempFile("w.json", "[]"), "codex", "x")).toThrow(/not an object/);
  });

  it("resolves a tier name as itself, and a source alias to its one tier", () => {
    expect(resolveTier(maps("cursor"), "deep", "x.md")).toBe("deep");
    expect(resolveTier(maps("cursor"), "opus", "x.md")).toBe("deep");
    expect(resolveTier(maps("cursor"), "haiku", "x.md")).toBe("economy");
  });

  it("refuses an alias under two tiers, an unknown value, and a missing source row -- each by pointer", () => {
    expect(() => resolveTier(maps("cursor", "twins"), "big", "x.md")).toThrow(/'models\.twins' lists under 2 tiers \(frontier, deep\)/);
    expect(() => resolveTier(maps("cursor"), "gigantic", "x.md")).toThrow(/neither a tier of 'models\.cursor'.*nor an alias under 'models\.claude-code'/);
    expect(() => resolveTier(maps("cursor", "nowhere"), "opus", "x.md")).toThrow(/declares no 'models\.nowhere'.*--source-surface/);
  });

  const entries = (text: string): ReturnType<typeof splitDocument>["entries"] => splitDocument(text).entries;

  it("rewrites a tier or a source alias to the target alias and leaves every other line alone", () => {
    const result = rewriteModel(row("cursor"), maps("cursor"), entries("---\nname: x\nmodel: deep\n---\n"), "x.md");
    expect(result.alias).toBe("claude-4-opus");
    expect(result.entries.map((entry): string => entry.lines.join("\n"))).toEqual(["name: x", "model: claude-4-opus"]);
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel: sonnet\n---\n"), "x.md").alias).toBe("gpt-4.1");
  });

  it("carries inherit where the row documents it and drops it, saying so, elsewhere", () => {
    const kept = rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel: inherit\n---\n"), "x.md");
    expect(kept.alias).toBe("inherit");
    expect(kept.droppedInherit).toBe(false);
    const dropped = rewriteModel({ ...row("cursor"), inheritModel: false }, maps("cursor"), entries("---\nmodel: inherit\n---\n"), "x.md");
    expect(dropped.alias).toBeNull();
    expect(dropped.droppedInherit).toBe(true);
    expect(dropped.entries).toEqual([]);
  });

  it("refuses an unresolvable value by pointer, and names an alias outside the documented set", () => {
    expect(() => rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: gigantic\n---\n"), "x.md")).toThrow(
      /'x\.md' says 'model: gigantic'/,
    );
    const economy = rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: haiku\n---\n"), "x.md");
    expect(economy.alias).toBe("flash_lite");
    expect(economy.undocumentedAlias).toBe("flash_lite");
    expect(rewriteModel(row("antigravity"), maps("antigravity"), entries("---\nmodel: opus\n---\n"), "x.md")).toMatchObject({ alias: "pro", undocumentedAlias: null });
  });

  it("leaves a persona with no model, or an empty one, untouched", () => {
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nname: x\n---\n"), "x.md").alias).toBeNull();
    expect(rewriteModel(row("cursor"), maps("cursor"), entries("---\nmodel:\n---\n"), "x.md").alias).toBeNull();
  });
});

describe("toml strings", () => {
  it("escapes what a basic string cannot carry raw", () => {
    expect(tomlString('say "hi"\\ there\n\tend')).toBe('"say \\"hi\\"\\\\ there\\n\\tend"');
    expect(tomlString(`bell${String.fromCharCode(7)}`)).toBe('"bell\\u0007"');
  });

  it("carries a body line for line in a multi-line string, breaking a triple quote", () => {
    expect(tomlMultiline('one\ntwo """ three\\')).toBe('"""\none\ntwo ""\\" three\\\\\n"""');
    expect(tomlMultiline("ends with newline\n")).toBe('"""\nends with newline\n"""');
  });
});
