<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <AppxPackageSigningEnabled>False</AppxPackageSigningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="KroCore\KroCore.csproj" />
  </ItemGroup>
</Project>
