// src/runner/script.ts -- `nen runner script`: the HOST script that registers a
// plan's runners as boot-persistent services, rendered deterministically, one
// per operating system.
//
// NEN RENDERS; NEN NEVER RUNS IT. The script registers Windows services, grants
// folder rights and asks for a service account's password -- every one of
// those is an act on the maintainer's machine that the maintainer consents to
// (a UAC prompt on Windows, their own `sudo` on Linux). So the verb's whole
// output is a file and the ONE command line that launches it; running that
// line is the caller's, and on Windows the elevation is the human's.
//
// THE SECRETS NEVER PASS THROUGH NEN. The registration token is minted INSIDE
// the script, by `gh`, at the moment `config` needs it, into a variable that
// is never printed; the Windows account password is typed ONCE into
// `Read-Host -AsSecureString`, checked against the refused-character rule
// before its first use, and turned into plain text only for the one config
// call. NEITHER SECRET IS EVER ON A COMMAND LINE (#312, SEC-1): `config.cmd` is
// a batch file cmd.exe re-parses, so `& | < > ^ %` in an argument split it,
// expanded it or ran a command. Both reach the runner through its
// `ACTIONS_RUNNER_INPUT_<ARG>` environment inputs instead (actions/runner's
// CommandSettings.cs reads, masks and removes them), set on this process only
// for the child's lifetime and cleared in a `finally`. Config's own output is
// DISCARDED, never replayed into the transcript: its exit code and a fixed
// line are all the log carries. The bash scripts pass the token the same way.
//
// THE RUNNER ROOT IS LOCKED BEFORE IT IS USED (#312, SEC-9). A root an
// unelevated session created inherits `Authenticated Users: Modify` from the
// drive; the Windows script takes ownership for Administrators, removes the
// inherited entries and grants SYSTEM and Administrators full control BEFORE
// anything is downloaded or run from it, keeps the package in an admin-only
// `_jusshin\pkg`, and re-hashes it before every extraction. The script ITSELF
// is protected by where it is written: `nen runner script` refuses an `--out`
// under the plan's root, and the docs place it in the user's profile.
//
// DETERMINISTIC TO THE BYTE. No timestamp, no host name, no random value is
// rendered: the transcript's own file name is computed by the SCRIPT when it
// runs. The version in the header is a parameter so the golden files
// (./fixtures/*.golden) survive a release.
//
// POWERSHELL 5.1, NOT 7. The Windows host this was built for has no `pwsh`, and
// a runner host is exactly the machine nobody has provisioned yet: no `&&`, no
// `??`, no ternary, ASCII only (5.1 reads a BOM-less file as the ANSI code page,
// so an em dash in the header would render as mojibake -- the bash scripts
// carry it, the .ps1 writes `--`). Native commands run with
// `$ErrorActionPreference = 'Continue'` around them, because under 'Stop' a
// 5.1 host turns any stderr line of a native program into a terminating error.

//
// AN INTERACTIVE WINDOWS POOL IS A LOGON TASK, NEVER A SERVICE (#333). A
// service runs in session 0, which has no desktop, so a job that drives a real
// UI times out there. For `mode: interactive` the script configures the runner
// WITHOUT `--runasservice`, grants the identity Modify on its own runner folder,
// and registers a Scheduled Task that starts `run.cmd` at that identity's logon,
// in its desktop session (interactive token: no password is asked or stored),
// restarting on failure, with no time limit. Every other guarantee above holds:
// the locked root, the re-hashed package, the token through the environment,
// the summary file.

import type { RunnerPlan } from "./plan.js";
import { isLogonTask, NETWORK_SERVICE } from "./plan.js";

export interface RenderedScript {
  readonly os: RunnerPlan["os"];
  readonly text: string;
  readonly needsElevation: boolean;
}

/**
 * The characters a Windows service-account password may not carry (#312,
 * SEC-1): the ones cmd.exe or PowerShell read as syntax, plus a line break.
 * The script refuses such a password before its first use, as defense in depth
 * behind the environment path -- and names this rule when it does.
 */
export const REFUSED_PASSWORD_CHARACTERS = `& | < > ^ % " ' or a line break`;

/** The same set as a regular expression; .NET and JavaScript read this class identically. */
export const REFUSED_PASSWORD_PATTERN = `[&|<>^%"'\\r\\n]`;

/** The summary file(s) a run leaves, as a glob under the project dir's _jusshin folder. */
export function summaryGlob(plan: RunnerPlan): string {
  const sep = plan.os === "Windows" ? "\\" : "/";
  return `${plan.projectDir}${sep}_jusshin${sep}register-*.summary`;
}

/** A PowerShell single-quoted literal. Plan values are validated to carry no quote; this is the second belt. */
function ps(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** A bash single-quoted literal, same reasoning. */
function sh(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function header(plan: RunnerPlan, version: string, comment: string, dash: string, what: string): string[] {
  return [
    `${comment} jusshin ${dash} register self-hosted GitHub Actions runners ${what}.`,
    `${comment} rendered by nen ${version} runner script ${dash} do not edit; re-run nen runner script`,
    `${comment}`,
    `${comment} target:   ${plan.target}`,
    `${comment} pool:     ${plan.pool} (${plan.labels.join(",")})`,
    `${comment} runners:  ${plan.runners.map((runner): string => runner.name).join(", ")}`,
    `${comment} identity: ${plan.identity}`,
    `${comment} root:     ${plan.root}`,
    `${comment} package:  ${plan.download.filename} (runner ${plan.runnerVersion})`,
  ];
}

// ── Windows ─────────────────────────────────────────────────────────────────

/** The service account's password, asked once and checked before its first use. A logon task asks none. */
const PASSWORD_PROMPT = [
  "    if ($pending.Count -gt 0 -and $Account -ne '') {",
  "        $secure = Read-Host -AsSecureString ('Password for {0} (asked once; never shown, never written)' -f $Identity)",
  "        $refusal = $null",
  "        $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)",
  "        try {",
  "            $refusal = Test-Password ([Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr))",
  "        } finally {",
  "            [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)",
  "        }",
  "        if ($null -ne $refusal) {",
  "            $secure.Dispose()",
  "            Write-Host ('jusshin: the password for {0} is refused: {1}. The rule: a service-account password carries none of {2}, and no leading or trailing whitespace. Change the account''s password and re-run.' -f $Identity, $refusal, $PasswordRule)",
  "            $script:Failed += $pending.Count",
  "            Close-Run 1",
  "        }",
  "    }",
];

/** Why a password is refused -- the service form's check, rendered only where a password is asked. */
const TEST_PASSWORD = [
  "# Why a password is refused, or $null. The rule: none of the characters",
  "# cmd.exe or PowerShell read as syntax, and no leading or trailing whitespace",
  "# (the runner trims an environment input). Checked BEFORE the first use.",
  "function Test-Password {",
  "    param([string]$Plain)",
  "    if ([string]::IsNullOrEmpty($Plain)) { return 'it is empty' }",
  `    if ($Plain -match ${ps(REFUSED_PASSWORD_PATTERN)}) { return 'it carries a refused character' }`,
  "    if ($Plain -cne $Plain.Trim()) { return 'it begins or ends with whitespace' }",
  "    return $null",
  "}",
  "",
];

export function renderWindows(plan: RunnerPlan, version: string): string {
  const account = plan.identity === NETWORK_SERVICE ? "" : plan.identity.slice(2);
  const [owner, repo] = plan.target.split("/") as [string, string];
  const runners = plan.runners.map(
    (runner, index): string =>
      `    @{ Name = ${ps(runner.name)}; Dir = ${ps(runner.installDir)} }${index === plan.runners.length - 1 ? "" : ","}`,
  );
  const task = isLogonTask(plan);
  const intro = task
    ? [
        ...header(plan, version, "#", "--", "as logon tasks in a desktop session"),
        "#",
        "# Windows PowerShell 5.1. Run it ELEVATED: 'nen runner script --json' prints",
        "# the one launch line, which opens it through a UAC prompt. Keep this file",
        "# OUTSIDE the runner root (e.g. %LOCALAPPDATA%\\nen\\jusshin\\), where only you",
        "# can change it before UAC.",
        "#",
        "# INTERACTIVE, NOT A SERVICE. Each runner is configured without --runasservice",
        "# and started by a Scheduled Task at the identity's logon, in its desktop",
        "# session (interactive token: no password is asked, none is stored). A runner",
        "# is online only while that identity is signed in (or auto-logged on -- this",
        "# script never configures that), and every job it takes runs with that",
        "# account's profile and credentials. Every registration token this script",
        "# mints with gh lives only in this process: never on a command line",
        "# (config.cmd reads it from ACTIONS_RUNNER_INPUT_TOKEN), never echoed, never",
        "# written to a file, and config.cmd's output is never replayed.",
        "#",
        "# The runner root is locked down FIRST: owner Administrators, inherited",
        "# entries removed, SYSTEM and Administrators full control. The package lives",
        "# in an admin-only _jusshin\\pkg and is re-hashed before every extraction.",
        "# The identity gets Modify on its own Runner<N> folders only.",
        "# The one summary line is also written to _jusshin\\register-<ts>.summary.",
        "#",
        "# Exit codes: 0 every planned runner's logon task is registered, and running",
        "# wherever the identity is signed in; 1 anything else (an identity that is",
        "# not a local account included); 3 not elevated; 5 gh missing or not signed",
        "# in; 6 the runner package failed its SHA-256 check (the file is deleted).",
        "",
      ]
    : [
        ...header(plan, version, "#", "--", "as Windows services"),
        "#",
        "# Windows PowerShell 5.1. Run it ELEVATED: 'nen runner script --json' prints",
        "# the one launch line, which opens it through a UAC prompt. Keep this file",
        "# OUTSIDE the runner root (e.g. %LOCALAPPDATA%\\nen\\jusshin\\), where only you",
        "# can change it before UAC. It asks ONCE for the service account's password.",
        "# That password, and every registration token this script mints with gh,",
        "# live only in this process: never on a command line (config.cmd reads them",
        "# from ACTIONS_RUNNER_INPUT_* environment inputs), never echoed, never",
        "# written to a file, and config.cmd's output is never replayed.",
        "#",
        "# The runner root is locked down FIRST: owner Administrators, inherited",
        "# entries removed, SYSTEM and Administrators full control. The package lives",
        "# in an admin-only _jusshin\\pkg and is re-hashed before every extraction.",
        "# The one summary line is also written to _jusshin\\register-<ts>.summary.",
        "#",
        "# Exit codes: 0 every planned runner's service is Running; 1 anything else",
        "# (a refused password included); 3 not elevated; 5 gh missing or not signed",
        "# in; 6 the runner package failed its SHA-256 check (the file is deleted).",
        "",
      ];
  return [
    ...intro,
    "$ErrorActionPreference = 'Stop'",
    "$ProgressPreference = 'SilentlyContinue'",
    "",
    `$Target = ${ps(plan.target)}`,
    `$RepoUrl = ${ps(`https://github.com/${plan.target}`)}`,
    `$Labels = ${ps(plan.labels.join(","))}`,
    `$Root = ${ps(plan.root)}`,
    `$ProjectDir = ${ps(plan.projectDir)}`,
    `$Identity = ${ps(plan.identity)}`,
    `$Account = ${ps(account)}`,
    `$DownloadUrl = ${ps(plan.download.download_url)}`,
    `$ZipName = ${ps(plan.download.filename)}`,
    `$Sha256 = ${ps(plan.download.sha256_checksum.toUpperCase())}`,
    ...(task
      ? [
          `$ServicePrefix = ${ps(`actions.runner.${owner}-${repo}.`)}`,
          `$TaskPrefix = ${ps(`actions.runner.${owner}-${repo}.`)}`,
        ]
      : [`$ServicePrefix = ${ps(`actions.runner.${owner}-${repo}.`)}`, `$PasswordRule = ${ps(REFUSED_PASSWORD_CHARACTERS)}`]),
    "$Runners = @(",
    ...runners,
    ")",
    "",
    "$WorkDir = Join-Path $ProjectDir '_jusshin'",
    "$PkgDir = Join-Path $WorkDir 'pkg'",
    "# Well-known SIDs, so the grants read the same in every display language.",
    "$SystemSid = '*S-1-5-18'",
    "$AdminsSid = '*S-1-5-32-544'",
    "$script:Registered = 0",
    "$script:Skipped = 0",
    "$script:Failed = 0",
    "$script:Listed = @()",
    "$script:ListOk = $false",
    "$script:ListRead = $false",
    "$script:Transcribing = $false",
    "$script:Stamp = Get-Date -Format 'yyyyMMdd-HHmmss'",
    "$script:LogPath = $null",
    "$script:SummaryPath = $null",
    "",
    "function Close-Run {",
    "    param([int]$Code)",
    "    $summary = 'jusshin: {0} registered, {1} skipped, {2} failed' -f $script:Registered, $script:Skipped, $script:Failed",
    "    Write-Host $summary",
    "    # The summary file carries that ONE line and nothing else: it is what the",
    "    # caller reads. The transcript is the maintainer's.",
    "    if ($null -ne $script:SummaryPath) {",
    "        try {",
    "            Set-Content -LiteralPath $script:SummaryPath -Value $summary -Encoding Ascii",
    "        } catch {",
    "            Write-Host ('jusshin: could not write {0}.' -f $script:SummaryPath)",
    "        }",
    "    }",
    "    if ($script:Transcribing) {",
    "        Stop-Transcript | Out-Null",
    "        $script:Transcribing = $false",
    "    }",
    "    # Keep the elevated window open on a failure, so its lines can be read.",
    "    if ($Code -ne 0 -and $Host.Name -eq 'ConsoleHost' -and [Environment]::UserInteractive) {",
    "        Read-Host 'press Enter to close' | Out-Null",
    "    }",
    "    exit $Code",
    "}",
    "",
    "# A native command, its output discarded, its exit code returned.",
    "function Invoke-Quiet {",
    "    param([string]$FilePath, [string[]]$ArgumentList)",
    "    $previous = $ErrorActionPreference",
    "    $ErrorActionPreference = 'Continue'",
    "    try {",
    "        & $FilePath @ArgumentList *> $null",
    "        return $LASTEXITCODE",
    "    } finally {",
    "        $ErrorActionPreference = $previous",
    "    }",
    "}",
    "",
    "# One icacls call; any failure stops the run before the root is used.",
    "function Invoke-Icacls {",
    "    param([string[]]$ArgumentList)",
    "    $code = Invoke-Quiet 'icacls' $ArgumentList",
    "    if ($code -ne 0) {",
    "        Write-Host ('jusshin: icacls {0} failed (exit {1}); the runner root is not locked down, so nothing is downloaded or run.' -f ($ArgumentList -join ' '), $code)",
    "        Close-Run 1",
    "    }",
    "}",
    "",
    ...(task ? [] : TEST_PASSWORD),
    "# Whether the package on disk is the one the plan names, hashed NOW.",
    "function Test-Package {",
    "    param([string]$Path)",
    "    if (-not (Test-Path -LiteralPath $Path)) { return $false }",
    "    return ((Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash -eq $Sha256)",
    "}",
    "",
    "# Why a folder configured as $Name is stale, or $null when it stands: its",
    "# service is absent, or GitHub no longer lists its registration (#319).",
    "function Get-StaleReason {",
    "    param([string]$Name, [bool]$HasService, [string[]]$Listed)",
    "    $reasons = @()",
    "    if (-not $HasService) { $reasons += 'its service is absent' }",
    "    # Case-sensitive, as the bash scripts' grep -Fx is: one listing, one verdict on every OS.",
    "    if ($Listed -cnotcontains $Name) { $reasons += 'GitHub no longer lists its registration' }",
    "    if ($reasons.Count -eq 0) { return $null }",
    "    return ($reasons -join ' and ')",
    "}",
    "",
    "# The names GitHub lists for the repository's runners, read once into",
    "# $script:Listed; $script:ListOk says whether the read succeeded.",
    "function Read-ListedRunners {",
    "    if ($script:ListRead) { return }",
    "    $script:ListRead = $true",
    "    $previous = $ErrorActionPreference",
    "    $ErrorActionPreference = 'Continue'",
    "    try {",
    "        $names = @(& gh api --paginate ('repos/{0}/actions/runners' -f $Target) --jq '.runners[].name' 2> $null)",
    "        if ($LASTEXITCODE -eq 0) {",
    "            $script:Listed = [string[]]$names",
    "            $script:ListOk = $true",
    "        }",
    "    } finally {",
    "        $ErrorActionPreference = $previous",
    "    }",
    "}",
    "",
    "function Start-Log {",
    "    Start-Transcript -Path $script:LogPath -Append | Out-Null",
    "    $script:Transcribing = $true",
    "}",
    "",
    "function Stop-Log {",
    "    if ($script:Transcribing) {",
    "        Stop-Transcript | Out-Null",
    "        $script:Transcribing = $false",
    "    }",
    "}",
    "",
    "try {",
    "    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())",
    "    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {",
    task
      ? "        Write-Host 'jusshin: run elevated -- this script registers Scheduled Tasks for another account and grants folder rights.'"
      : "        Write-Host 'jusshin: run elevated -- this script registers Windows services and grants folder rights.'",
    "        Close-Run 3",
    "    }",
    "",
    "    # LOCK THE ROOT DOWN before anything is downloaded, extracted or run from it.",
    "    # A root an unelevated session created inherits 'Authenticated Users: Modify'",
    "    # from the drive: any signed-in principal -- the pool's own service account",
    "    # included -- could swap the package or config.cmd under this process. The",
    "    # root: owner Administrators, inherited entries removed, SYSTEM and",
    "    # Administrators full control inherited by everything below (explicit grants",
    "    # other projects' accounts hold on it are kept). The project folders: owner",
    "    # Administrators, their own explicit entries reset. The package folder: no",
    "    # inheritance at all. You (the elevated user) may READ _jusshin, where the",
    "    # transcript and the summary file land.",
    "    $Me = '*' + [Security.Principal.WindowsIdentity]::GetCurrent().User.Value",
    "    if (-not (Test-Path -LiteralPath $Root)) { New-Item -ItemType Directory -Path $Root | Out-Null }",
    "    Invoke-Icacls @($Root, '/setowner', $AdminsSid)",
    "    Invoke-Icacls @($Root, '/inheritance:r', '/grant:r', ($SystemSid + ':(OI)(CI)F'), ($AdminsSid + ':(OI)(CI)F'))",
    "    foreach ($dir in @($ProjectDir, $WorkDir, $PkgDir)) {",
    "        if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }",
    "        Invoke-Icacls @($dir, '/setowner', $AdminsSid)",
    "        Invoke-Icacls @($dir, '/reset')",
    "    }",
    "    Invoke-Icacls @($PkgDir, '/inheritance:r', '/grant:r', ($SystemSid + ':(OI)(CI)F'), ($AdminsSid + ':(OI)(CI)F'))",
    "    Invoke-Icacls @($WorkDir, '/grant', ($Me + ':(OI)(CI)RX'))",
    "    Write-Host ('jusshin: {0} locked down (owner Administrators; SYSTEM and Administrators full control; no inherited entries).' -f $Root)",
    "",
    "    $script:LogPath = Join-Path $WorkDir ('register-{0}.log' -f $script:Stamp)",
    "    $script:SummaryPath = Join-Path $WorkDir ('register-{0}.summary' -f $script:Stamp)",
    "    Start-Log",
    "    Write-Host ('jusshin: {0} runner(s) for {1}; transcript {2}' -f $Runners.Count, $Target, $script:LogPath)",
    "",
    "    if ($null -eq (Get-Command gh -ErrorAction SilentlyContinue)) {",
    "        Write-Host 'jusshin: gh is not on PATH for this elevated shell. Install the GitHub CLI machine-wide and re-run.'",
    "        Close-Run 5",
    "    }",
    "    if ((Invoke-Quiet 'gh' @('auth', 'status')) -ne 0) {",
    "        Write-Host \"jusshin: 'gh auth status' failed in this elevated shell. Run 'gh auth login' as this user and re-run.\"",
    "        Close-Run 5",
    "    }",
    "",
    ...(task
      ? [
          "    # The logon task belongs to a LOCAL account on this host: one that does not",
          "    # exist could never sign in, so its task would never fire.",
          "    $localUser = $null",
          "    try { $localUser = Get-LocalUser -Name $Account -ErrorAction Stop } catch { $localUser = $null }",
          "    if ($null -eq $localUser -or -not $localUser.Enabled) {",
          "        Write-Host ('jusshin: {0} is not an enabled local account on {1}; an interactive runner starts at that account''s logon. Create it (or name another with nen runner plan --service-account) and re-run.' -f $Identity, $env:COMPUTERNAME)",
          "        Close-Run 1",
          "    }",
          "    $TaskUser = '{0}\\{1}' -f $env:COMPUTERNAME, $Account",
          "",
        ]
      : []),
    ...(task
      ? [
          "    # Traverse rights for the identity: read-and-execute on the root and the",
          "    # project folder, THIS FOLDER ONLY (no inheritance). The leaf Runner<N>",
          "    # folders are granted below, before each logon task. icacls /grant is",
          "    # idempotent.",
        ]
      : [
          "    # Traverse rights for a local-account service: read-and-execute on the root",
          "    # and the project folder, THIS FOLDER ONLY (no inheritance). config.cmd grants",
          "    # the leaf Runner<N> folders itself. icacls /grant is idempotent.",
        ]),
    "    if ($Account -ne '') {",
    "        foreach ($dir in @($Root, $ProjectDir)) {",
    "            $code = Invoke-Quiet 'icacls' @($dir, '/grant', ('{0}:(RX)' -f $Account))",
    "            if ($code -ne 0) {",
    "                Write-Host ('jusshin: icacls could not grant {0} read-and-execute on {1} (exit {2}).' -f $Account, $dir, $code)",
    "                Close-Run 1",
    "            }",
    "            Write-Host ('jusshin: {0} may traverse {1} (RX, this folder only).' -f $Account, $dir)",
    "        }",
    "    }",
    "",
    "    $pending = @()",
    "    foreach ($runner in $Runners) {",
    "        $marker = Join-Path $runner.Dir '.runner'",
    "        if (Test-Path -LiteralPath $marker) {",
    "            $agent = $null",
    "            try { $agent = (Get-Content -LiteralPath $marker -Raw | ConvertFrom-Json).agentName } catch { $agent = $null }",
    "            if ($agent -eq $runner.Name) {",
    "                # Configured is not standing (#319): a failed service install leaves",
    "                # .runner behind with no service, and a removed registration leaves",
    "                # one GitHub no longer lists. Either is stale -- emptied and",
    "                # re-registered, never counted as skipped.",
    "                Read-ListedRunners",
    "                if (-not $script:ListOk) {",
    "                    Write-Host ('jusshin: could not list the runners of {0}, so {1} in {2} cannot be told live from stale -- left untouched (the gh user must be an admin of {0}).' -f $Target, $runner.Name, $runner.Dir)",
    "                    $script:Failed++",
    "                    continue",
    "                }",
    "                $serviceName = $ServicePrefix + $runner.Name",
    "                $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue",
    ...(task
      ? [
          "                # A logon-task runner has no service by design, and its task is",
          "                # (re)registered below for every configured runner: only GitHub's",
          "                # listing can make it stale. A service left in its folder is refused",
          "                # below, not deleted here.",
          "                $stale = Get-StaleReason $runner.Name $true $script:Listed",
        ]
      : ["                $stale = Get-StaleReason $runner.Name ($null -ne $service) $script:Listed"]),
    "                if ($null -eq $stale) {",
    "                    Write-Host ('jusshin: {0} is already configured in {1} -- skipped.' -f $runner.Name, $runner.Dir)",
    "                    $script:Skipped++",
    "                    continue",
    "                }",
    "                Write-Host ('jusshin: {0} in {1} is stale ({2}) -- emptied and re-registered.' -f $runner.Name, $runner.Dir, $stale)",
    "                if ($null -ne $service) {",
    "                    # sc.exe delete only MARKS a running service: it must be stopped first,",
    "                    # or its listener keeps the folder's files open and config.cmd meets",
    "                    # a service still marked for deletion.",
    "                    Stop-Service -Name $serviceName -Force -ErrorAction SilentlyContinue",
    "                    $state = (Get-Service -Name $serviceName -ErrorAction SilentlyContinue).Status",
    "                    if ($null -ne $state -and $state -ne 'Stopped') {",
    "                        Write-Host ('jusshin: {0} did not stop (it is {1}); {2} left untouched.' -f $serviceName, $state, $runner.Dir)",
    "                        $script:Failed++",
    "                        continue",
    "                    }",
    "                    $code = Invoke-Quiet 'sc.exe' @('delete', $serviceName)",
    "                    if ($code -ne 0) {",
    "                        Write-Host ('jusshin: sc.exe delete {0} failed (exit {1}); {2} left untouched.' -f $serviceName, $code, $runner.Dir)",
    "                        $script:Failed++",
    "                        continue",
    "                    }",
    "                }",
    "                $pending += @{ Name = $runner.Name; Dir = $runner.Dir; Replace = ($script:Listed -ccontains $runner.Name) }",
    "                continue",
    "            }",
    "            Write-Host ('jusshin: {0} holds a runner configured as {1}, not {2} -- left untouched.' -f $runner.Dir, $agent, $runner.Name)",
    "            $script:Failed++",
    "            continue",
    "        }",
    "        $pending += $runner",
    "    }",
    "",
    ...(task ? [] : ["    $secure = $null", ...PASSWORD_PROMPT, ""]),
    "    $zip = Join-Path $PkgDir $ZipName",
    "    if ($pending.Count -gt 0) {",
    "        if (-not (Test-Package $zip)) {",
    "            [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12",
    "            Write-Host ('jusshin: downloading {0}' -f $ZipName)",
    "            Invoke-WebRequest -Uri $DownloadUrl -OutFile $zip -UseBasicParsing",
    "            $actual = (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash",
    "            if ($actual -ne $Sha256) {",
    "                Remove-Item -LiteralPath $zip -Force",
    "                Write-Host ('jusshin: {0} failed its SHA-256 check (expected {1}, got {2}) -- deleted.' -f $ZipName, $Sha256, $actual)",
    "                Close-Run 6",
    "            }",
    "        }",
    "        Write-Host ('jusshin: {0} verified (sha256 {1}).' -f $ZipName, $Sha256)",
    "    }",
    "",
    "    foreach ($runner in $pending) {",
    "        $name = $runner.Name",
    "        $dir = $runner.Dir",
    "        Write-Host ('jusshin: registering {0} in {1}' -f $name, $dir)",
    "        # A pending folder holds no configured runner (.runner is absent) or a",
    "        # stale one, so anything in it predates this run's lockdown: it is",
    "        # emptied, never trusted.",
    "        if (Test-Path -LiteralPath $dir) {",
    "            # One folder a process still holds fails that runner alone, never the run.",
    "            try {",
    "                Remove-Item -LiteralPath $dir -Recurse -Force -ErrorAction Stop",
    "            } catch {",
    "                Write-Host ('jusshin: could not empty {0} for {1}: {2}' -f $dir, $name, $_.Exception.Message)",
    "                $script:Failed++",
    "                continue",
    "            }",
    "        }",
    "        New-Item -ItemType Directory -Path $dir | Out-Null",
    "        # Re-hashed immediately before EVERY extraction, not only after the download.",
    "        if (-not (Test-Package $zip)) {",
    "            Remove-Item -LiteralPath $zip -Force -ErrorAction SilentlyContinue",
    "            Write-Host ('jusshin: {0} no longer matches sha256 {1} -- deleted; nothing extracted into {2}.' -f $ZipName, $Sha256, $dir)",
    "            Close-Run 6",
    "        }",
    "        Expand-Archive -LiteralPath $zip -DestinationPath $dir -Force",
    "",
    "        # A fresh registration token, minted NOW (it lives about an hour), into a",
    "        # variable that is never printed.",
    "        $token = $null",
    "        $mint = 1",
    "        $previous = $ErrorActionPreference",
    "        $ErrorActionPreference = 'Continue'",
    "        try {",
    "            $token = [string](& gh api -X POST ('repos/{0}/actions/runners/registration-token' -f $Target) --jq .token 2> $null)",
    "            $mint = $LASTEXITCODE",
    "        } finally {",
    "            $ErrorActionPreference = $previous",
    "        }",
    "        if ($mint -ne 0 -or [string]::IsNullOrWhiteSpace($token)) {",
    "            Write-Host ('jusshin: could not mint a registration token for {0} (gh exit {1}); the gh user must be an admin of {2}.' -f $name, $mint, $Target)",
    "            $token = $null",
    "            $script:Failed++",
    "            continue",
    "        }",
    "",
    ...(task
      ? [
          "        # NO SECRET ON THE COMMAND LINE: config.cmd is a batch file, and cmd.exe",
          "        # re-parses & | < > ^ % in its arguments. The token reaches the runner as",
          "        # ACTIONS_RUNNER_INPUT_TOKEN, which actions/runner reads as its --token",
          "        # input, masks, and removes from its own environment. It exists in this",
          "        # process only for the call, and config.cmd's output is DISCARDED: the log",
          "        # gets its exit code and a fixed line, never a replay. NO --runasservice:",
          "        # this runner is started by a logon task, in a desktop session.",
          "        $configArgs = @('--unattended', '--url', $RepoUrl, '--name', $name, '--labels', $Labels, '--work', '_work')",
          "        # A stale runner GitHub still lists is replaced under its own name.",
          "        if ($runner.Replace) { $configArgs += '--replace' }",
          "        $code = 1",
          "        Stop-Log",
          "        try {",
          "            $env:ACTIONS_RUNNER_INPUT_TOKEN = $token",
        ]
      : [
          "        # NO SECRET ON THE COMMAND LINE: config.cmd is a batch file, and cmd.exe",
          "        # re-parses & | < > ^ % in its arguments. The token and the password reach",
          "        # the runner as ACTIONS_RUNNER_INPUT_TOKEN and",
          "        # ACTIONS_RUNNER_INPUT_WINDOWSLOGONPASSWORD, which actions/runner reads as",
          "        # its --token and --windowslogonpassword inputs, masks, and removes from",
          "        # its own environment. They exist in this process only for the call, and",
          "        # config.cmd's output is DISCARDED: the log gets its exit code and a fixed",
          "        # line, never a replay. The transcript is stopped around it all the same.",
          "        $configArgs = @('--unattended', '--url', $RepoUrl, '--name', $name, '--labels', $Labels, '--work', '_work', '--runasservice')",
          "        if ($Account -ne '') { $configArgs += @('--windowslogonaccount', $Identity) }",
          "        # A stale runner GitHub still lists is replaced under its own name.",
          "        if ($runner.Replace) { $configArgs += '--replace' }",
          "        $bstr = [IntPtr]::Zero",
          "        $code = 1",
          "        Stop-Log",
          "        try {",
          "            $env:ACTIONS_RUNNER_INPUT_TOKEN = $token",
          "            if ($Account -ne '') {",
          "                $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)",
          "                $env:ACTIONS_RUNNER_INPUT_WINDOWSLOGONPASSWORD = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)",
          "            }",
        ]),
    "            Push-Location -LiteralPath $dir",
    "            $previous = $ErrorActionPreference",
    "            $ErrorActionPreference = 'Continue'",
    "            try {",
    "                & .\\config.cmd @configArgs *> $null",
    "                $code = $LASTEXITCODE",
    "            } finally {",
    "                $ErrorActionPreference = $previous",
    "                Pop-Location",
    "            }",
    "        } finally {",
    "            [Environment]::SetEnvironmentVariable('ACTIONS_RUNNER_INPUT_TOKEN', $null, 'Process')",
    ...(task
      ? []
      : [
          "            [Environment]::SetEnvironmentVariable('ACTIONS_RUNNER_INPUT_WINDOWSLOGONPASSWORD', $null, 'Process')",
          "            if ($bstr -ne [IntPtr]::Zero) { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }",
        ]),
    "            $token = $null",
    "            $configArgs = $null",
    "            Start-Log",
    "        }",
    "        if ($code -ne 0) {",
    "            Write-Host ('jusshin: config.cmd exited {0} for {1}; its own (masked) log is under {2}\\_diag.' -f $code, $name, $dir)",
    "            $script:Failed++",
    "            continue",
    "        }",
    "        $script:Registered++",
    "    }",
    ...(task ? [] : ["    if ($null -ne $secure) { $secure.Dispose() }"]),
    "",
    ...(task ? LOGON_TASKS : SERVICE_CHECK),
    "} catch {",
    "    Write-Host ('jusshin: stopped -- {0}' -f $_.Exception.Message)",
    "    $script:Failed++",
    "    Close-Run 1",
    "}",
    "",
  ].join("\n");
}

/** The service form's tail: every planned runner's service Running. */
const SERVICE_CHECK = [
    "    # Every planned runner's service must be Running -- skipped ones included;",
    "    # a stopped one is started once (a service inherits PATH only at start).",
    "    $down = 0",
    "    foreach ($runner in $Runners) {",
    "        $serviceName = $ServicePrefix + $runner.Name",
    "        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue",
    "        if ($null -eq $service) {",
    "            Write-Host ('jusshin: no service {0}.' -f $serviceName)",
    "            $down++",
    "            continue",
    "        }",
    "        if ($service.Status -ne 'Running') {",
    "            try {",
    "                Start-Service -Name $serviceName",
    "                $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))",
    "            } catch {",
    "                Write-Host ('jusshin: {0} did not start: {1}' -f $serviceName, $_.Exception.Message)",
    "            }",
    "            $service = Get-Service -Name $serviceName",
    "        }",
    "        if ($service.Status -ne 'Running') {",
    "            Write-Host ('jusshin: {0} is {1}.' -f $serviceName, $service.Status)",
    "            $down++",
    "        }",
    "    }",
    "    Get-Service -Name ($ServicePrefix + '*') -ErrorAction SilentlyContinue | Sort-Object Name | Format-Table -AutoSize Name, Status, StartType | Out-String -Width 200 | Write-Host",
    "",
    "    if ($down -eq 0 -and $script:Failed -eq 0) { Close-Run 0 }",
    "    Close-Run 1",
];

/**
 * The interactive form's tail: for every planned runner, skipped ones included,
 * the identity's Modify grant on its own folder and its logon task -- then the
 * task started wherever the identity is already signed in.
 */
const LOGON_TASKS = [
  "    # run.cmd runs AS the identity and writes _diag, _work and its own updates",
  "    # into its folder: Modify there, on that folder only. icacls /grant and",
  "    # Register-ScheduledTask -Force are both idempotent.",
  "    if ($env:USERNAME -eq $Account) {",
  "        Write-Host ('jusshin: WARNING -- {0} is the account running this script: every job these runners take runs in your own desktop session, with your profile and credentials.' -f $Identity)",
  "    }",
  "    # Signed in = owns an explorer.exe on this host. A query that fails is said",
  "    # out loud: the tasks are then registered but not started.",
  "    $signedIn = $false",
  "    $probed = $true",
  "    try {",
  "        $owners = Get-CimInstance Win32_Process -Filter \"Name = 'explorer.exe'\" | ForEach-Object { Invoke-CimMethod -InputObject $_ -MethodName GetOwner }",
  "        $signedIn = @($owners | Where-Object { $_.User -eq $Account -and $_.Domain -eq $env:COMPUTERNAME }).Count -gt 0",
  "    } catch {",
  "        $probed = $false",
  "        Write-Host ('jusshin: could not tell whether {0} is signed in ({1}); the logon tasks are registered but not started.' -f $Identity, $_.Exception.Message)",
  "    }",
  "    $down = 0",
  "    $waiting = 0",
  "    foreach ($runner in $Runners) {",
  "        $taskName = $TaskPrefix + $runner.Name",
  "        if (-not (Test-Path -LiteralPath (Join-Path $runner.Dir '.runner'))) {",
  "            Write-Host ('jusshin: {0} is not configured in {1}; no logon task registered for it.' -f $runner.Name, $runner.Dir)",
  "            $down++",
  "            continue",
  "        }",
  "        # A folder an earlier service-mode run configured is still a service: a",
  "        # logon task beside it would be a second listener for one runner.",
  "        if ($null -ne (Get-Service -Name $taskName -ErrorAction SilentlyContinue)) {",
  "            Write-Host ('jusshin: {0} is installed as the service {1}; no logon task registered. Remove that runner (config.cmd remove) and re-run.' -f $runner.Name, $taskName)",
  "            $down++",
  "            continue",
  "        }",
  "        # Reset the folder to the locked root's inherited baseline FIRST, so an",
  "        # account an earlier run granted (a different identity) keeps no access",
  "        # to run.cmd, _work or the runner's credentials. Then grant this one.",
  "        $code = Invoke-Quiet 'icacls' @($runner.Dir, '/reset', '/T', '/C', '/Q')",
  "        if ($code -ne 0) {",
  "            Write-Host ('jusshin: icacls could not reset {0} to the root''s baseline (exit {1}); no logon task registered.' -f $runner.Dir, $code)",
  "            $down++",
  "            continue",
  "        }",
  "        $code = Invoke-Quiet 'icacls' @($runner.Dir, '/grant', ('{0}:(OI)(CI)M' -f $Account))",
  "        if ($code -ne 0) {",
  "            Write-Host ('jusshin: icacls could not grant {0} Modify on {1} (exit {2}); no logon task registered.' -f $Account, $runner.Dir, $code)",
  "            $down++",
  "            continue",
  "        }",
  "        try {",
  "            # Interactive token: the task runs only in the identity's own desktop",
  "            # session, so no password is asked or stored. No time limit; restarted",
  "            # every minute (up to 255 times) when the task ends in failure -- a",
  "            # sign-out is not a failure; one instance at a time; priority 4, normal",
  "            # (the default 7 is below normal, and every job would inherit it).",
  "            $action = New-ScheduledTaskAction -Execute (Join-Path $runner.Dir 'run.cmd') -WorkingDirectory $runner.Dir",
  "            $trigger = New-ScheduledTaskTrigger -AtLogOn -User $TaskUser",
  "            $principal = New-ScheduledTaskPrincipal -UserId $TaskUser -LogonType Interactive -RunLevel Limited",
  "            $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 255 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew -Priority 4 -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable",
  "            Register-ScheduledTask -TaskName $taskName -TaskPath '\\' -Action $action -Trigger $trigger -Principal $principal -Settings $settings -Description ('GitHub Actions runner {0} for {1}, in {2}''s desktop session. Rendered by nen runner script.' -f $runner.Name, $Target, $Identity) -Force | Out-Null",
  "        } catch {",
  "            Write-Host ('jusshin: could not register the logon task {0}: {1}' -f $taskName, $_.Exception.Message)",
  "            $down++",
  "            continue",
  "        }",
  "        Write-Host ('jusshin: {0} registered (at logon of {1}, {2} Modify on {3}).' -f $taskName, $TaskUser, $Account, $runner.Dir)",
  "        if (-not $signedIn) {",
  "            $waiting++",
  "            continue",
  "        }",
  "        if ((Get-ScheduledTask -TaskName $taskName -TaskPath '\\').State -ne 'Running') {",
  "            try {",
  "                Start-ScheduledTask -TaskName $taskName -TaskPath '\\'",
  "            } catch {",
  "                Write-Host ('jusshin: {0} did not start: {1}' -f $taskName, $_.Exception.Message)",
  "            }",
  "            $deadline = (Get-Date).AddSeconds(30)",
  "            while ((Get-Date) -lt $deadline -and (Get-ScheduledTask -TaskName $taskName -TaskPath '\\').State -ne 'Running') { Start-Sleep -Seconds 2 }",
  "        }",
  "        $state = (Get-ScheduledTask -TaskName $taskName -TaskPath '\\').State",
  "        if ($state -ne 'Running') {",
  "            Write-Host ('jusshin: {0} is {1} although {2} is signed in.' -f $taskName, $state, $Account)",
  "            $down++",
  "        }",
  "    }",
  "    Get-ScheduledTask -TaskPath '\\' -ErrorAction SilentlyContinue | Where-Object { $_.TaskName -like ($TaskPrefix + '*') } | Sort-Object TaskName | Format-Table -AutoSize TaskName, State | Out-String -Width 200 | Write-Host",
  "    if ($waiting -gt 0 -and $probed) {",
  "        Write-Host ('jusshin: {0} is not signed in, so {1} logon task(s) wait: the runners come online when {0} signs in to the desktop (or is auto-logged on; this script never configures that). A UI job needs that session active and unlocked, and the run.cmd console window open.' -f $Identity, $waiting)",
  "    }",
  "",
  "    if ($down -eq 0 -and $script:Failed -eq 0) { Close-Run 0 }",
  "    Close-Run 1",
];

// ── Linux and macOS ─────────────────────────────────────────────────────────

function posixPreamble(plan: RunnerPlan, version: string, what: string, runAs: string): string[] {
  const [owner, repo] = plan.target.split("/") as [string, string];
  return [
    "#!/usr/bin/env bash",
    ...header(plan, version, "#", "—", what),
    "#",
    ...runAs.split("\n").map((line): string => `# ${line}`.trimEnd()),
    "#",
    "# Exit codes: 0 every planned runner's service is running; 1 anything else;",
    "# 3 run as the wrong user; 5 gh missing or not signed in; 6 the runner",
    "# package failed its SHA-256 check (the file is deleted). The one summary",
    "# line is also written to $PROJECT_DIR/_jusshin/register-<ts>.summary.",
    "set -euo pipefail",
    "",
    `TARGET=${sh(plan.target)}`,
    `REPO_URL=${sh(`https://github.com/${plan.target}`)}`,
    `LABELS=${sh(plan.labels.join(","))}`,
    `ROOT=${sh(plan.root)}`,
    `PROJECT_DIR=${sh(plan.projectDir)}`,
    `DOWNLOAD_URL=${sh(plan.download.download_url)}`,
    `ARCHIVE=${sh(plan.download.filename)}`,
    `SHA256=${sh(plan.download.sha256_checksum.toLowerCase())}`,
    `SERVICE_PREFIX=${sh(`actions.runner.${owner}-${repo}.`)}`,
    "RUNNERS=(",
    ...plan.runners.map((runner): string => `  ${sh(`${runner.name}|${runner.installDir}`)}`),
    ")",
    'WORK_DIR="$PROJECT_DIR/_jusshin"',
    "registered=0",
    "skipped=0",
    "failed=0",
    'stamp="$(date +%Y%m%d-%H%M%S)"',
    'summary_file=""',
    "",
    "# The summary file carries the ONE summary line and nothing else: it is what",
    "# the caller reads. The log is the maintainer's.",
    "finish() {",
    '  summary="jusshin: ${registered} registered, ${skipped} skipped, ${failed} failed"',
    '  echo "$summary"',
    `  if [ -n "$summary_file" ]; then printf '%s\\n' "$summary" > "$summary_file" || true; fi`,
    '  exit "$1"',
    "}",
    "",
    "# Whether a runner directory is already configured as NAME (idempotent re-run).",
    "configured_as() {",
    '  [ -f "$1/.runner" ] && grep -q "\\"agentName\\": *\\"$2\\"" "$1/.runner"',
    "}",
    "",
    "# Why a directory configured as NAME is stale, or nothing when it stands: its",
    "# service is absent ($2 is not 1), or GitHub no longer lists its registration",
    "# ($3, one name per line) (#319).",
    "stale_reason() {",
    '  local reasons=""',
    '  if [ "$2" != 1 ]; then reasons="its service is absent"; fi',
    "  # A here-string, never a pipe: under pipefail, grep -q exiting on an early",
    "  # match would SIGPIPE a long printf and read a listed name as unlisted.",
    "  if ! grep -Fxq -- \"$1\" <<<\"$3\"; then",
    '    reasons="${reasons:+$reasons and }GitHub no longer lists its registration"',
    "  fi",
    "  printf '%s' \"$reasons\"",
    "}",
    "",
    "# The names GitHub lists for the repository's runners, read once into",
    "# $listed; $listed_ok is 1 when the read succeeded.",
    'listed=""',
    'listed_ok=""',
    "read_listed() {",
    '  if [ -n "$listed_ok" ]; then return 0; fi',
    "  if listed=\"$(gh_run api --paginate \"repos/$TARGET/actions/runners\" --jq '.runners[].name' 2>/dev/null)\"; then listed_ok=1; else listed_ok=0; fi",
    "}",
    "",
    "# Stop and uninstall a stale runner's service from its own directory.",
    "remove_service() {",
    "  # A stop that fails is a failure: deleting a directory under a live listener",
    "  # is the one thing this must not do.",
    '  (cd "$1" && ./svc.sh stop && ./svc.sh uninstall)',
    "}",
    "",
  ];
}

function posixDownload(checker: string): string[] {
  return [
    'archive="$WORK_DIR/$ARCHIVE"',
    "verify_archive() {",
    `  echo "$SHA256  $archive" | ${checker} >/dev/null 2>&1`,
    "}",
    "if [ \"${#pending[@]}\" -gt 0 ]; then",
    '  if [ ! -f "$archive" ] || ! verify_archive; then',
    '    echo "jusshin: downloading $ARCHIVE"',
    '    curl -fsSL -o "$archive" "$DOWNLOAD_URL"',
    "    if ! verify_archive; then",
    '      rm -f "$archive"',
    '      echo "jusshin: $ARCHIVE failed its SHA-256 check (expected $SHA256) -- deleted."',
    "      finish 6",
    "    fi",
    "  fi",
    '  echo "jusshin: $ARCHIVE verified (sha256 $SHA256)."',
    "fi",
    "",
  ];
}

const POSIX_PENDING = [
  "pending=()",
  'replace_names=" "',
  'for entry in "${RUNNERS[@]}"; do',
  '  name="${entry%%|*}"',
  '  dir="${entry#*|}"',
  '  if configured_as "$dir" "$name"; then',
  "    # Configured is not standing (#319): a failed service install leaves .runner",
  "    # behind with no service, and a removed registration leaves one GitHub no",
  "    # longer lists. Either is stale -- emptied and re-registered, never skipped.",
  "    read_listed",
  '    if [ "$listed_ok" != 1 ]; then',
  "      echo \"jusshin: could not list the runners of $TARGET, so $name in $dir cannot be told live from stale -- left untouched (the gh user must be an admin of $TARGET).\"",
  "      failed=$((failed + 1))",
  "      continue",
  "    fi",
  '    if ! has_service="$(service_present "$name")"; then',
  '      echo "jusshin: the service state of $name could not be read, so $dir cannot be told live from stale -- left untouched."',
  "      failed=$((failed + 1))",
  "      continue",
  "    fi",
  '    reason="$(stale_reason "$name" "$has_service" "$listed")"',
  '    if [ -z "$reason" ]; then',
  '      echo "jusshin: $name is already configured in $dir -- skipped."',
  "      skipped=$((skipped + 1))",
  "      continue",
  "    fi",
  '    echo "jusshin: $name in $dir is stale ($reason) -- emptied and re-registered."',
  '    if [ "$has_service" = 1 ] && ! remove_service "$dir"; then',
  '      echo "jusshin: svc.sh could not stop or uninstall the stale service for $name; $dir left untouched."',
  "      failed=$((failed + 1))",
  "      continue",
  "    fi",
  "    # Under set -e a bare rm that fails would end the run with no summary: a",
  "    # directory that cannot be emptied fails this runner alone.",
  '    if ! rm -rf "$dir"; then',
  '      echo "jusshin: could not empty $dir for $name."',
  "      failed=$((failed + 1))",
  "      continue",
  "    fi",
  "    # A stale runner GitHub still lists is replaced under its own name.",
  "    if grep -Fxq -- \"$name\" <<<\"$listed\"; then replace_names=\"$replace_names$name \"; fi",
  '    pending+=("$entry")',
  "    continue",
  "  fi",
  '  if [ -f "$dir/.runner" ]; then',
  '    echo "jusshin: $dir holds a runner configured as another name, not $name -- left untouched."',
  "    failed=$((failed + 1))",
  "    continue",
  "  fi",
  '  pending+=("$entry")',
  "done",
  "",
];

export function renderLinux(plan: RunnerPlan, version: string): string {
  return [
    ...posixPreamble(
      plan,
      version,
      "as systemd services",
      "Run it as root, through sudo from your own account: sudo bash <this file>.\nconfig.sh runs as the service user (it refuses root), gh runs as YOU\n(SUDO_USER, with your own sign-in), and svc.sh installs the systemd unit as\nroot. The registration token is minted per runner into a variable that is\nnever printed, and reaches config.sh through its environment, never argv.\nKeep this file outside the runner root (e.g. ~/.local/state/nen/jusshin/).",
    ),
    `SERVICE_USER=${sh(plan.identity)}`,
    "",
    'if [ "$(id -u)" -ne 0 ]; then',
    '  echo "jusshin: run as root (sudo bash $0) -- this script installs systemd services."',
    "  finish 3",
    "fi",
    'if [ -z "${SUDO_USER:-}" ] || [ "$SUDO_USER" = root ]; then',
    '  echo "jusshin: run through sudo from your own account -- gh runs as that account (SUDO_USER), with its own sign-in."',
    "  finish 3",
    "fi",
    'as_invoker() { sudo -u "$SUDO_USER" -H "$@"; }',
    'gh_run() { as_invoker gh "$@"; }',
    "# Prints 1 (the unit exists) or 0 (systemd says not-found); a read that fails",
    "# returns nonzero, so an unreadable state is never taken for an absent one.",
    "service_present() {",
    "  local state",
    '  state="$(systemctl show -p LoadState --value "${SERVICE_PREFIX}$1.service" 2>/dev/null)" || return 1',
    '  case "$state" in not-found) echo 0 ;; "") return 1 ;; *) echo 1 ;; esac',
    "}",
    "if ! as_invoker gh --version >/dev/null 2>&1; then",
    '  echo "jusshin: gh is not on PATH for $SUDO_USER. Install the GitHub CLI and re-run."',
    "  finish 5",
    "fi",
    "if ! as_invoker gh auth status >/dev/null 2>&1; then",
    "  echo \"jusshin: 'gh auth status' failed for $SUDO_USER. Run 'gh auth login' and re-run.\"",
    "  finish 5",
    "fi",
    'if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then',
    '  echo "jusshin: the service user $SERVICE_USER does not exist. Create it (useradd --system --create-home $SERVICE_USER) and re-run."',
    "  finish 1",
    "fi",
    "",
    'mkdir -p "$ROOT" "$PROJECT_DIR" "$WORK_DIR"',
    'chmod 0755 "$ROOT" "$PROJECT_DIR"',
    'log="$WORK_DIR/register-$stamp.log"',
    'summary_file="$WORK_DIR/register-$stamp.summary"',
    'exec > >(tee -a "$log") 2>&1',
    'echo "jusshin: ${#RUNNERS[@]} runner(s) for $TARGET; log $log"',
    "",
    ...POSIX_PENDING,
    ...posixDownload("sha256sum -c -"),
    'for entry in "${pending[@]+"${pending[@]}"}"; do',
    '  name="${entry%%|*}"',
    '  dir="${entry#*|}"',
    '  echo "jusshin: registering $name in $dir"',
    '  install -d -o "$SERVICE_USER" -m 0755 "$dir"',
    "  # Re-hashed immediately before EVERY extraction, not only after the download.",
    "  if ! verify_archive; then",
    '    rm -f "$archive"',
    '    echo "jusshin: $ARCHIVE no longer matches sha256 $SHA256 -- deleted; nothing extracted into $dir."',
    "    finish 6",
    "  fi",
    '  sudo -u "$SERVICE_USER" tar xzf "$archive" -C "$dir"',
    '  token="$(as_invoker gh api -X POST "repos/$TARGET/actions/runners/registration-token" --jq .token 2>/dev/null)" || token=""',
    '  if [ -z "$token" ]; then',
    '    echo "jusshin: could not mint a registration token for $name; the gh user must be an admin of $TARGET."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  # NO TOKEN ON A COMMAND LINE (/proc/<pid>/cmdline is world-readable): it",
    "  # reaches config.sh as ACTIONS_RUNNER_INPUT_TOKEN, which actions/runner reads",
    "  # as its --token input. printf is a builtin (no argv), and the service user's",
    "  # shell reads it from stdin into its own environment -- sudo would strip an",
    "  # inherited variable, and 'env VAR=...' would put it back on argv.",
    "  replace=()",
    '  case "$replace_names" in *" $name "*) replace=(--replace) ;; esac',
    `  if ! (cd "$dir" && printf '%s\\n' "$token" | sudo -u "$SERVICE_USER" bash -c 'IFS= read -r ACTIONS_RUNNER_INPUT_TOKEN; export ACTIONS_RUNNER_INPUT_TOKEN; exec ./config.sh --unattended --url "$1" --name "$2" --labels "$3" --work _work "\${@:4}"' jusshin "$REPO_URL" "$name" "$LABELS" \${replace[@]+"\${replace[@]}"}); then`,
    '    token=""',
    '    echo "jusshin: config.sh failed for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  token=""',
    '  if ! (cd "$dir" && ./svc.sh install "$SERVICE_USER" && ./svc.sh start && ./svc.sh status); then',
    '    echo "jusshin: svc.sh could not install or start the service for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  registered=$((registered + 1))",
    "done",
    "",
    "down=0",
    'for entry in "${RUNNERS[@]}"; do',
    '  name="${entry%%|*}"',
    '  if ! systemctl is-active --quiet "${SERVICE_PREFIX}${name}.service"; then',
    '    echo "jusshin: ${SERVICE_PREFIX}${name}.service is not active."',
    "    down=$((down + 1))",
    "  fi",
    "done",
    'systemctl list-units "${SERVICE_PREFIX}*" --all --no-pager || true',
    "",
    'if [ "$down" -eq 0 ] && [ "$failed" -eq 0 ]; then finish 0; fi',
    "finish 1",
    "",
  ].join("\n");
}

export function renderMac(plan: RunnerPlan, version: string): string {
  return [
    ...posixPreamble(
      plan,
      version,
      "as launchd agents",
      "Run it as YOURSELF, not with sudo: bash <this file>. A macOS runner is a\nLaunchAgent of the user who installs it. The registration token is minted\nper runner into a variable that is never printed, and reaches config.sh\nthrough its environment, never argv. Keep this file outside the runner root\n(e.g. ~/.local/state/nen/jusshin/).",
    ),
    'if [ "$(id -u)" -eq 0 ]; then',
    '  echo "jusshin: run as yourself, not root -- a macOS runner is a LaunchAgent of the user who installs it."',
    "  finish 3",
    "fi",
    'gh_run() { gh "$@"; }',
    'service_present() { if [ -f "$HOME/Library/LaunchAgents/${SERVICE_PREFIX}$1.plist" ]; then echo 1; else echo 0; fi; }',
    "if ! gh --version >/dev/null 2>&1; then",
    '  echo "jusshin: gh is not on PATH. Install the GitHub CLI and re-run."',
    "  finish 5",
    "fi",
    "if ! gh auth status >/dev/null 2>&1; then",
    "  echo \"jusshin: 'gh auth status' failed. Run 'gh auth login' and re-run.\"",
    "  finish 5",
    "fi",
    "",
    'mkdir -p "$ROOT" "$PROJECT_DIR" "$WORK_DIR"',
    'log="$WORK_DIR/register-$stamp.log"',
    'summary_file="$WORK_DIR/register-$stamp.summary"',
    'exec > >(tee -a "$log") 2>&1',
    'echo "jusshin: ${#RUNNERS[@]} runner(s) for $TARGET; log $log"',
    "",
    ...POSIX_PENDING,
    ...posixDownload("shasum -a 256 -c -"),
    'for entry in "${pending[@]+"${pending[@]}"}"; do',
    '  name="${entry%%|*}"',
    '  dir="${entry#*|}"',
    '  echo "jusshin: registering $name in $dir"',
    '  mkdir -p "$dir"',
    "  # Re-hashed immediately before EVERY extraction, not only after the download.",
    "  if ! verify_archive; then",
    '    rm -f "$archive"',
    '    echo "jusshin: $ARCHIVE no longer matches sha256 $SHA256 -- deleted; nothing extracted into $dir."',
    "    finish 6",
    "  fi",
    '  tar xzf "$archive" -C "$dir"',
    '  token="$(gh api -X POST "repos/$TARGET/actions/runners/registration-token" --jq .token 2>/dev/null)" || token=""',
    '  if [ -z "$token" ]; then',
    '    echo "jusshin: could not mint a registration token for $name; the gh user must be an admin of $TARGET."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  # NO TOKEN ON A COMMAND LINE: it reaches config.sh as ACTIONS_RUNNER_INPUT_TOKEN,",
    "  # which actions/runner reads as its --token input; a prefix assignment is",
    "  # never part of argv.",
    "  replace=()",
    '  case "$replace_names" in *" $name "*) replace=(--replace) ;; esac',
    '  if ! (cd "$dir" && ACTIONS_RUNNER_INPUT_TOKEN="$token" ./config.sh --unattended --url "$REPO_URL" --name "$name" --labels "$LABELS" --work _work ${replace[@]+"${replace[@]}"}); then',
    '    token=""',
    '    echo "jusshin: config.sh failed for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  token=""',
    '  if ! (cd "$dir" && ./svc.sh install && ./svc.sh start); then',
    '    echo "jusshin: svc.sh could not install or start the LaunchAgent for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  registered=$((registered + 1))",
    "done",
    "",
    "# Background Task Management: a LaunchAgent macOS has not approved is loaded",
    "# with no PID ('-' in launchctl list). It is held pending approval under",
    "# System Settings > General > Login Items; this script never approves it.",
    "down=0",
    'for entry in "${RUNNERS[@]}"; do',
    '  name="${entry%%|*}"',
    '  label="${SERVICE_PREFIX}${name}"',
    '  launchctl print "gui/$(id -u)/$label" 2>/dev/null | grep -E "^[[:space:]]*(state|pid) =" || true',
    '  pid="$(launchctl list | while read -r p _ l; do if [ "$l" = "$label" ]; then echo "$p"; fi; done)"',
    '  if [ -z "$pid" ] || [ "$pid" = "-" ]; then',
    '    echo "jusshin: $label has no PID -- if it is listed, it is held pending approval under System Settings > General > Login Items (approve it there; nen never does)."',
    "    down=$((down + 1))",
    "  fi",
    "done",
    "",
    'if [ "$down" -eq 0 ] && [ "$failed" -eq 0 ]; then finish 0; fi',
    "finish 1",
    "",
  ].join("\n");
}

/** Render the plan's host script. The plan has already passed `validatePlan`. */
export function renderScript(plan: RunnerPlan, version: string): RenderedScript {
  if (plan.os === "Windows") return { os: plan.os, text: renderWindows(plan, version), needsElevation: true };
  if (plan.os === "Linux") return { os: plan.os, text: renderLinux(plan, version), needsElevation: true };
  return { os: plan.os, text: renderMac(plan, version), needsElevation: false };
}

/** The one command line the caller runs the script with. */
export function launchLine(os: RunnerPlan["os"], out: string): string {
  if (os === "Windows") {
    return `powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process powershell -Verb RunAs -Wait -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File','${out}'"`;
  }
  if (os === "Linux") return `sudo bash ${out}`;
  return `bash ${out}`;
}
