// src/runner/script.ts -- `nen runner script`: the HOST script that registers a
// plan's runners as boot-persistent services, rendered deterministically, one
// per operating system.
//
// NEN RENDERS; NEN NEVER RUNS IT. The script registers Windows services, grants
// folder rights and asks for a service account's password -- every one of
// those is an act on the maintainer's machine that the maintainer consents to
// (a UAC prompt on Windows, their own `sudo` on Linux). So the verb's whole
// output is a file and the ONE command line that launches it; running that
// line is the caller's, and on Windows the elevation is the human's.
//
// THE SECRETS NEVER PASS THROUGH NEN. The registration token is minted INSIDE
// the script, by `gh`, at the moment `config` needs it, into a variable that
// is never printed; the Windows account password is typed ONCE into
// `Read-Host -AsSecureString`, turned into plain text only for the one
// `config.cmd` call (config.cmd's own contract takes it as an argument), and
// cleared after. The transcript is STOPPED around that call and restarted
// after it, and `config.cmd`'s own output is replayed into it with both
// secrets replaced by `***`. Nothing here writes, logs or echoes either one.
//
// DETERMINISTIC TO THE BYTE. No timestamp, no host name, no random value is
// rendered: the transcript's own file name is computed by the SCRIPT when it
// runs. The version in the header is a parameter so the golden files
// (./fixtures/*.golden) survive a release.
//
// POWERSHELL 5.1, NOT 7. The Windows host this was built for has no `pwsh`, and
// a runner host is exactly the machine nobody has provisioned yet: no `&&`, no
// `??`, no ternary, ASCII only (5.1 reads a BOM-less file as the ANSI code page,
// so an em dash in the header would render as mojibake -- the bash scripts
// carry it, the .ps1 writes `--`). Native commands run with
// `$ErrorActionPreference = 'Continue'` around them, because under 'Stop' a
// 5.1 host turns any stderr line of a native program into a terminating error.

import type { RunnerPlan } from "./plan.js";
import { NETWORK_SERVICE } from "./plan.js";

export interface RenderedScript {
  readonly os: RunnerPlan["os"];
  readonly text: string;
  readonly needsElevation: boolean;
}

/** A PowerShell single-quoted literal. Plan values are validated to carry no quote; this is the second belt. */
function ps(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/** A bash single-quoted literal, same reasoning. */
function sh(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

function header(plan: RunnerPlan, version: string, comment: string, dash: string, what: string): string[] {
  return [
    `${comment} jusshin ${dash} register self-hosted GitHub Actions runners ${what}.`,
    `${comment} rendered by nen ${version} runner script ${dash} do not edit; re-run nen runner script`,
    `${comment}`,
    `${comment} target:   ${plan.target}`,
    `${comment} pool:     ${plan.pool} (${plan.labels.join(",")})`,
    `${comment} runners:  ${plan.runners.map((runner): string => runner.name).join(", ")}`,
    `${comment} identity: ${plan.identity}`,
    `${comment} root:     ${plan.root}`,
    `${comment} package:  ${plan.download.filename} (runner ${plan.runnerVersion})`,
  ];
}

// ── Windows ─────────────────────────────────────────────────────────────────

export function renderWindows(plan: RunnerPlan, version: string): string {
  const account = plan.identity === NETWORK_SERVICE ? "" : plan.identity.slice(2);
  const [owner, repo] = plan.target.split("/") as [string, string];
  const runners = plan.runners.map(
    (runner, index): string =>
      `    @{ Name = ${ps(runner.name)}; Dir = ${ps(runner.installDir)} }${index === plan.runners.length - 1 ? "" : ","}`,
  );
  return [
    ...header(plan, version, "#", "--", "as Windows services"),
    "#",
    "# Windows PowerShell 5.1. Run it ELEVATED: 'nen runner script --json' prints",
    "# the one launch line, which opens it through a UAC prompt. It asks ONCE for",
    "# the service account's password. That password, and every registration",
    "# token this script mints with gh, live only in this process: never echoed,",
    "# never written to a file, and the transcript is stopped around the one",
    "# config.cmd call that carries them.",
    "#",
    "# Exit codes: 0 every planned runner's service is Running; 1 anything else;",
    "# 3 not elevated; 5 gh missing or not signed in; 6 the runner package failed",
    "# its SHA-256 check (the file is deleted).",
    "",
    "$ErrorActionPreference = 'Stop'",
    "$ProgressPreference = 'SilentlyContinue'",
    "",
    `$Target = ${ps(plan.target)}`,
    `$RepoUrl = ${ps(`https://github.com/${plan.target}`)}`,
    `$Labels = ${ps(plan.labels.join(","))}`,
    `$Root = ${ps(plan.root)}`,
    `$ProjectDir = ${ps(plan.projectDir)}`,
    `$Identity = ${ps(plan.identity)}`,
    `$Account = ${ps(account)}`,
    `$DownloadUrl = ${ps(plan.download.download_url)}`,
    `$ZipName = ${ps(plan.download.filename)}`,
    `$Sha256 = ${ps(plan.download.sha256_checksum.toUpperCase())}`,
    `$ServicePrefix = ${ps(`actions.runner.${owner}-${repo}.`)}`,
    "$Runners = @(",
    ...runners,
    ")",
    "",
    "$WorkDir = Join-Path $ProjectDir '_jusshin'",
    "$script:Registered = 0",
    "$script:Skipped = 0",
    "$script:Failed = 0",
    "$script:Transcribing = $false",
    "$script:LogPath = $null",
    "",
    "function Close-Run {",
    "    param([int]$Code)",
    "    Write-Host ('jusshin: {0} registered, {1} skipped, {2} failed' -f $script:Registered, $script:Skipped, $script:Failed)",
    "    if ($script:Transcribing) {",
    "        Stop-Transcript | Out-Null",
    "        $script:Transcribing = $false",
    "    }",
    "    # Keep the elevated window open on a failure, so its lines can be read.",
    "    if ($Code -ne 0 -and $Host.Name -eq 'ConsoleHost' -and [Environment]::UserInteractive) {",
    "        Read-Host 'press Enter to close' | Out-Null",
    "    }",
    "    exit $Code",
    "}",
    "",
    "# A native command, its output discarded, its exit code returned.",
    "function Invoke-Quiet {",
    "    param([string]$FilePath, [string[]]$ArgumentList)",
    "    $previous = $ErrorActionPreference",
    "    $ErrorActionPreference = 'Continue'",
    "    try {",
    "        & $FilePath @ArgumentList *> $null",
    "        return $LASTEXITCODE",
    "    } finally {",
    "        $ErrorActionPreference = $previous",
    "    }",
    "}",
    "",
    "# Replace every secret in a line with ***. An empty secret replaces nothing.",
    "function Hide-Secret {",
    "    param([string]$Text, [string[]]$Secrets)",
    "    foreach ($secret in $Secrets) {",
    "        if (-not [string]::IsNullOrEmpty($secret)) { $Text = $Text.Replace($secret, '***') }",
    "    }",
    "    return $Text",
    "}",
    "",
    "function Start-Log {",
    "    Start-Transcript -Path $script:LogPath -Append | Out-Null",
    "    $script:Transcribing = $true",
    "}",
    "",
    "function Stop-Log {",
    "    if ($script:Transcribing) {",
    "        Stop-Transcript | Out-Null",
    "        $script:Transcribing = $false",
    "    }",
    "}",
    "",
    "try {",
    "    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())",
    "    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {",
    "        Write-Host 'jusshin: run elevated -- this script registers Windows services and grants folder rights.'",
    "        Close-Run 3",
    "    }",
    "",
    "    foreach ($dir in @($Root, $ProjectDir, $WorkDir)) {",
    "        if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }",
    "    }",
    "    $script:LogPath = Join-Path $WorkDir ('register-{0}.log' -f (Get-Date -Format 'yyyyMMdd-HHmmss'))",
    "    Start-Log",
    "    Write-Host ('jusshin: {0} runner(s) for {1}; transcript {2}' -f $Runners.Count, $Target, $script:LogPath)",
    "",
    "    if ($null -eq (Get-Command gh -ErrorAction SilentlyContinue)) {",
    "        Write-Host 'jusshin: gh is not on PATH for this elevated shell. Install the GitHub CLI machine-wide and re-run.'",
    "        Close-Run 5",
    "    }",
    "    if ((Invoke-Quiet 'gh' @('auth', 'status')) -ne 0) {",
    "        Write-Host \"jusshin: 'gh auth status' failed in this elevated shell. Run 'gh auth login' as this user and re-run.\"",
    "        Close-Run 5",
    "    }",
    "",
    "    # Traverse rights for a local-account service: read-and-execute on the root",
    "    # and the project folder, THIS FOLDER ONLY (no inheritance). config.cmd grants",
    "    # the leaf Runner<N> folders itself. icacls /grant is idempotent.",
    "    if ($Account -ne '') {",
    "        foreach ($dir in @($Root, $ProjectDir)) {",
    "            $code = Invoke-Quiet 'icacls' @($dir, '/grant', ('{0}:(RX)' -f $Account))",
    "            if ($code -ne 0) {",
    "                Write-Host ('jusshin: icacls could not grant {0} read-and-execute on {1} (exit {2}).' -f $Account, $dir, $code)",
    "                Close-Run 1",
    "            }",
    "            Write-Host ('jusshin: {0} may traverse {1} (RX, this folder only).' -f $Account, $dir)",
    "        }",
    "    }",
    "",
    "    $pending = @()",
    "    foreach ($runner in $Runners) {",
    "        $marker = Join-Path $runner.Dir '.runner'",
    "        if (Test-Path -LiteralPath $marker) {",
    "            $agent = $null",
    "            try { $agent = (Get-Content -LiteralPath $marker -Raw | ConvertFrom-Json).agentName } catch { $agent = $null }",
    "            if ($agent -eq $runner.Name) {",
    "                Write-Host ('jusshin: {0} is already configured in {1} -- skipped.' -f $runner.Name, $runner.Dir)",
    "                $script:Skipped++",
    "                continue",
    "            }",
    "            Write-Host ('jusshin: {0} holds a runner configured as {1}, not {2} -- left untouched.' -f $runner.Dir, $agent, $runner.Name)",
    "            $script:Failed++",
    "            continue",
    "        }",
    "        $pending += $runner",
    "    }",
    "",
    "    $secure = $null",
    "    if ($pending.Count -gt 0 -and $Account -ne '') {",
    "        $secure = Read-Host -AsSecureString ('Password for {0} (asked once; never shown, never written)' -f $Identity)",
    "    }",
    "",
    "    $zip = Join-Path $WorkDir $ZipName",
    "    if ($pending.Count -gt 0) {",
    "        $have = $false",
    "        if (Test-Path -LiteralPath $zip) { $have = ((Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash -eq $Sha256) }",
    "        if (-not $have) {",
    "            [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12",
    "            Write-Host ('jusshin: downloading {0}' -f $ZipName)",
    "            Invoke-WebRequest -Uri $DownloadUrl -OutFile $zip -UseBasicParsing",
    "            $actual = (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash",
    "            if ($actual -ne $Sha256) {",
    "                Remove-Item -LiteralPath $zip -Force",
    "                Write-Host ('jusshin: {0} failed its SHA-256 check (expected {1}, got {2}) -- deleted.' -f $ZipName, $Sha256, $actual)",
    "                Close-Run 6",
    "            }",
    "        }",
    "        Write-Host ('jusshin: {0} verified (sha256 {1}).' -f $ZipName, $Sha256)",
    "    }",
    "",
    "    foreach ($runner in $pending) {",
    "        $name = $runner.Name",
    "        $dir = $runner.Dir",
    "        Write-Host ('jusshin: registering {0} in {1}' -f $name, $dir)",
    "        if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }",
    "        Expand-Archive -LiteralPath $zip -DestinationPath $dir -Force",
    "",
    "        # A fresh registration token, minted NOW (it lives about an hour), into a",
    "        # variable that is never printed.",
    "        $token = $null",
    "        $mint = 1",
    "        $previous = $ErrorActionPreference",
    "        $ErrorActionPreference = 'Continue'",
    "        try {",
    "            $token = [string](& gh api -X POST ('repos/{0}/actions/runners/registration-token' -f $Target) --jq .token 2> $null)",
    "            $mint = $LASTEXITCODE",
    "        } finally {",
    "            $ErrorActionPreference = $previous",
    "        }",
    "        if ($mint -ne 0 -or [string]::IsNullOrWhiteSpace($token)) {",
    "            Write-Host ('jusshin: could not mint a registration token for {0} (gh exit {1}); the gh user must be an admin of {2}.' -f $name, $mint, $Target)",
    "            $token = $null",
    "            $script:Failed++",
    "            continue",
    "        }",
    "",
    "        $configArgs = @('--unattended', '--url', $RepoUrl, '--token', $token, '--name', $name, '--labels', $Labels, '--work', '_work', '--runasservice')",
    "        if ($Account -ne '') { $configArgs += @('--windowslogonaccount', $Identity) }",
    "        $plain = $null",
    "        $bstr = [IntPtr]::Zero",
    "        $lines = @()",
    "        $code = 1",
    "        # The transcript stops HERE: the argument list below carries the token and",
    "        # the password. It restarts after, and config.cmd's output is replayed into",
    "        # it with both replaced by ***.",
    "        Stop-Log",
    "        try {",
    "            if ($Account -ne '') {",
    "                $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)",
    "                $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)",
    "                $configArgs += @('--windowslogonpassword', $plain)",
    "            }",
    "            Push-Location -LiteralPath $dir",
    "            $previous = $ErrorActionPreference",
    "            $ErrorActionPreference = 'Continue'",
    "            try {",
    "                $lines = @(& .\\config.cmd @configArgs 2>&1 | ForEach-Object { Hide-Secret ([string]$_) @($token, $plain) })",
    "                $code = $LASTEXITCODE",
    "            } finally {",
    "                $ErrorActionPreference = $previous",
    "                Pop-Location",
    "            }",
    "        } finally {",
    "            if ($bstr -ne [IntPtr]::Zero) { [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr) }",
    "            $plain = $null",
    "            $token = $null",
    "            $configArgs = $null",
    "            Start-Log",
    "        }",
    "        foreach ($line in $lines) { Write-Host ('  config: {0}' -f $line) }",
    "        if ($code -ne 0) {",
    "            Write-Host ('jusshin: config.cmd exited {0} for {1}.' -f $code, $name)",
    "            $script:Failed++",
    "            continue",
    "        }",
    "        $script:Registered++",
    "    }",
    "    if ($null -ne $secure) { $secure.Dispose() }",
    "",
    "    # Every planned runner's service must be Running -- skipped ones included;",
    "    # a stopped one is started once (a service inherits PATH only at start).",
    "    $down = 0",
    "    foreach ($runner in $Runners) {",
    "        $serviceName = $ServicePrefix + $runner.Name",
    "        $service = Get-Service -Name $serviceName -ErrorAction SilentlyContinue",
    "        if ($null -eq $service) {",
    "            Write-Host ('jusshin: no service {0}.' -f $serviceName)",
    "            $down++",
    "            continue",
    "        }",
    "        if ($service.Status -ne 'Running') {",
    "            try {",
    "                Start-Service -Name $serviceName",
    "                $service.WaitForStatus('Running', [TimeSpan]::FromSeconds(30))",
    "            } catch {",
    "                Write-Host ('jusshin: {0} did not start: {1}' -f $serviceName, $_.Exception.Message)",
    "            }",
    "            $service = Get-Service -Name $serviceName",
    "        }",
    "        if ($service.Status -ne 'Running') {",
    "            Write-Host ('jusshin: {0} is {1}.' -f $serviceName, $service.Status)",
    "            $down++",
    "        }",
    "    }",
    "    Get-Service -Name ($ServicePrefix + '*') -ErrorAction SilentlyContinue | Sort-Object Name | Format-Table -AutoSize Name, Status, StartType | Out-String -Width 200 | Write-Host",
    "",
    "    if ($down -eq 0 -and $script:Failed -eq 0) { Close-Run 0 }",
    "    Close-Run 1",
    "} catch {",
    "    Write-Host ('jusshin: stopped -- {0}' -f $_.Exception.Message)",
    "    $script:Failed++",
    "    Close-Run 1",
    "}",
    "",
  ].join("\n");
}

// ── Linux and macOS ─────────────────────────────────────────────────────────

function posixPreamble(plan: RunnerPlan, version: string, what: string, runAs: string): string[] {
  const [owner, repo] = plan.target.split("/") as [string, string];
  return [
    "#!/usr/bin/env bash",
    ...header(plan, version, "#", "—", what),
    "#",
    ...runAs.split("\n").map((line): string => `# ${line}`.trimEnd()),
    "#",
    "# Exit codes: 0 every planned runner's service is running; 1 anything else;",
    "# 3 run as the wrong user; 5 gh missing or not signed in; 6 the runner",
    "# package failed its SHA-256 check (the file is deleted).",
    "set -euo pipefail",
    "",
    `TARGET=${sh(plan.target)}`,
    `REPO_URL=${sh(`https://github.com/${plan.target}`)}`,
    `LABELS=${sh(plan.labels.join(","))}`,
    `ROOT=${sh(plan.root)}`,
    `PROJECT_DIR=${sh(plan.projectDir)}`,
    `DOWNLOAD_URL=${sh(plan.download.download_url)}`,
    `ARCHIVE=${sh(plan.download.filename)}`,
    `SHA256=${sh(plan.download.sha256_checksum.toLowerCase())}`,
    `SERVICE_PREFIX=${sh(`actions.runner.${owner}-${repo}.`)}`,
    "RUNNERS=(",
    ...plan.runners.map((runner): string => `  ${sh(`${runner.name}|${runner.installDir}`)}`),
    ")",
    'WORK_DIR="$PROJECT_DIR/_jusshin"',
    "registered=0",
    "skipped=0",
    "failed=0",
    "",
    "finish() {",
    '  echo "jusshin: ${registered} registered, ${skipped} skipped, ${failed} failed"',
    '  exit "$1"',
    "}",
    "",
    "# Whether a runner directory is already configured as NAME (idempotent re-run).",
    "configured_as() {",
    '  [ -f "$1/.runner" ] && grep -q "\\"agentName\\": *\\"$2\\"" "$1/.runner"',
    "}",
    "",
  ];
}

function posixDownload(checker: string): string[] {
  return [
    'archive="$WORK_DIR/$ARCHIVE"',
    "verify_archive() {",
    `  echo "$SHA256  $archive" | ${checker} >/dev/null 2>&1`,
    "}",
    "if [ \"${#pending[@]}\" -gt 0 ]; then",
    '  if [ ! -f "$archive" ] || ! verify_archive; then',
    '    echo "jusshin: downloading $ARCHIVE"',
    '    curl -fsSL -o "$archive" "$DOWNLOAD_URL"',
    "    if ! verify_archive; then",
    '      rm -f "$archive"',
    '      echo "jusshin: $ARCHIVE failed its SHA-256 check (expected $SHA256) -- deleted."',
    "      finish 6",
    "    fi",
    "  fi",
    '  echo "jusshin: $ARCHIVE verified (sha256 $SHA256)."',
    "fi",
    "",
  ];
}

const POSIX_PENDING = [
  "pending=()",
  'for entry in "${RUNNERS[@]}"; do',
  '  name="${entry%%|*}"',
  '  dir="${entry#*|}"',
  '  if configured_as "$dir" "$name"; then',
  '    echo "jusshin: $name is already configured in $dir -- skipped."',
  "    skipped=$((skipped + 1))",
  "    continue",
  "  fi",
  '  if [ -f "$dir/.runner" ]; then',
  '    echo "jusshin: $dir holds a runner configured as another name, not $name -- left untouched."',
  "    failed=$((failed + 1))",
  "    continue",
  "  fi",
  '  pending+=("$entry")',
  "done",
  "",
];

export function renderLinux(plan: RunnerPlan, version: string): string {
  return [
    ...posixPreamble(
      plan,
      version,
      "as systemd services",
      "Run it as root, through sudo from your own account: sudo bash <this file>.\nconfig.sh runs as the service user (it refuses root), gh runs as YOU\n(SUDO_USER, with your own sign-in), and svc.sh installs the systemd unit as\nroot. The registration token is minted per runner into a variable that is\nnever printed.",
    ),
    `SERVICE_USER=${sh(plan.identity)}`,
    "",
    'if [ "$(id -u)" -ne 0 ]; then',
    '  echo "jusshin: run as root (sudo bash $0) -- this script installs systemd services."',
    "  finish 3",
    "fi",
    'if [ -z "${SUDO_USER:-}" ] || [ "$SUDO_USER" = root ]; then',
    '  echo "jusshin: run through sudo from your own account -- gh runs as that account (SUDO_USER), with its own sign-in."',
    "  finish 3",
    "fi",
    'as_invoker() { sudo -u "$SUDO_USER" -H "$@"; }',
    "if ! as_invoker gh --version >/dev/null 2>&1; then",
    '  echo "jusshin: gh is not on PATH for $SUDO_USER. Install the GitHub CLI and re-run."',
    "  finish 5",
    "fi",
    "if ! as_invoker gh auth status >/dev/null 2>&1; then",
    "  echo \"jusshin: 'gh auth status' failed for $SUDO_USER. Run 'gh auth login' and re-run.\"",
    "  finish 5",
    "fi",
    'if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then',
    '  echo "jusshin: the service user $SERVICE_USER does not exist. Create it (useradd --system --create-home $SERVICE_USER) and re-run."',
    "  finish 1",
    "fi",
    "",
    'mkdir -p "$ROOT" "$PROJECT_DIR" "$WORK_DIR"',
    'chmod 0755 "$ROOT" "$PROJECT_DIR"',
    'log="$WORK_DIR/register-$(date +%Y%m%d-%H%M%S).log"',
    'exec > >(tee -a "$log") 2>&1',
    'echo "jusshin: ${#RUNNERS[@]} runner(s) for $TARGET; log $log"',
    "",
    ...POSIX_PENDING,
    ...posixDownload("sha256sum -c -"),
    'for entry in "${pending[@]+"${pending[@]}"}"; do',
    '  name="${entry%%|*}"',
    '  dir="${entry#*|}"',
    '  echo "jusshin: registering $name in $dir"',
    '  install -d -o "$SERVICE_USER" -m 0755 "$dir"',
    '  sudo -u "$SERVICE_USER" tar xzf "$archive" -C "$dir"',
    '  token="$(as_invoker gh api -X POST "repos/$TARGET/actions/runners/registration-token" --jq .token 2>/dev/null)" || token=""',
    '  if [ -z "$token" ]; then',
    '    echo "jusshin: could not mint a registration token for $name; the gh user must be an admin of $TARGET."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  if ! (cd "$dir" && sudo -u "$SERVICE_USER" ./config.sh --unattended --url "$REPO_URL" --token "$token" --name "$name" --labels "$LABELS" --work _work); then',
    '    token=""',
    '    echo "jusshin: config.sh failed for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  token=""',
    '  if ! (cd "$dir" && ./svc.sh install "$SERVICE_USER" && ./svc.sh start && ./svc.sh status); then',
    '    echo "jusshin: svc.sh could not install or start the service for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  registered=$((registered + 1))",
    "done",
    "",
    "down=0",
    'for entry in "${RUNNERS[@]}"; do',
    '  name="${entry%%|*}"',
    '  if ! systemctl is-active --quiet "${SERVICE_PREFIX}${name}.service"; then',
    '    echo "jusshin: ${SERVICE_PREFIX}${name}.service is not active."',
    "    down=$((down + 1))",
    "  fi",
    "done",
    'systemctl list-units "${SERVICE_PREFIX}*" --all --no-pager || true',
    "",
    'if [ "$down" -eq 0 ] && [ "$failed" -eq 0 ]; then finish 0; fi',
    "finish 1",
    "",
  ].join("\n");
}

export function renderMac(plan: RunnerPlan, version: string): string {
  return [
    ...posixPreamble(
      plan,
      version,
      "as launchd agents",
      "Run it as YOURSELF, not with sudo: bash <this file>. A macOS runner is a\nLaunchAgent of the user who installs it. The registration token is minted\nper runner into a variable that is never printed.",
    ),
    'if [ "$(id -u)" -eq 0 ]; then',
    '  echo "jusshin: run as yourself, not root -- a macOS runner is a LaunchAgent of the user who installs it."',
    "  finish 3",
    "fi",
    "if ! gh --version >/dev/null 2>&1; then",
    '  echo "jusshin: gh is not on PATH. Install the GitHub CLI and re-run."',
    "  finish 5",
    "fi",
    "if ! gh auth status >/dev/null 2>&1; then",
    "  echo \"jusshin: 'gh auth status' failed. Run 'gh auth login' and re-run.\"",
    "  finish 5",
    "fi",
    "",
    'mkdir -p "$ROOT" "$PROJECT_DIR" "$WORK_DIR"',
    'log="$WORK_DIR/register-$(date +%Y%m%d-%H%M%S).log"',
    'exec > >(tee -a "$log") 2>&1',
    'echo "jusshin: ${#RUNNERS[@]} runner(s) for $TARGET; log $log"',
    "",
    ...POSIX_PENDING,
    ...posixDownload("shasum -a 256 -c -"),
    'for entry in "${pending[@]+"${pending[@]}"}"; do',
    '  name="${entry%%|*}"',
    '  dir="${entry#*|}"',
    '  echo "jusshin: registering $name in $dir"',
    '  mkdir -p "$dir"',
    '  tar xzf "$archive" -C "$dir"',
    '  token="$(gh api -X POST "repos/$TARGET/actions/runners/registration-token" --jq .token 2>/dev/null)" || token=""',
    '  if [ -z "$token" ]; then',
    '    echo "jusshin: could not mint a registration token for $name; the gh user must be an admin of $TARGET."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  if ! (cd "$dir" && ./config.sh --unattended --url "$REPO_URL" --token "$token" --name "$name" --labels "$LABELS" --work _work); then',
    '    token=""',
    '    echo "jusshin: config.sh failed for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    '  token=""',
    '  if ! (cd "$dir" && ./svc.sh install && ./svc.sh start); then',
    '    echo "jusshin: svc.sh could not install or start the LaunchAgent for $name."',
    "    failed=$((failed + 1))",
    "    continue",
    "  fi",
    "  registered=$((registered + 1))",
    "done",
    "",
    "# Background Task Management: a LaunchAgent macOS has not approved is loaded",
    "# with no PID ('-' in launchctl list). It is held pending approval under",
    "# System Settings > General > Login Items; this script never approves it.",
    "down=0",
    'for entry in "${RUNNERS[@]}"; do',
    '  name="${entry%%|*}"',
    '  label="${SERVICE_PREFIX}${name}"',
    '  launchctl print "gui/$(id -u)/$label" 2>/dev/null | grep -E "^[[:space:]]*(state|pid) =" || true',
    '  pid="$(launchctl list | while read -r p _ l; do if [ "$l" = "$label" ]; then echo "$p"; fi; done)"',
    '  if [ -z "$pid" ] || [ "$pid" = "-" ]; then',
    '    echo "jusshin: $label has no PID -- if it is listed, it is held pending approval under System Settings > General > Login Items (approve it there; nen never does)."',
    "    down=$((down + 1))",
    "  fi",
    "done",
    "",
    'if [ "$down" -eq 0 ] && [ "$failed" -eq 0 ]; then finish 0; fi',
    "finish 1",
    "",
  ].join("\n");
}

/** Render the plan's host script. The plan has already passed `validatePlan`. */
export function renderScript(plan: RunnerPlan, version: string): RenderedScript {
  if (plan.os === "Windows") return { os: plan.os, text: renderWindows(plan, version), needsElevation: true };
  if (plan.os === "Linux") return { os: plan.os, text: renderLinux(plan, version), needsElevation: true };
  return { os: plan.os, text: renderMac(plan, version), needsElevation: false };
}

/** The one command line the caller runs the script with. */
export function launchLine(os: RunnerPlan["os"], out: string): string {
  if (os === "Windows") {
    return `powershell -NoProfile -ExecutionPolicy Bypass -Command "Start-Process powershell -Verb RunAs -Wait -ArgumentList '-NoProfile','-ExecutionPolicy','Bypass','-File','${out}'"`;
  }
  if (os === "Linux") return `sudo bash ${out}`;
  return `bash ${out}`;
}
